from _typeshed import Incomplete

def degree_assortativity_coefficient(G, x: str = ..., y: str = ..., weight: Incomplete | None = ..., nodes: Incomplete | None = ...): ...
def degree_pearson_correlation_coefficient(G, x: str = ..., y: str = ..., weight: Incomplete | None = ..., nodes: Incomplete | None = ...): ...
def attribute_assortativity_coefficient(G, attribute, nodes: Incomplete | None = ...): ...
def numeric_assortativity_coefficient(G, attribute, nodes: Incomplete | None = ...): ...
