from _typeshed import Incomplete

def attribute_mixing_dict(G, attribute, nodes: Incomplete | None = ..., normalized: bool = ...): ...
def attribute_mixing_matrix(G, attribute, nodes: Incomplete | None = ..., mapping: Incomplete | None = ..., normalized: bool = ...): ...
def degree_mixing_dict(G, x: str = ..., y: str = ..., weight: Incomplete | None = ..., nodes: Incomplete | None = ..., normalized: bool = ...): ...
def degree_mixing_matrix(G, x: str = ..., y: str = ..., weight: Incomplete | None = ..., nodes: Incomplete | None = ..., normalized: bool = ..., mapping: Incomplete | None = ...): ...
def numeric_mixing_matrix(G, attribute, nodes: Incomplete | None = ..., normalized: bool = ..., mapping: Incomplete | None = ...): ...
def mixing_dict(xy, normalized: bool = ...): ...
