from _typeshed import Incomplete

def imread(fname, as_gray: bool = ..., plugin: Incomplete | None = ..., **plugin_args): ...
def imread_collection(load_pattern, conserve_memory: bool = ..., plugin: Incomplete | None = ..., **plugin_args): ...
def imsave(fname, arr, plugin: Incomplete | None = ..., check_contrast: bool = ..., **plugin_args): ...
def imshow(arr, plugin: Incomplete | None = ..., **plugin_args): ...
def imshow_collection(ic, plugin: Incomplete | None = ..., **plugin_args): ...
def show(): ...
