from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _bezier_curve(*args, **kwargs) -> Any: ...
def _bezier_segment(*args, **kwargs) -> Any: ...
def _circle_perimeter(*args, **kwargs) -> Any: ...
def _circle_perimeter_aa(*args, **kwargs) -> Any: ...
def _coords_inside_image(*args, **kwargs) -> Any: ...
def _ellipse_perimeter(*args, **kwargs) -> Any: ...
def _line(*args, **kwargs) -> Any: ...
def _line_aa(*args, **kwargs) -> Any: ...
def _polygon(*args, **kwargs) -> Any: ...
