from .._shared._geometry import polygon_clip as polygon_clip
from .._shared.version_requirements import require as require
from _typeshed import Incomplete

def ellipse(r, c, r_radius, c_radius, shape: Incomplete | None = ..., rotation: float = ...): ...
def disk(center, radius, *, shape: Incomplete | None = ...): ...
def polygon_perimeter(r, c, shape: Incomplete | None = ..., clip: bool = ...): ...
def set_color(image, coords, color, alpha: int = ...) -> None: ...
def line(r0, c0, r1, c1): ...
def line_aa(r0, c0, r1, c1): ...
def polygon(r, c, shape: Incomplete | None = ...): ...
def circle_perimeter(r, c, radius, method: str = ..., shape: Incomplete | None = ...): ...
def circle_perimeter_aa(r, c, radius, shape: Incomplete | None = ...): ...
def ellipse_perimeter(r, c, r_radius, c_radius, orientation: int = ..., shape: Incomplete | None = ...): ...
def bezier_curve(r0, c0, r1, c1, r2, c2, weight, shape: Incomplete | None = ...): ...
def rectangle(start, end: Incomplete | None = ..., extent: Incomplete | None = ..., shape: Incomplete | None = ...): ...
def rectangle_perimeter(start, end: Incomplete | None = ..., extent: Incomplete | None = ..., shape: Incomplete | None = ..., clip: bool = ...): ...
