from _typeshed import Incomplete

def average_degree_connectivity(G, source: str = ..., target: str = ..., nodes: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def k_nearest_neighbors(G, source: str = ..., target: str = ..., nodes: Incomplete | None = ..., weight: Incomplete | None = ...): ...
