from . import interfaces as interfaces
from _typeshed import Incomplete

def difference(meshes, engine: Incomplete | None = ..., **kwargs): ...
def union(meshes, engine: Incomplete | None = ..., **kwargs): ...
def intersection(meshes, engine: Incomplete | None = ..., **kwargs): ...
def boolean_automatic(meshes, operation, **kwargs): ...
