from . import convex as convex, exceptions as exceptions, geometry as geometry, grouping as grouping, nsphere as nsphere, transformations as transformations, triangles as triangles, util as util
from .constants import log as log
from time import perf_counter as now
from _typeshed import Incomplete

def oriented_bounds_2D(points, qhull_options: str = ...): ...
def oriented_bounds(obj, angle_digits: int = ..., ordered: bool = ..., normal: Incomplete | None = ...): ...
def minimum_cylinder(obj, sample_count: int = ..., angle_tol: float = ...): ...
def to_extents(bounds): ...
def corners(bounds): ...
def contains(bounds, points): ...
