from . import triangles as triangles, util as util
from .constants import tol as tol
from .exceptions import ExceptionModule as ExceptionModule

def convex_hull(obj, qhull_options: str = ...): ...
def adjacency_projections(mesh): ...
def is_convex(mesh): ...
def hull_points(obj, qhull_options: str = ...): ...
