from . import exceptions as exceptions, util as util

def face_angles_sparse(mesh): ...
def vertex_defects(mesh): ...
def discrete_gaussian_curvature_measure(mesh, points, radius): ...
def discrete_mean_curvature_measure(mesh, points, radius): ...
def line_ball_intersection(start_points, end_points, center, radius): ...
def sphere_ball_intersection(R, r): ...
