from . import exceptions as exceptions, util as util
from .constants import log as log
from _typeshed import Incomplete

def plane_transform(origin, normal): ...
def align_vectors(a, b, return_angle: bool = ...): ...
def faces_to_edges(faces, return_index: bool = ...): ...
def vector_angle(pairs): ...
def triangulate_quads(quads, dtype=...): ...
def vertex_face_indices(vertex_count, faces, faces_sparse): ...
def mean_vertex_normals(vertex_count, faces, face_normals, sparse: Incomplete | None = ..., **kwargs): ...
def weighted_vertex_normals(vertex_count, faces, face_normals, face_angles, use_loop: bool = ...): ...
def index_sparse(columns, indices, data: Incomplete | None = ...): ...
