from . import geometry as geometry, grouping as grouping, util as util
from .constants import tol as tol
from _typeshed import Incomplete

def mesh_plane(mesh, plane_normal, plane_origin, return_faces: bool = ..., local_faces: Incomplete | None = ..., cached_dots: Incomplete | None = ...): ...
def mesh_multiplane(mesh, plane_origin, plane_normal, heights): ...
def plane_lines(plane_origin, plane_normal, endpoints, line_segments: bool = ...): ...
def planes_lines(plane_origins, plane_normals, line_origins, line_directions, return_distance: bool = ..., return_denom: bool = ...): ...
def slice_faces_plane(vertices, faces, plane_normal, plane_origin, face_index: Incomplete | None = ..., cached_dots: Incomplete | None = ...): ...
def slice_mesh_plane(mesh, plane_normal, plane_origin, face_index: Incomplete | None = ..., cap: bool = ..., cached_dots: Incomplete | None = ..., **kwargs): ...
