from . import convex as convex, exceptions as exceptions, util as util
from .constants import log as log, tol as tol
from _typeshed import Incomplete

def minimum_nsphere(obj): ...
def fit_nsphere(points, prior: Incomplete | None = ...): ...
def is_nsphere(points): ...
