from . import util as util
from _typeshed import Incomplete

GL_POINTS: Incomplete
GL_LINES: Incomplete
GL_TRIANGLES: Incomplete

def convert_to_vertexlist(geometry, **kwargs): ...
def mesh_to_vertexlist(mesh, group: Incomplete | None = ..., smooth: bool = ..., smooth_threshold: int = ...): ...
def path_to_vertexlist(path, group: Incomplete | None = ..., **kwargs): ...
def points_to_vertexlist(points, colors: Incomplete | None = ..., group: Incomplete | None = ..., **kwargs): ...
def colors_to_gl(colors, count): ...
def material_to_texture(material, upsize: bool = ...): ...
def matrix_to_gl(matrix): ...
def vector_to_gl(array, *args): ...
def light_to_gl(light, transform, lightN): ...
