from . import transformations as transformations, util as util
from .visual import uv_to_interpolated_color as uv_to_interpolated_color
from _typeshed import Incomplete

def sample_surface(mesh, count, face_weight: Incomplete | None = ..., sample_color: bool = ...): ...
def volume_mesh(mesh, count): ...
def volume_rectangular(extents, count, transform: Incomplete | None = ...): ...
def sample_surface_even(mesh, count, radius: Incomplete | None = ...): ...
def sample_surface_sphere(count): ...
