from . import util as util
from .constants import tol as tol
from .points import point_plane_distance as point_plane_distance
from .util import diagonal_dot as diagonal_dot, unitize as unitize
from _typeshed import Incomplete

def cross(triangles): ...
def area(triangles: Incomplete | None = ..., crosses: Incomplete | None = ..., sum: bool = ...): ...
def normals(triangles: Incomplete | None = ..., crosses: Incomplete | None = ...): ...
def angles(triangles): ...
def all_coplanar(triangles): ...
def any_coplanar(triangles): ...
def mass_properties(triangles, crosses: Incomplete | None = ..., density: float = ..., center_mass: Incomplete | None = ..., skip_inertia: bool = ...): ...
def windings_aligned(triangles, normals_compare): ...
def bounds_tree(triangles): ...
def nondegenerate(triangles, areas: Incomplete | None = ..., height: Incomplete | None = ...): ...
def extents(triangles, areas: Incomplete | None = ...): ...
def barycentric_to_points(triangles, barycentric): ...
def points_to_barycentric(triangles, points, method: str = ...): ...
def closest_point(triangles, points): ...
def to_kwargs(triangles): ...
