import numpy as np
from pandas._typing import npt as npt
from pandas.core.nanops import check_below_min_count as check_below_min_count

def sum(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = ..., min_count: int = ..., axis: Union[int, None] = ...): ...
def prod(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = ..., min_count: int = ..., axis: Union[int, None] = ...): ...
def min(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = ..., axis: Union[int, None] = ...): ...
def max(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = ..., axis: Union[int, None] = ...): ...
def mean(values: np.ndarray, mask: npt.NDArray[np.bool_], skipna: bool = ...): ...
