import numpy as np
from pandas._libs import lib as lib
from pandas._typing import ArrayLike as ArrayLike, npt as npt
from pandas.compat import np_version_under1p21 as np_version_under1p21
from pandas.core.arrays import ExtensionArray as ExtensionArray
from pandas.core.dtypes.cast import infer_dtype_from as infer_dtype_from
from pandas.core.dtypes.common import is_list_like as is_list_like
from typing import Any

def putmask_inplace(values: ArrayLike, mask: npt.NDArray[np.bool_], value: Any) -> None: ...
def putmask_without_repeat(values: np.ndarray, mask: npt.NDArray[np.bool_], new: Any) -> None: ...
def validate_putmask(values: ArrayLike, mask: np.ndarray) -> tuple[npt.NDArray[np.bool_], bool]: ...
def extract_bool_array(mask: ArrayLike) -> npt.NDArray[np.bool_]: ...
def setitem_datetimelike_compat(values: np.ndarray, num_set: int, other): ...
