from _typeshed import Incomplete
from scipy.sparse import csc_matrix as csc_matrix, csr_matrix as csr_matrix

TOLS: Incomplete

def is_complex_type(dtype): ...
def is_32bit(): ...
def is_windows(): ...

marks: Incomplete

def generate_matrix(constructor, n, m, f, dtype=..., rseed: int = ..., **kwargs): ...
def assert_orthogonal(u1, u2, rtol, atol) -> None: ...
def check_svdp(n, m, constructor, dtype, k, irl_mode, which, f: float = ...) -> None: ...
def test_svdp(ctor, dtype, irl, which) -> None: ...
def test_examples(dtype, irl) -> None: ...
def test_shifts(shifts, dtype) -> None: ...
def test_shifts_accuracy() -> None: ...
