from _typeshed import Incomplete

pytestmark: Incomplete
msg: str
sparse_params: Incomplete
scipy_sparse_classes: Incomplete

def sparse_cls(request): ...
def sp_sparse_cls(request): ...
def same_matrix(sparse_cls, sp_sparse_cls): ...
def matrices(sparse_cls): ...
def test_isolve_gmres(matrices) -> None: ...
def test_lsmr(matrices) -> None: ...
def test_lsmr_output_shape() -> None: ...
def test_lsqr(matrices) -> None: ...
def test_eigs(matrices) -> None: ...
def test_svds(matrices) -> None: ...
def test_lobpcg(matrices) -> None: ...
def test_spsolve(matrices) -> None: ...
def test_splu(matrices) -> None: ...
def test_spilu(matrices) -> None: ...
def test_spsolve_triangular(matrices) -> None: ...
def test_onenormest(matrices) -> None: ...
def test_inv(matrices) -> None: ...
def test_expm(matrices) -> None: ...
def test_expm_multiply(matrices) -> None: ...
def test_eq(same_matrix) -> None: ...
def test_ne(same_matrix) -> None: ...
