from _typeshed import Incomplete
from scipy.sparse._sputils import matrix as matrix

class TestLinearOperator:
    A: Incomplete
    B: Incomplete
    C: Incomplete
    def setup_method(self) -> None: ...
    def test_matvec(self): ...
    def test_matmul(self): ...

class TestAsLinearOperator:
    cases: Incomplete
    dtype: Incomplete
    shape: Incomplete
    def setup_method(self): ...
    def test_basic(self) -> None: ...
    def test_dot(self) -> None: ...

def test_repr(): ...
def test_identity() -> None: ...
def test_attributes(): ...
def matvec(x): ...
def test_pickle() -> None: ...
def test_inheritance(): ...
def test_dtypes_of_operator_sum() -> None: ...
def test_no_double_init(): ...
def test_adjoint_conjugate() -> None: ...
def test_ndim() -> None: ...
def test_transpose_noconjugate() -> None: ...
def test_sparse_matmat_exception(): ...
