from _typeshed import Incomplete

def test_sparray_norm() -> None: ...

class TestNorm:
    b: Incomplete
    def setup_method(self) -> None: ...
    def test_matrix_norm(self) -> None: ...
    def test_matrix_norm_axis(self) -> None: ...
    def test_vector_norm(self) -> None: ...
    def test_norm_exceptions(self) -> None: ...

class TestVsNumpyNorm:
    def test_sparse_matrix_norms(self) -> None: ...
    def test_sparse_matrix_norms_with_axis(self) -> None: ...
    def test_sparse_vector_norms(self) -> None: ...
