from openpyxl.descriptors.serialisable import Serialisable as Serialisable
from openpyxl.workbook import Workbook
from pandas._typing import FilePath as FilePath, ReadBuffer as ReadBuffer, Scalar as Scalar, StorageOptions as StorageOptions, WriteExcelBuffer as WriteExcelBuffer
from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.io.excel._base import BaseExcelReader as BaseExcelReader, ExcelWriter as ExcelWriter
from pandas.io.excel._util import combine_kwargs as combine_kwargs, validate_freeze_panes as validate_freeze_panes
from pandas.util._decorators import doc as doc
from typing import Any

class OpenpyxlWriter(ExcelWriter):
    def __init__(self, path: Union[FilePath, WriteExcelBuffer, ExcelWriter], engine: Union[str, None] = ..., date_format: Union[str, None] = ..., datetime_format: Union[str, None] = ..., mode: str = ..., storage_options: StorageOptions = ..., if_sheet_exists: Union[str, None] = ..., engine_kwargs: Union[dict[str, Any], None] = ..., **kwargs) -> None: ...
    @property
    def book(self) -> Workbook: ...
    @book.setter
    def book(self, other: Workbook) -> None: ...
    @property
    def sheets(self) -> dict[str, Any]: ...

class OpenpyxlReader(BaseExcelReader):
    def __init__(self, filepath_or_buffer: Union[FilePath, ReadBuffer[bytes]], storage_options: StorageOptions = ...) -> None: ...
    def load_workbook(self, filepath_or_buffer: Union[FilePath, ReadBuffer[bytes]]): ...
    @property
    def sheet_names(self) -> list[str]: ...
    def get_sheet_by_name(self, name: str): ...
    def get_sheet_by_index(self, index: int): ...
    def get_sheet_data(self, sheet, convert_float: bool, file_rows_needed: Union[int, None] = ...) -> list[list[Scalar]]: ...
