from pandas._typing import FilePath as FilePath, ReadBuffer as ReadBuffer, Scalar as Scalar, StorageOptions as StorageOptions
from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.io.excel._base import BaseExcelReader as BaseExcelReader
from pandas.util._decorators import doc as doc

class PyxlsbReader(BaseExcelReader):
    def __init__(self, filepath_or_buffer: Union[FilePath, ReadBuffer[bytes]], storage_options: StorageOptions = ...) -> None: ...
    def load_workbook(self, filepath_or_buffer: Union[FilePath, ReadBuffer[bytes]]): ...
    @property
    def sheet_names(self) -> list[str]: ...
    def get_sheet_by_name(self, name: str): ...
    def get_sheet_by_index(self, index: int): ...
    def get_sheet_data(self, sheet, convert_float: bool, file_rows_needed: Union[int, None] = ...) -> list[list[Scalar]]: ...
