from ..qt import FigureCanvasQTAgg
from _typeshed import Incomplete
from matplotlib.colors import LinearSegmentedColormap

def init_qtapp(): ...
def start_qtapp(app: Incomplete | None = ...) -> None: ...

class RequiredAttr:
    instances: Incomplete
    def __init__(self, init_val: Incomplete | None = ...) -> None: ...
    def __get__(self, obj, objtype): ...
    def __set__(self, obj, value) -> None: ...

class LinearColormap(LinearSegmentedColormap):
    def __init__(self, name, segmented_data, **kwargs) -> None: ...

class ClearColormap(LinearColormap):
    def __init__(self, rgb, max_alpha: int = ..., name: str = ...) -> None: ...

class FigureCanvas(FigureCanvasQTAgg):
    fig: Incomplete
    def __init__(self, figure, **kwargs) -> None: ...
    def resizeEvent(self, event) -> None: ...

def new_plot(parent: Incomplete | None = ..., subplot_kw: Incomplete | None = ..., **fig_kw): ...
def figimage(image, scale: int = ..., dpi: Incomplete | None = ..., **kwargs): ...
def update_axes_image(image_axes, image) -> None: ...
