from typing import Any, ClassVar

integral_image: function
rgb2gray: function

class Cascade:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    eps: Any
    features_number: Any
    stages_number: Any
    stumps_number: Any
    window_height: Any
    window_width: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def _get_contiguous_integral_image(self, *args, **kwargs) -> Any: ...
    def _get_valid_scale_factors(self, *args, **kwargs) -> Any: ...
    def _load_xml(self, *args, **kwargs) -> Any: ...
    def detect_multi_scale(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
