from networkx import NetworkXError

class NotAPartition(NetworkXError):
    def __init__(self, G, collection) -> None: ...

def performance(G, partition): ...
def coverage(G, partition): ...
def modularity(G, communities, weight: str = ..., resolution: int = ...): ...
def partition_quality(G, partition): ...
