from typing import Any

DAYS: list
DAYS_FULL: list
MONTHS: list
MONTHS_FULL: list
MONTH_ALIASES: dict
MONTH_NUMBERS: dict
MONTH_TO_CAL_NUM: dict
int_to_weekday: dict
weekday_to_int: dict

def get_day_of_year(*args, **kwargs) -> Any: ...
def get_days_in_month(*args, **kwargs) -> Any: ...
def get_firstbday(*args, **kwargs) -> Any: ...
def get_iso_calendar(*args, **kwargs) -> Any: ...
def get_lastbday(*args, **kwargs) -> Any: ...
def get_week_of_year(*args, **kwargs) -> Any: ...
