from typing import Any

import numpy
DT64NS_DTYPE: numpy.dtype[datetime64]
TD64NS_DTYPE: numpy.dtype[timedelta64]
find_stack_level: function

class OutOfBoundsDatetime(ValueError): ...

class OutOfBoundsTimedelta(ValueError): ...

class _TSObject:
    dts: Any
    fold: Any
    tzinfo: Any
    value: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def localize_pydatetime(*args, **kwargs) -> Any: ...
def parse_datetime_string(*args, **kwargs) -> Any: ...
def precision_from_unit(*args, **kwargs) -> Any: ...
