from typing import Any, ClassVar

DAYS_FULL: list
LC_TIME: int
MONTHS_FULL: list
set_locale: function

class LocaleTime:
    __init__: ClassVar[function] = ...
    _LocaleTime__calc_am_pm: ClassVar[function] = ...
    _LocaleTime__calc_date_time: ClassVar[function] = ...
    _LocaleTime__calc_month: ClassVar[function] = ...
    _LocaleTime__calc_timezone: ClassVar[function] = ...
    _LocaleTime__calc_weekday: ClassVar[function] = ...

class RoundTo:
    @property
    def MINUS_INFTY(self) -> Any: ...
    @property
    def NEAREST_HALF_EVEN(self) -> Any: ...
    @property
    def NEAREST_HALF_MINUS_INFTY(self) -> Any: ...
    @property
    def NEAREST_HALF_PLUS_INFTY(self) -> Any: ...
    @property
    def PLUS_INFTY(self) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _get_locale_names(*args, **kwargs) -> Any: ...
def build_field_sarray(*args, **kwargs) -> Any: ...
def build_isocalendar_sarray(*args, **kwargs) -> Any: ...
def get_date_field(*args, **kwargs) -> Any: ...
def get_date_name_field(*args, **kwargs) -> Any: ...
def get_start_end_field(*args, **kwargs) -> Any: ...
def get_timedelta_field(*args, **kwargs) -> Any: ...
def isleapyear_arr(*args, **kwargs) -> Any: ...
def month_position_check(*args, **kwargs) -> Any: ...
def round_nsint64(*args, **kwargs) -> Any: ...
