from typing import Any, ClassVar

import _strptime
import _thread
_CACHE_MAX_SIZE: int
_TimeRE_cache: TimeRE
_cache_lock: _thread.lock
_getlang: function
_regex_cache: dict

class LocaleTime:
    __init__: ClassVar[function] = ...
    _LocaleTime__calc_am_pm: ClassVar[function] = ...
    _LocaleTime__calc_date_time: ClassVar[function] = ...
    _LocaleTime__calc_month: ClassVar[function] = ...
    _LocaleTime__calc_timezone: ClassVar[function] = ...
    _LocaleTime__calc_weekday: ClassVar[function] = ...

class TimeRE(_strptime.TimeRE):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, index) -> Any: ...

class _TimeRE(dict):
    __init__: ClassVar[function] = ...
    _TimeRE__seqToRE: ClassVar[function] = ...
    compile: ClassVar[function] = ...
    pattern: ClassVar[function] = ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _thread_allocate_lock(*args, **kwargs) -> Any: ...
def array_strptime(*args, **kwargs) -> Any: ...
