from typing import Any, ClassVar

class Localizer:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def tz_convert_from_utc_single(*args, **kwargs) -> Any: ...
def tz_localize_to_utc(*args, **kwargs) -> Any: ...
