from _typeshed import Incomplete

def hits(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...): ...
def authority_matrix(G, nodelist: Incomplete | None = ...): ...
def hub_matrix(G, nodelist: Incomplete | None = ...): ...
def hits_numpy(G, normalized: bool = ...): ...
def hits_scipy(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ...): ...
