from _typeshed import Incomplete

def expm_multiply(A, B, start: Incomplete | None = ..., stop: Incomplete | None = ..., num: Incomplete | None = ..., endpoint: Incomplete | None = ..., traceA: Incomplete | None = ...): ...

class LazyOperatorNormInfo:
    def __init__(self, A, A_1_norm: Incomplete | None = ..., ell: int = ..., scale: int = ...) -> None: ...
    def set_scale(self, scale) -> None: ...
    def onenorm(self): ...
    def d(self, p): ...
    def alpha(self, p): ...
