import networkx as nx
from _typeshed import Incomplete
from collections.abc import Generator, Mapping

def k_components(G, min_density: float = ...): ...

class _AntiGraph(nx.Graph):
    all_edge_dict: Incomplete
    def single_edge_dict(self): ...
    edge_attr_dict_factory: Incomplete
    def __getitem__(self, n): ...
    def neighbors(self, n): ...
    class AntiAtlasView(Mapping):
        def __init__(self, graph, node) -> None: ...
        def __len__(self) -> int: ...
        def __iter__(self): ...
        def __getitem__(self, nbr): ...
    class AntiAdjacencyView(AntiAtlasView):
        def __init__(self, graph) -> None: ...
        def __len__(self) -> int: ...
        def __iter__(self): ...
        def __getitem__(self, node): ...
    def adj(self): ...
    def subgraph(self, nodes): ...
    class AntiDegreeView(nx.reportviews.DegreeView):
        def __iter__(self): ...
        def __getitem__(self, n): ...
    def degree(self): ...
    def adjacency(self) -> Generator[Incomplete, None, None]: ...
