from _typeshed import Incomplete

def ensure_python_version(min_version) -> None: ...
def get_module_version(module_name): ...
def is_installed(name, version: Incomplete | None = ...): ...
def require(name, version: Incomplete | None = ...): ...
def get_module(module_name, version: Incomplete | None = ...): ...
