import numpy as np
from pandas._libs import lib as lib, missing as libmissing

def kleene_or(left: Union[bool, np.ndarray, libmissing.NAType], right: Union[bool, np.ndarray, libmissing.NAType], left_mask: Union[np.ndarray, None], right_mask: Union[np.ndarray, None]): ...
def kleene_xor(left: Union[bool, np.ndarray, libmissing.NAType], right: Union[bool, np.ndarray, libmissing.NAType], left_mask: Union[np.ndarray, None], right_mask: Union[np.ndarray, None]): ...
def kleene_and(left: Union[bool, libmissing.NAType, np.ndarray], right: Union[bool, libmissing.NAType, np.ndarray], left_mask: Union[np.ndarray, None], right_mask: Union[np.ndarray, None]): ...
def raise_for_nan(value, method: str) -> None: ...
