from _typeshed import Incomplete

def dist(x1, x2): ...
def sinkhorn(w1, w2, M, reg, k): ...
def split_classes(X, y): ...
def fda(X, y, p: int = ..., reg: float = ...): ...
def wda(X, y, p: int = ..., reg: int = ..., k: int = ..., solver: Incomplete | None = ..., maxiter: int = ..., verbose: int = ..., P0: Incomplete | None = ...): ...
