from .bregman import sinkhorn as sinkhorn
from .lp import emd as emd
from _typeshed import Incomplete

def line_search_armijo(f, xk, pk, gfk, old_fval, args=..., c1: float = ..., alpha0: float = ...): ...
def solve_linesearch(cost, G, deltaG, Mi, f_val, armijo: bool = ..., C1: Incomplete | None = ..., C2: Incomplete | None = ..., reg: Incomplete | None = ..., Gc: Incomplete | None = ..., constC: Incomplete | None = ..., M: Incomplete | None = ...): ...
def cg(a, b, M, reg, f, df, G0: Incomplete | None = ..., numItermax: int = ..., numItermaxEmd: int = ..., stopThr: float = ..., stopThr2: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
def gcg(a, b, M, reg1, reg2, f, df, G0: Incomplete | None = ..., numItermax: int = ..., numInnerItermax: int = ..., stopThr: float = ..., stopThr2: float = ..., verbose: bool = ..., log: bool = ...): ...
def solve_1d_linesearch_quad(a, b, c): ...
