from _typeshed import Incomplete

def coordinate_grad_semi_dual(b, M, reg, beta, i): ...
def sag_entropic_transport(a, b, M, reg, numItermax: int = ..., lr: Incomplete | None = ...): ...
def averaged_sgd_entropic_transport(a, b, M, reg, numItermax: int = ..., lr: Incomplete | None = ...): ...
def c_transform_entropic(b, M, reg, beta): ...
def solve_semi_dual_entropic(a, b, M, reg, method, numItermax: int = ..., lr: Incomplete | None = ..., log: bool = ...): ...
def batch_grad_dual(a, b, M, reg, alpha, beta, batch_size, batch_alpha, batch_beta): ...
def sgd_entropic_regularization(a, b, M, reg, batch_size, numItermax, lr): ...
def solve_dual_entropic(a, b, M, reg, batch_size, numItermax: int = ..., lr: int = ..., log: bool = ...): ...
