from _typeshed import Incomplete

def sinkhorn_unbalanced(a, b, M, reg, reg_m, method: str = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
def sinkhorn_unbalanced2(a, b, M, reg, reg_m, method: str = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
def sinkhorn_knopp_unbalanced(a, b, M, reg, reg_m, numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
def sinkhorn_stabilized_unbalanced(a, b, M, reg, reg_m, tau: float = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
def barycenter_unbalanced_stabilized(A, M, reg, reg_m, weights: Incomplete | None = ..., tau: float = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ...): ...
def barycenter_unbalanced_sinkhorn(A, M, reg, reg_m, weights: Incomplete | None = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ...): ...
def barycenter_unbalanced(A, M, reg, reg_m, method: str = ..., weights: Incomplete | None = ..., numItermax: int = ..., stopThr: float = ..., verbose: bool = ..., log: bool = ..., **kwargs): ...
