from .externals.funcsigs import signature as signature
from _typeshed import Incomplete

def tic() -> None: ...
def toc(message: str = ...): ...
def toq(): ...
def kernel(x1, x2, method: str = ..., sigma: int = ..., **kwargs): ...
def laplacian(x): ...
def unif(n): ...
def clean_zeros(a, b, M): ...
def euclidean_distances(X, Y, squared: bool = ...): ...
def dist(x1, x2: Incomplete | None = ..., metric: str = ...): ...
def dist0(n, method: str = ...): ...
def cost_normalization(C, norm: Incomplete | None = ...): ...
def dots(*args): ...
def label_normalization(y, start: int = ...): ...
def fun(f, q_in, q_out) -> None: ...
def parmap(f, X, nprocs=...): ...
def check_params(**kwargs): ...
def check_random_state(seed): ...

class deprecated:
    extra: Incomplete
    def __init__(self, extra: str = ...) -> None: ...
    def __call__(self, obj): ...

class BaseEstimator:
    def get_params(self, deep: bool = ...): ...
    def set_params(self, **params): ...

class UndefinedParameter(Exception): ...
