def dtype_limits(image, clip_negative: bool = ...): ...
def img_as_float32(image, force_copy: bool = ...): ...
def img_as_float64(image, force_copy: bool = ...): ...
def img_as_float(image, force_copy: bool = ...): ...
def img_as_uint(image, force_copy: bool = ...): ...
def img_as_int(image, force_copy: bool = ...): ...
def img_as_ubyte(image, force_copy: bool = ...): ...
def img_as_bool(image, force_copy: bool = ...): ...
