from . import ops as ops
from .. import util as util
from ..constants import log_time as log_time
from ..exceptions import ExceptionModule as ExceptionModule
from _typeshed import Incomplete

def fill_base(encoding): ...
def fill_orthographic(encoding): ...
def fill_holes(encoding, **kwargs): ...

fillers: Incomplete

def fill(encoding, method: str = ..., **kwargs): ...
def binary_dilation(encoding, **kwargs): ...
def binary_closing(encoding, **kwargs): ...
def surface(encoding, structure: Incomplete | None = ...): ...
