from .. import util as util
from ..constants import log as log
from _typeshed import Incomplete

def fill_orthographic(dense): ...
def fill_base(sparse_indices): ...
fill_voxelization = fill_base

def matrix_to_marching_cubes(matrix, pitch: float = ...): ...
def sparse_to_matrix(sparse): ...
def points_to_marching_cubes(points, pitch: float = ...): ...
def multibox(centers, pitch: float = ..., colors: Incomplete | None = ...): ...
def boolean_sparse(a, b, operation=...): ...
def strip_array(data): ...
def indices_to_points(indices, pitch: Incomplete | None = ..., origin: Incomplete | None = ...): ...
def matrix_to_points(matrix, pitch: Incomplete | None = ..., origin: Incomplete | None = ...): ...
def points_to_indices(points, pitch: Incomplete | None = ..., origin: Incomplete | None = ...): ...
