from _typeshed import Incomplete
from collections.abc import Generator

def brle_length(brle): ...
def rle_length(rle): ...
def rle_to_brle(rle, dtype: Incomplete | None = ...): ...
def brle_logical_not(brle): ...
def merge_brle_lengths(lengths): ...
def split_long_brle_lengths(lengths, dtype=...): ...
def dense_to_brle(dense_data, dtype=...): ...
def brle_to_dense(brle_data, vals: Incomplete | None = ...): ...
def rle_to_dense(rle_data, dtype=...): ...
def dense_to_rle(dense_data, dtype=...): ...
def split_long_rle_lengths(values, lengths, dtype=...): ...
def merge_rle_lengths(values, lengths): ...
def brle_to_rle(brle, dtype=...): ...
def brle_to_brle(brle, dtype=...): ...
def rle_to_rle(rle, dtype=...): ...
def sorted_rle_gather_1d(rle_data, ordered_indices) -> Generator[Incomplete, None, None]: ...
def rle_mask(rle_data, mask) -> Generator[Incomplete, None, None]: ...
def brle_mask(rle_data, mask) -> Generator[Incomplete, None, None]: ...
def rle_gatherer_1d(indices): ...
def rle_gather_1d(rle_data, indices, dtype: Incomplete | None = ...): ...
def sorted_brle_gather_1d(brle_data, ordered_indices) -> Generator[Incomplete, None, None]: ...
def brle_gatherer_1d(indices): ...
def brle_gather_1d(brle_data, indices): ...
def brle_reverse(brle_data): ...
def rle_reverse(rle_data): ...
def rle_to_sparse(rle_data): ...
def brle_to_sparse(brle_data, dtype=...): ...
def rle_strip(rle_data): ...
def brle_strip(brle_data): ...
