from .. import caching as caching, util as util

class Transform:
    def __init__(self, matrix) -> None: ...
    def crc(self): ...
    def hash(self): ...
    def __hash__(self): ...
    @property
    def translation(self): ...
    @property
    def matrix(self): ...
    @matrix.setter
    def matrix(self, data) -> None: ...
    def scale(self): ...
    def pitch(self): ...
    def unit_volume(self): ...
    def apply_transform(self, matrix): ...
    def apply_translation(self, translation): ...
    def apply_scale(self, scale): ...
    def transform_points(self, points): ...
    def inverse_transform_points(self, points): ...
    def inverse_matrix(self): ...
    def copy(self): ...
    def is_identity(self): ...
