from _typeshed import Incomplete

def cut_size(G, S, T: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def volume(G, S, weight: Incomplete | None = ...): ...
def normalized_cut_size(G, S, T: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def conductance(G, S, T: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def edge_expansion(G, S, T: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def mixing_expansion(G, S, T: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def node_expansion(G, S): ...
def boundary_expansion(G, S): ...
