import numpy as np
from pandas.core.interchange.dataframe_protocol import Buffer as Buffer, DlpackDeviceType as DlpackDeviceType
from pandas.util.version import Version as Version

class PandasBuffer(Buffer):
    def __init__(self, x: np.ndarray, allow_copy: bool = ...) -> None: ...
    @property
    def bufsize(self) -> int: ...
    @property
    def ptr(self) -> int: ...
    def __dlpack__(self): ...
    def __dlpack_device__(self) -> tuple[DlpackDeviceType, Union[int, None]]: ...
