import pandas as pd
from _typeshed import Incomplete
from collections.abc import Generator
from pandas import Index as Index
from pandas.core.interchange.column import PandasColumn as PandasColumn
from pandas.core.interchange.dataframe_protocol import DataFrame as DataFrameXchg

class PandasDataFrameXchg(DataFrameXchg):
    def __init__(self, df: pd.DataFrame, nan_as_null: bool = ..., allow_copy: bool = ...) -> None: ...
    def __dataframe__(self, nan_as_null: bool = ..., allow_copy: bool = ...) -> PandasDataFrameXchg: ...
    @property
    def metadata(self) -> dict[str, Index]: ...
    def num_columns(self) -> int: ...
    def num_rows(self) -> int: ...
    def num_chunks(self) -> int: ...
    def column_names(self) -> Index: ...
    def get_column(self, i: int) -> PandasColumn: ...
    def get_column_by_name(self, name: str) -> PandasColumn: ...
    def get_columns(self) -> list[PandasColumn]: ...
    def select_columns(self, indices) -> PandasDataFrameXchg: ...
    def select_columns_by_name(self, names) -> PandasDataFrameXchg: ...
    def get_chunks(self, n_chunks: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
