import numpy as np
import pandas as pd
from pandas.core.interchange.column import PandasColumn as PandasColumn
from pandas.core.interchange.dataframe_protocol import Buffer as Buffer, Column as Column, ColumnNullType as ColumnNullType, DataFrame as DataFrameXchg, DtypeKind as DtypeKind
from pandas.core.interchange.utils import ArrowCTypes as ArrowCTypes, Endianness as Endianness
from typing import Any

def from_dataframe(df, allow_copy: bool = ...) -> pd.DataFrame: ...
def protocol_df_chunk_to_pandas(df: DataFrameXchg) -> pd.DataFrame: ...
def primitive_column_to_ndarray(col: Column) -> tuple[np.ndarray, Any]: ...
def categorical_column_to_series(col: Column) -> tuple[pd.Series, Any]: ...
def string_column_to_ndarray(col: Column) -> tuple[np.ndarray, Any]: ...
def parse_datetime_format_str(format_str, data): ...
def datetime_column_to_ndarray(col: Column) -> tuple[np.ndarray, Any]: ...
def buffer_to_ndarray(buffer: Buffer, dtype: tuple[DtypeKind, int, str, str], offset: int = ..., length: Union[int, None] = ...) -> np.ndarray: ...
def bitmask_to_bool_ndarray(bitmask: np.ndarray, mask_length: int, first_byte_offset: int = ...) -> np.ndarray: ...
def set_nulls(data: Union[np.ndarray, pd.Series], col: Column, validity: Union[tuple[Buffer, tuple[DtypeKind, int, str, str]], None], allow_modify_inplace: bool = ...): ...
