from networkx.readwrite.json_graph import node_link_data as node_link_data, node_link_graph as node_link_graph

def test_attrs_deprecation(recwarn) -> None: ...

class TestNodeLink:
    def test_custom_attrs_dep(self) -> None: ...
    def test_exception_dep(self) -> None: ...
    def test_graph(self) -> None: ...
    def test_graph_attributes(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_graph_with_tuple_nodes(self) -> None: ...
    def test_unicode_keys(self) -> None: ...
    def test_exception(self) -> None: ...
    def test_string_ids(self) -> None: ...
    def test_custom_attrs(self) -> None: ...
