from networkx.readwrite.json_graph import cytoscape_data as cytoscape_data, cytoscape_graph as cytoscape_graph

def test_attrs_deprecation(recwarn) -> None: ...
def test_graph() -> None: ...
def test_input_data_is_not_modified_when_building_graph() -> None: ...
def test_graph_attributes() -> None: ...
def test_digraph() -> None: ...
def test_multidigraph() -> None: ...
def test_multigraph() -> None: ...
def test_exception() -> None: ...
