from networkx.readwrite.json_graph import jit_data as jit_data, jit_graph as jit_graph

class TestJIT:
    def test_jit(self) -> None: ...
    def test_jit_2(self) -> None: ...
    def test_jit_directed(self) -> None: ...
    def test_jit_multi_directed(self) -> None: ...
    def test_jit_round_trip(self) -> None: ...
