from networkx.readwrite.json_graph import adjacency_data as adjacency_data, adjacency_graph as adjacency_graph

class TestAdjacency:
    def test_graph(self) -> None: ...
    def test_graph_attributes(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_multidigraph(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_exception(self) -> None: ...
