from networkx.readwrite.json_graph import tree_data as tree_data, tree_graph as tree_graph

def test_graph() -> None: ...
def test_graph_attributes() -> None: ...
def test_exceptions() -> None: ...
def test_attrs_deprecation(recwarn) -> None: ...
