from _typeshed import Incomplete

def categorical_node_match(attr, default): ...

categorical_edge_match: Incomplete

def categorical_multiedge_match(attr, default): ...
def numerical_node_match(attr, default, rtol: float = ..., atol: float = ...): ...

numerical_edge_match: Incomplete

def numerical_multiedge_match(attr, default, rtol: float = ..., atol: float = ...): ...
def generic_node_match(attr, default, op): ...

generic_edge_match: Incomplete

def generic_multiedge_match(attr, default, op): ...
