version: 2
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - wget https://github.com/jgm/pandoc/releases/download/3.1.5/pandoc-3.1.5-linux-amd64.tar.gz
      - mkdir /home/docs/pandoc
      - tar -xvzf pandoc-3.1.5-linux-amd64.tar.gz --strip-components 1 -C /home/docs/pandoc
      - echo $(which pandoc)
      - echo $(whereis pandoc)
sphinx:
  fail_on_warning: false
  configuration: docs/conf.py
  
formats:
  - pdf