version: 2
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
  
formats:
  - pdf
  - epub