version: 2
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - bash pre_install.sh
      - echo $(which pandoc)
      - echo $(whereis pandoc)
sphinx:
  fail_on_warning: true
  configuration: docs/conf.py
  
formats:
  - pdf