from _typeshed import Incomplete

def to_networkx_graph(data, create_using: Incomplete | None = ..., multigraph_input: bool = ...): ...
def to_dict_of_lists(G, nodelist: Incomplete | None = ...): ...
def from_dict_of_lists(d, create_using: Incomplete | None = ...): ...
def to_dict_of_dicts(G, nodelist: Incomplete | None = ..., edge_data: Incomplete | None = ...): ...
def from_dict_of_dicts(d, create_using: Incomplete | None = ..., multigraph_input: bool = ...): ...
def to_edgelist(G, nodelist: Incomplete | None = ...): ...
def from_edgelist(edgelist, create_using: Incomplete | None = ...): ...
