from _typeshed import Incomplete

def relabel_nodes(G, mapping, copy: bool = ...): ...
def convert_node_labels_to_integers(G, first_label: int = ..., ordering: str = ..., label_attribute: Incomplete | None = ...): ...
