from _typeshed import Incomplete

def full_rary_tree(r, n, create_using: Incomplete | None = ...): ...
def balanced_tree(r, h, create_using: Incomplete | None = ...): ...
def barbell_graph(m1, m2, create_using: Incomplete | None = ...): ...
def binomial_tree(n, create_using: Incomplete | None = ...): ...
def complete_graph(n, create_using: Incomplete | None = ...): ...
def circular_ladder_graph(n, create_using: Incomplete | None = ...): ...
def circulant_graph(n, offsets, create_using: Incomplete | None = ...): ...
def cycle_graph(n, create_using: Incomplete | None = ...): ...
def dorogovtsev_goltsev_mendes_graph(n, create_using: Incomplete | None = ...): ...
def empty_graph(n: int = ..., create_using: Incomplete | None = ..., default=...): ...
def ladder_graph(n, create_using: Incomplete | None = ...): ...
def lollipop_graph(m, n, create_using: Incomplete | None = ...): ...
def null_graph(create_using: Incomplete | None = ...): ...
def path_graph(n, create_using: Incomplete | None = ...): ...
def star_graph(n, create_using: Incomplete | None = ...): ...
def trivial_graph(create_using: Incomplete | None = ...): ...
def turan_graph(n, r): ...
def wheel_graph(n, create_using: Incomplete | None = ...): ...
def complete_multipartite_graph(*subset_sizes): ...
