from _typeshed import Incomplete

def make_small_graph(graph_description, create_using: Incomplete | None = ...): ...
def LCF_graph(n, shift_list, repeats, create_using: Incomplete | None = ...): ...
def bull_graph(create_using: Incomplete | None = ...): ...
def chvatal_graph(create_using: Incomplete | None = ...): ...
def cubical_graph(create_using: Incomplete | None = ...): ...
def desargues_graph(create_using: Incomplete | None = ...): ...
def diamond_graph(create_using: Incomplete | None = ...): ...
def dodecahedral_graph(create_using: Incomplete | None = ...): ...
def frucht_graph(create_using: Incomplete | None = ...): ...
def heawood_graph(create_using: Incomplete | None = ...): ...
def hoffman_singleton_graph(): ...
def house_graph(create_using: Incomplete | None = ...): ...
def house_x_graph(create_using: Incomplete | None = ...): ...
def icosahedral_graph(create_using: Incomplete | None = ...): ...
def krackhardt_kite_graph(create_using: Incomplete | None = ...): ...
def moebius_kantor_graph(create_using: Incomplete | None = ...): ...
def octahedral_graph(create_using: Incomplete | None = ...): ...
def pappus_graph(): ...
def petersen_graph(create_using: Incomplete | None = ...): ...
def sedgewick_maze_graph(create_using: Incomplete | None = ...): ...
def tetrahedral_graph(create_using: Incomplete | None = ...): ...
def truncated_cube_graph(create_using: Incomplete | None = ...): ...
def truncated_tetrahedron_graph(create_using: Incomplete | None = ...): ...
def tutte_graph(create_using: Incomplete | None = ...): ...
