import enum

class GeoKeys(enum.IntEnum):
    GTModelTypeGeoKey: int
    GTRasterTypeGeoKey: int
    GTCitationGeoKey: int
    GeographicTypeGeoKey: int
    GeogCitationGeoKey: int
    GeogGeodeticDatumGeoKey: int
    GeogPrimeMeridianGeoKey: int
    GeogLinearUnitsGeoKey: int
    GeogLinearUnitSizeGeoKey: int
    GeogAngularUnitsGeoKey: int
    GeogAngularUnitsSizeGeoKey: int
    GeogEllipsoidGeoKey: int
    GeogSemiMajorAxisGeoKey: int
    GeogSemiMinorAxisGeoKey: int
    GeogInvFlatteningGeoKey: int
    GeogAzimuthUnitsGeoKey: int
    GeogPrimeMeridianLongGeoKey: int
    GeogTOWGS84GeoKey: int
    ProjLinearUnitsInterpCorrectGeoKey: int
    ProjectedCSTypeGeoKey: int
    PCSCitationGeoKey: int
    ProjectionGeoKey: int
    ProjCoordTransGeoKey: int
    ProjLinearUnitsGeoKey: int
    ProjLinearUnitSizeGeoKey: int
    ProjStdParallel1GeoKey: int
    ProjStdParallel2GeoKey: int
    ProjNatOriginLongGeoKey: int
    ProjNatOriginLatGeoKey: int
    ProjFalseEastingGeoKey: int
    ProjFalseNorthingGeoKey: int
    ProjFalseOriginLongGeoKey: int
    ProjFalseOriginLatGeoKey: int
    ProjFalseOriginEastingGeoKey: int
    ProjFalseOriginNorthingGeoKey: int
    ProjCenterLongGeoKey: int
    ProjCenterLatGeoKey: int
    ProjCenterEastingGeoKey: int
    ProjCenterNorthingGeoKey: int
    ProjScaleAtNatOriginGeoKey: int
    ProjScaleAtCenterGeoKey: int
    ProjAzimuthAngleGeoKey: int
    ProjStraightVertPoleLongGeoKey: int
    ProjRectifiedGridAngleGeoKey: int
    VerticalCSTypeGeoKey: int
    VerticalCitationGeoKey: int
    VerticalDatumGeoKey: int
    VerticalUnitsGeoKey: int

class Proj(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Alabama_CS27_East: int
    Alabama_CS27_West: int
    Alabama_CS83_East: int
    Alabama_CS83_West: int
    Arizona_Coordinate_System_east: int
    Arizona_Coordinate_System_Central: int
    Arizona_Coordinate_System_west: int
    Arizona_CS83_east: int
    Arizona_CS83_Central: int
    Arizona_CS83_west: int
    Arkansas_CS27_North: int
    Arkansas_CS27_South: int
    Arkansas_CS83_North: int
    Arkansas_CS83_South: int
    California_CS27_I: int
    California_CS27_II: int
    California_CS27_III: int
    California_CS27_IV: int
    California_CS27_V: int
    California_CS27_VI: int
    California_CS27_VII: int
    California_CS83_1: int
    California_CS83_2: int
    California_CS83_3: int
    California_CS83_4: int
    California_CS83_5: int
    California_CS83_6: int
    Colorado_CS27_North: int
    Colorado_CS27_Central: int
    Colorado_CS27_South: int
    Colorado_CS83_North: int
    Colorado_CS83_Central: int
    Colorado_CS83_South: int
    Connecticut_CS27: int
    Connecticut_CS83: int
    Delaware_CS27: int
    Delaware_CS83: int
    Florida_CS27_East: int
    Florida_CS27_West: int
    Florida_CS27_North: int
    Florida_CS83_East: int
    Florida_CS83_West: int
    Florida_CS83_North: int
    Georgia_CS27_East: int
    Georgia_CS27_West: int
    Georgia_CS83_East: int
    Georgia_CS83_West: int
    Idaho_CS27_East: int
    Idaho_CS27_Central: int
    Idaho_CS27_West: int
    Idaho_CS83_East: int
    Idaho_CS83_Central: int
    Idaho_CS83_West: int
    Illinois_CS27_East: int
    Illinois_CS27_West: int
    Illinois_CS83_East: int
    Illinois_CS83_West: int
    Indiana_CS27_East: int
    Indiana_CS27_West: int
    Indiana_CS83_East: int
    Indiana_CS83_West: int
    Iowa_CS27_North: int
    Iowa_CS27_South: int
    Iowa_CS83_North: int
    Iowa_CS83_South: int
    Kansas_CS27_North: int
    Kansas_CS27_South: int
    Kansas_CS83_North: int
    Kansas_CS83_South: int
    Kentucky_CS27_North: int
    Kentucky_CS27_South: int
    Kentucky_CS83_North: int
    Kentucky_CS83_South: int
    Louisiana_CS27_North: int
    Louisiana_CS27_South: int
    Louisiana_CS83_North: int
    Louisiana_CS83_South: int
    Maine_CS27_East: int
    Maine_CS27_West: int
    Maine_CS83_East: int
    Maine_CS83_West: int
    Maryland_CS27: int
    Maryland_CS83: int
    Massachusetts_CS27_Mainland: int
    Massachusetts_CS27_Island: int
    Massachusetts_CS83_Mainland: int
    Massachusetts_CS83_Island: int
    Michigan_State_Plane_East: int
    Michigan_State_Plane_Old_Central: int
    Michigan_State_Plane_West: int
    Michigan_CS27_North: int
    Michigan_CS27_Central: int
    Michigan_CS27_South: int
    Michigan_CS83_North: int
    Michigan_CS83_Central: int
    Michigan_CS83_South: int
    Minnesota_CS27_North: int
    Minnesota_CS27_Central: int
    Minnesota_CS27_South: int
    Minnesota_CS83_North: int
    Minnesota_CS83_Central: int
    Minnesota_CS83_South: int
    Mississippi_CS27_East: int
    Mississippi_CS27_West: int
    Mississippi_CS83_East: int
    Mississippi_CS83_West: int
    Missouri_CS27_East: int
    Missouri_CS27_Central: int
    Missouri_CS27_West: int
    Missouri_CS83_East: int
    Missouri_CS83_Central: int
    Missouri_CS83_West: int
    Montana_CS27_North: int
    Montana_CS27_Central: int
    Montana_CS27_South: int
    Montana_CS83: int
    Nebraska_CS27_North: int
    Nebraska_CS27_South: int
    Nebraska_CS83: int
    Nevada_CS27_East: int
    Nevada_CS27_Central: int
    Nevada_CS27_West: int
    Nevada_CS83_East: int
    Nevada_CS83_Central: int
    Nevada_CS83_West: int
    New_Hampshire_CS27: int
    New_Hampshire_CS83: int
    New_Jersey_CS27: int
    New_Jersey_CS83: int
    New_Mexico_CS27_East: int
    New_Mexico_CS27_Central: int
    New_Mexico_CS27_West: int
    New_Mexico_CS83_East: int
    New_Mexico_CS83_Central: int
    New_Mexico_CS83_West: int
    New_York_CS27_East: int
    New_York_CS27_Central: int
    New_York_CS27_West: int
    New_York_CS27_Long_Island: int
    New_York_CS83_East: int
    New_York_CS83_Central: int
    New_York_CS83_West: int
    New_York_CS83_Long_Island: int
    North_Carolina_CS27: int
    North_Carolina_CS83: int
    North_Dakota_CS27_North: int
    North_Dakota_CS27_South: int
    North_Dakota_CS83_North: int
    North_Dakota_CS83_South: int
    Ohio_CS27_North: int
    Ohio_CS27_South: int
    Ohio_CS83_North: int
    Ohio_CS83_South: int
    Oklahoma_CS27_North: int
    Oklahoma_CS27_South: int
    Oklahoma_CS83_North: int
    Oklahoma_CS83_South: int
    Oregon_CS27_North: int
    Oregon_CS27_South: int
    Oregon_CS83_North: int
    Oregon_CS83_South: int
    Pennsylvania_CS27_North: int
    Pennsylvania_CS27_South: int
    Pennsylvania_CS83_North: int
    Pennsylvania_CS83_South: int
    Rhode_Island_CS27: int
    Rhode_Island_CS83: int
    South_Carolina_CS27_North: int
    South_Carolina_CS27_South: int
    South_Carolina_CS83: int
    South_Dakota_CS27_North: int
    South_Dakota_CS27_South: int
    South_Dakota_CS83_North: int
    South_Dakota_CS83_South: int
    Tennessee_CS27: int
    Tennessee_CS83: int
    Texas_CS27_North: int
    Texas_CS27_North_Central: int
    Texas_CS27_Central: int
    Texas_CS27_South_Central: int
    Texas_CS27_South: int
    Texas_CS83_North: int
    Texas_CS83_North_Central: int
    Texas_CS83_Central: int
    Texas_CS83_South_Central: int
    Texas_CS83_South: int
    Utah_CS27_North: int
    Utah_CS27_Central: int
    Utah_CS27_South: int
    Utah_CS83_North: int
    Utah_CS83_Central: int
    Utah_CS83_South: int
    Vermont_CS27: int
    Vermont_CS83: int
    Virginia_CS27_North: int
    Virginia_CS27_South: int
    Virginia_CS83_North: int
    Virginia_CS83_South: int
    Washington_CS27_North: int
    Washington_CS27_South: int
    Washington_CS83_North: int
    Washington_CS83_South: int
    West_Virginia_CS27_North: int
    West_Virginia_CS27_South: int
    West_Virginia_CS83_North: int
    West_Virginia_CS83_South: int
    Wisconsin_CS27_North: int
    Wisconsin_CS27_Central: int
    Wisconsin_CS27_South: int
    Wisconsin_CS83_North: int
    Wisconsin_CS83_Central: int
    Wisconsin_CS83_South: int
    Wyoming_CS27_East: int
    Wyoming_CS27_East_Central: int
    Wyoming_CS27_West_Central: int
    Wyoming_CS27_West: int
    Wyoming_CS83_East: int
    Wyoming_CS83_East_Central: int
    Wyoming_CS83_West_Central: int
    Wyoming_CS83_West: int
    Alaska_CS27_1: int
    Alaska_CS27_2: int
    Alaska_CS27_3: int
    Alaska_CS27_4: int
    Alaska_CS27_5: int
    Alaska_CS27_6: int
    Alaska_CS27_7: int
    Alaska_CS27_8: int
    Alaska_CS27_9: int
    Alaska_CS27_10: int
    Alaska_CS83_1: int
    Alaska_CS83_2: int
    Alaska_CS83_3: int
    Alaska_CS83_4: int
    Alaska_CS83_5: int
    Alaska_CS83_6: int
    Alaska_CS83_7: int
    Alaska_CS83_8: int
    Alaska_CS83_9: int
    Alaska_CS83_10: int
    Hawaii_CS27_1: int
    Hawaii_CS27_2: int
    Hawaii_CS27_3: int
    Hawaii_CS27_4: int
    Hawaii_CS27_5: int
    Hawaii_CS83_1: int
    Hawaii_CS83_2: int
    Hawaii_CS83_3: int
    Hawaii_CS83_4: int
    Hawaii_CS83_5: int
    Puerto_Rico_CS27: int
    St_Croix: int
    Puerto_Rico_Virgin_Is: int
    BLM_14N_feet: int
    BLM_15N_feet: int
    BLM_16N_feet: int
    BLM_17N_feet: int
    UTM_zone_1N: int
    UTM_zone_2N: int
    UTM_zone_3N: int
    UTM_zone_4N: int
    UTM_zone_5N: int
    UTM_zone_6N: int
    UTM_zone_7N: int
    UTM_zone_8N: int
    UTM_zone_9N: int
    UTM_zone_10N: int
    UTM_zone_11N: int
    UTM_zone_12N: int
    UTM_zone_13N: int
    UTM_zone_14N: int
    UTM_zone_15N: int
    UTM_zone_16N: int
    UTM_zone_17N: int
    UTM_zone_18N: int
    UTM_zone_19N: int
    UTM_zone_20N: int
    UTM_zone_21N: int
    UTM_zone_22N: int
    UTM_zone_23N: int
    UTM_zone_24N: int
    UTM_zone_25N: int
    UTM_zone_26N: int
    UTM_zone_27N: int
    UTM_zone_28N: int
    UTM_zone_29N: int
    UTM_zone_30N: int
    UTM_zone_31N: int
    UTM_zone_32N: int
    UTM_zone_33N: int
    UTM_zone_34N: int
    UTM_zone_35N: int
    UTM_zone_36N: int
    UTM_zone_37N: int
    UTM_zone_38N: int
    UTM_zone_39N: int
    UTM_zone_40N: int
    UTM_zone_41N: int
    UTM_zone_42N: int
    UTM_zone_43N: int
    UTM_zone_44N: int
    UTM_zone_45N: int
    UTM_zone_46N: int
    UTM_zone_47N: int
    UTM_zone_48N: int
    UTM_zone_49N: int
    UTM_zone_50N: int
    UTM_zone_51N: int
    UTM_zone_52N: int
    UTM_zone_53N: int
    UTM_zone_54N: int
    UTM_zone_55N: int
    UTM_zone_56N: int
    UTM_zone_57N: int
    UTM_zone_58N: int
    UTM_zone_59N: int
    UTM_zone_60N: int
    UTM_zone_1S: int
    UTM_zone_2S: int
    UTM_zone_3S: int
    UTM_zone_4S: int
    UTM_zone_5S: int
    UTM_zone_6S: int
    UTM_zone_7S: int
    UTM_zone_8S: int
    UTM_zone_9S: int
    UTM_zone_10S: int
    UTM_zone_11S: int
    UTM_zone_12S: int
    UTM_zone_13S: int
    UTM_zone_14S: int
    UTM_zone_15S: int
    UTM_zone_16S: int
    UTM_zone_17S: int
    UTM_zone_18S: int
    UTM_zone_19S: int
    UTM_zone_20S: int
    UTM_zone_21S: int
    UTM_zone_22S: int
    UTM_zone_23S: int
    UTM_zone_24S: int
    UTM_zone_25S: int
    UTM_zone_26S: int
    UTM_zone_27S: int
    UTM_zone_28S: int
    UTM_zone_29S: int
    UTM_zone_30S: int
    UTM_zone_31S: int
    UTM_zone_32S: int
    UTM_zone_33S: int
    UTM_zone_34S: int
    UTM_zone_35S: int
    UTM_zone_36S: int
    UTM_zone_37S: int
    UTM_zone_38S: int
    UTM_zone_39S: int
    UTM_zone_40S: int
    UTM_zone_41S: int
    UTM_zone_42S: int
    UTM_zone_43S: int
    UTM_zone_44S: int
    UTM_zone_45S: int
    UTM_zone_46S: int
    UTM_zone_47S: int
    UTM_zone_48S: int
    UTM_zone_49S: int
    UTM_zone_50S: int
    UTM_zone_51S: int
    UTM_zone_52S: int
    UTM_zone_53S: int
    UTM_zone_54S: int
    UTM_zone_55S: int
    UTM_zone_56S: int
    UTM_zone_57S: int
    UTM_zone_58S: int
    UTM_zone_59S: int
    UTM_zone_60S: int
    Gauss_Kruger_zone_0: int
    Gauss_Kruger_zone_1: int
    Gauss_Kruger_zone_2: int
    Gauss_Kruger_zone_3: int
    Gauss_Kruger_zone_4: int
    Gauss_Kruger_zone_5: int
    Map_Grid_of_Australia_48: int
    Map_Grid_of_Australia_49: int
    Map_Grid_of_Australia_50: int
    Map_Grid_of_Australia_51: int
    Map_Grid_of_Australia_52: int
    Map_Grid_of_Australia_53: int
    Map_Grid_of_Australia_54: int
    Map_Grid_of_Australia_55: int
    Map_Grid_of_Australia_56: int
    Map_Grid_of_Australia_57: int
    Map_Grid_of_Australia_58: int
    Australian_Map_Grid_48: int
    Australian_Map_Grid_49: int
    Australian_Map_Grid_50: int
    Australian_Map_Grid_51: int
    Australian_Map_Grid_52: int
    Australian_Map_Grid_53: int
    Australian_Map_Grid_54: int
    Australian_Map_Grid_55: int
    Australian_Map_Grid_56: int
    Australian_Map_Grid_57: int
    Australian_Map_Grid_58: int
    Argentina_1: int
    Argentina_2: int
    Argentina_3: int
    Argentina_4: int
    Argentina_5: int
    Argentina_6: int
    Argentina_7: int
    Colombia_3W: int
    Colombia_Bogota: int
    Colombia_3E: int
    Colombia_6E: int
    Egypt_Red_Belt: int
    Egypt_Purple_Belt: int
    Extended_Purple_Belt: int
    New_Zealand_North_Island_Nat_Grid: int
    New_Zealand_South_Island_Nat_Grid: int
    Bahrain_Grid: int
    Netherlands_E_Indies_Equatorial: int
    RSO_Borneo: int
    Stereo_70: int

class PCS(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Adindan_UTM_zone_37N: int
    Adindan_UTM_zone_38N: int
    AGD66_AMG_zone_48: int
    AGD66_AMG_zone_49: int
    AGD66_AMG_zone_50: int
    AGD66_AMG_zone_51: int
    AGD66_AMG_zone_52: int
    AGD66_AMG_zone_53: int
    AGD66_AMG_zone_54: int
    AGD66_AMG_zone_55: int
    AGD66_AMG_zone_56: int
    AGD66_AMG_zone_57: int
    AGD66_AMG_zone_58: int
    AGD84_AMG_zone_48: int
    AGD84_AMG_zone_49: int
    AGD84_AMG_zone_50: int
    AGD84_AMG_zone_51: int
    AGD84_AMG_zone_52: int
    AGD84_AMG_zone_53: int
    AGD84_AMG_zone_54: int
    AGD84_AMG_zone_55: int
    AGD84_AMG_zone_56: int
    AGD84_AMG_zone_57: int
    AGD84_AMG_zone_58: int
    Ain_el_Abd_UTM_zone_37N: int
    Ain_el_Abd_UTM_zone_38N: int
    Ain_el_Abd_UTM_zone_39N: int
    Ain_el_Abd_Bahrain_Grid: int
    Afgooye_UTM_zone_38N: int
    Afgooye_UTM_zone_39N: int
    Lisbon_Portugese_Grid: int
    Aratu_UTM_zone_22S: int
    Aratu_UTM_zone_23S: int
    Aratu_UTM_zone_24S: int
    Arc_1950_Lo13: int
    Arc_1950_Lo15: int
    Arc_1950_Lo17: int
    Arc_1950_Lo19: int
    Arc_1950_Lo21: int
    Arc_1950_Lo23: int
    Arc_1950_Lo25: int
    Arc_1950_Lo27: int
    Arc_1950_Lo29: int
    Arc_1950_Lo31: int
    Arc_1950_Lo33: int
    Arc_1950_Lo35: int
    Batavia_NEIEZ: int
    Batavia_UTM_zone_48S: int
    Batavia_UTM_zone_49S: int
    Batavia_UTM_zone_50S: int
    Beijing_Gauss_zone_13: int
    Beijing_Gauss_zone_14: int
    Beijing_Gauss_zone_15: int
    Beijing_Gauss_zone_16: int
    Beijing_Gauss_zone_17: int
    Beijing_Gauss_zone_18: int
    Beijing_Gauss_zone_19: int
    Beijing_Gauss_zone_20: int
    Beijing_Gauss_zone_21: int
    Beijing_Gauss_zone_22: int
    Beijing_Gauss_zone_23: int
    Beijing_Gauss_13N: int
    Beijing_Gauss_14N: int
    Beijing_Gauss_15N: int
    Beijing_Gauss_16N: int
    Beijing_Gauss_17N: int
    Beijing_Gauss_18N: int
    Beijing_Gauss_19N: int
    Beijing_Gauss_20N: int
    Beijing_Gauss_21N: int
    Beijing_Gauss_22N: int
    Beijing_Gauss_23N: int
    Belge_Lambert_50: int
    Bern_1898_Swiss_Old: int
    Bogota_UTM_zone_17N: int
    Bogota_UTM_zone_18N: int
    Bogota_Colombia_3W: int
    Bogota_Colombia_Bogota: int
    Bogota_Colombia_3E: int
    Bogota_Colombia_6E: int
    Camacupa_UTM_32S: int
    Camacupa_UTM_33S: int
    C_Inchauspe_Argentina_1: int
    C_Inchauspe_Argentina_2: int
    C_Inchauspe_Argentina_3: int
    C_Inchauspe_Argentina_4: int
    C_Inchauspe_Argentina_5: int
    C_Inchauspe_Argentina_6: int
    C_Inchauspe_Argentina_7: int
    Carthage_UTM_zone_32N: int
    Carthage_Nord_Tunisie: int
    Carthage_Sud_Tunisie: int
    Corrego_Alegre_UTM_23S: int
    Corrego_Alegre_UTM_24S: int
    Douala_UTM_zone_32N: int
    Egypt_1907_Red_Belt: int
    Egypt_1907_Purple_Belt: int
    Egypt_1907_Ext_Purple: int
    ED50_UTM_zone_28N: int
    ED50_UTM_zone_29N: int
    ED50_UTM_zone_30N: int
    ED50_UTM_zone_31N: int
    ED50_UTM_zone_32N: int
    ED50_UTM_zone_33N: int
    ED50_UTM_zone_34N: int
    ED50_UTM_zone_35N: int
    ED50_UTM_zone_36N: int
    ED50_UTM_zone_37N: int
    ED50_UTM_zone_38N: int
    Fahud_UTM_zone_39N: int
    Fahud_UTM_zone_40N: int
    Garoua_UTM_zone_33N: int
    ID74_UTM_zone_46N: int
    ID74_UTM_zone_47N: int
    ID74_UTM_zone_48N: int
    ID74_UTM_zone_49N: int
    ID74_UTM_zone_50N: int
    ID74_UTM_zone_51N: int
    ID74_UTM_zone_52N: int
    ID74_UTM_zone_53N: int
    ID74_UTM_zone_46S: int
    ID74_UTM_zone_47S: int
    ID74_UTM_zone_48S: int
    ID74_UTM_zone_49S: int
    ID74_UTM_zone_50S: int
    ID74_UTM_zone_51S: int
    ID74_UTM_zone_52S: int
    ID74_UTM_zone_53S: int
    ID74_UTM_zone_54S: int
    Indian_1954_UTM_47N: int
    Indian_1954_UTM_48N: int
    Indian_1975_UTM_47N: int
    Indian_1975_UTM_48N: int
    Jamaica_1875_Old_Grid: int
    JAD69_Jamaica_Grid: int
    Kalianpur_India_0: int
    Kalianpur_India_I: int
    Kalianpur_India_IIa: int
    Kalianpur_India_IIIa: int
    Kalianpur_India_IVa: int
    Kalianpur_India_IIb: int
    Kalianpur_India_IIIb: int
    Kalianpur_India_IVb: int
    Kertau_Singapore_Grid: int
    Kertau_UTM_zone_47N: int
    Kertau_UTM_zone_48N: int
    La_Canoa_UTM_zone_20N: int
    La_Canoa_UTM_zone_21N: int
    PSAD56_UTM_zone_18N: int
    PSAD56_UTM_zone_19N: int
    PSAD56_UTM_zone_20N: int
    PSAD56_UTM_zone_21N: int
    PSAD56_UTM_zone_17S: int
    PSAD56_UTM_zone_18S: int
    PSAD56_UTM_zone_19S: int
    PSAD56_UTM_zone_20S: int
    PSAD56_Peru_west_zone: int
    PSAD56_Peru_central: int
    PSAD56_Peru_east_zone: int
    Leigon_Ghana_Grid: int
    Lome_UTM_zone_31N: int
    Luzon_Philippines_I: int
    Luzon_Philippines_II: int
    Luzon_Philippines_III: int
    Luzon_Philippines_IV: int
    Luzon_Philippines_V: int
    Makassar_NEIEZ: int
    Malongo_1987_UTM_32S: int
    Merchich_Nord_Maroc: int
    Merchich_Sud_Maroc: int
    Merchich_Sahara: int
    Massawa_UTM_zone_37N: int
    Minna_UTM_zone_31N: int
    Minna_UTM_zone_32N: int
    Minna_Nigeria_West: int
    Minna_Nigeria_Mid_Belt: int
    Minna_Nigeria_East: int
    Mhast_UTM_zone_32S: int
    Monte_Mario_Italy_1: int
    Monte_Mario_Italy_2: int
    M_poraloko_UTM_32N: int
    M_poraloko_UTM_32S: int
    NAD27_UTM_zone_3N: int
    NAD27_UTM_zone_4N: int
    NAD27_UTM_zone_5N: int
    NAD27_UTM_zone_6N: int
    NAD27_UTM_zone_7N: int
    NAD27_UTM_zone_8N: int
    NAD27_UTM_zone_9N: int
    NAD27_UTM_zone_10N: int
    NAD27_UTM_zone_11N: int
    NAD27_UTM_zone_12N: int
    NAD27_UTM_zone_13N: int
    NAD27_UTM_zone_14N: int
    NAD27_UTM_zone_15N: int
    NAD27_UTM_zone_16N: int
    NAD27_UTM_zone_17N: int
    NAD27_UTM_zone_18N: int
    NAD27_UTM_zone_19N: int
    NAD27_UTM_zone_20N: int
    NAD27_UTM_zone_21N: int
    NAD27_UTM_zone_22N: int
    NAD27_Alabama_East: int
    NAD27_Alabama_West: int
    NAD27_Alaska_zone_1: int
    NAD27_Alaska_zone_2: int
    NAD27_Alaska_zone_3: int
    NAD27_Alaska_zone_4: int
    NAD27_Alaska_zone_5: int
    NAD27_Alaska_zone_6: int
    NAD27_Alaska_zone_7: int
    NAD27_Alaska_zone_8: int
    NAD27_Alaska_zone_9: int
    NAD27_Alaska_zone_10: int
    NAD27_California_I: int
    NAD27_California_II: int
    NAD27_California_III: int
    NAD27_California_IV: int
    NAD27_California_V: int
    NAD27_California_VI: int
    NAD27_California_VII: int
    NAD27_Arizona_East: int
    NAD27_Arizona_Central: int
    NAD27_Arizona_West: int
    NAD27_Arkansas_North: int
    NAD27_Arkansas_South: int
    NAD27_Colorado_North: int
    NAD27_Colorado_Central: int
    NAD27_Colorado_South: int
    NAD27_Connecticut: int
    NAD27_Delaware: int
    NAD27_Florida_East: int
    NAD27_Florida_West: int
    NAD27_Florida_North: int
    NAD27_Hawaii_zone_1: int
    NAD27_Hawaii_zone_2: int
    NAD27_Hawaii_zone_3: int
    NAD27_Hawaii_zone_4: int
    NAD27_Hawaii_zone_5: int
    NAD27_Georgia_East: int
    NAD27_Georgia_West: int
    NAD27_Idaho_East: int
    NAD27_Idaho_Central: int
    NAD27_Idaho_West: int
    NAD27_Illinois_East: int
    NAD27_Illinois_West: int
    NAD27_Indiana_East: int
    NAD27_BLM_14N_feet: int
    NAD27_Indiana_West: int
    NAD27_BLM_15N_feet: int
    NAD27_Iowa_North: int
    NAD27_BLM_16N_feet: int
    NAD27_Iowa_South: int
    NAD27_BLM_17N_feet: int
    NAD27_Kansas_North: int
    NAD27_Kansas_South: int
    NAD27_Kentucky_North: int
    NAD27_Kentucky_South: int
    NAD27_Louisiana_North: int
    NAD27_Louisiana_South: int
    NAD27_Maine_East: int
    NAD27_Maine_West: int
    NAD27_Maryland: int
    NAD27_Massachusetts: int
    NAD27_Massachusetts_Is: int
    NAD27_Michigan_North: int
    NAD27_Michigan_Central: int
    NAD27_Michigan_South: int
    NAD27_Minnesota_North: int
    NAD27_Minnesota_Cent: int
    NAD27_Minnesota_South: int
    NAD27_Mississippi_East: int
    NAD27_Mississippi_West: int
    NAD27_Missouri_East: int
    NAD27_Missouri_Central: int
    NAD27_Missouri_West: int
    NAD_Michigan_Michigan_East: int
    NAD_Michigan_Michigan_Old_Central: int
    NAD_Michigan_Michigan_West: int
    NAD83_UTM_zone_3N: int
    NAD83_UTM_zone_4N: int
    NAD83_UTM_zone_5N: int
    NAD83_UTM_zone_6N: int
    NAD83_UTM_zone_7N: int
    NAD83_UTM_zone_8N: int
    NAD83_UTM_zone_9N: int
    NAD83_UTM_zone_10N: int
    NAD83_UTM_zone_11N: int
    NAD83_UTM_zone_12N: int
    NAD83_UTM_zone_13N: int
    NAD83_UTM_zone_14N: int
    NAD83_UTM_zone_15N: int
    NAD83_UTM_zone_16N: int
    NAD83_UTM_zone_17N: int
    NAD83_UTM_zone_18N: int
    NAD83_UTM_zone_19N: int
    NAD83_UTM_zone_20N: int
    NAD83_UTM_zone_21N: int
    NAD83_UTM_zone_22N: int
    NAD83_UTM_zone_23N: int
    NAD83_Alabama_East: int
    NAD83_Alabama_West: int
    NAD83_Alaska_zone_1: int
    NAD83_Alaska_zone_2: int
    NAD83_Alaska_zone_3: int
    NAD83_Alaska_zone_4: int
    NAD83_Alaska_zone_5: int
    NAD83_Alaska_zone_6: int
    NAD83_Alaska_zone_7: int
    NAD83_Alaska_zone_8: int
    NAD83_Alaska_zone_9: int
    NAD83_Alaska_zone_10: int
    NAD83_California_1: int
    NAD83_California_2: int
    NAD83_California_3: int
    NAD83_California_4: int
    NAD83_California_5: int
    NAD83_California_6: int
    NAD83_Arizona_East: int
    NAD83_Arizona_Central: int
    NAD83_Arizona_West: int
    NAD83_Arkansas_North: int
    NAD83_Arkansas_South: int
    NAD83_Colorado_North: int
    NAD83_Colorado_Central: int
    NAD83_Colorado_South: int
    NAD83_Connecticut: int
    NAD83_Delaware: int
    NAD83_Florida_East: int
    NAD83_Florida_West: int
    NAD83_Florida_North: int
    NAD83_Hawaii_zone_1: int
    NAD83_Hawaii_zone_2: int
    NAD83_Hawaii_zone_3: int
    NAD83_Hawaii_zone_4: int
    NAD83_Hawaii_zone_5: int
    NAD83_Georgia_East: int
    NAD83_Georgia_West: int
    NAD83_Idaho_East: int
    NAD83_Idaho_Central: int
    NAD83_Idaho_West: int
    NAD83_Illinois_East: int
    NAD83_Illinois_West: int
    NAD83_Indiana_East: int
    NAD83_Indiana_West: int
    NAD83_Iowa_North: int
    NAD83_Iowa_South: int
    NAD83_Kansas_North: int
    NAD83_Kansas_South: int
    NAD83_Kentucky_North: int
    NAD83_Kentucky_South: int
    NAD83_Louisiana_North: int
    NAD83_Louisiana_South: int
    NAD83_Maine_East: int
    NAD83_Maine_West: int
    NAD83_Maryland: int
    NAD83_Massachusetts: int
    NAD83_Massachusetts_Is: int
    NAD83_Michigan_North: int
    NAD83_Michigan_Central: int
    NAD83_Michigan_South: int
    NAD83_Minnesota_North: int
    NAD83_Minnesota_Cent: int
    NAD83_Minnesota_South: int
    NAD83_Mississippi_East: int
    NAD83_Mississippi_West: int
    NAD83_Missouri_East: int
    NAD83_Missouri_Central: int
    NAD83_Missouri_West: int
    Nahrwan_1967_UTM_38N: int
    Nahrwan_1967_UTM_39N: int
    Nahrwan_1967_UTM_40N: int
    Naparima_UTM_20N: int
    GD49_NZ_Map_Grid: int
    GD49_North_Island_Grid: int
    GD49_South_Island_Grid: int
    Datum_73_UTM_zone_29N: int
    ATF_Nord_de_Guerre: int
    NTF_France_I: int
    NTF_France_II: int
    NTF_France_III: int
    NTF_Nord_France: int
    NTF_Centre_France: int
    NTF_Sud_France: int
    British_National_Grid: int
    Point_Noire_UTM_32S: int
    GDA94_MGA_zone_48: int
    GDA94_MGA_zone_49: int
    GDA94_MGA_zone_50: int
    GDA94_MGA_zone_51: int
    GDA94_MGA_zone_52: int
    GDA94_MGA_zone_53: int
    GDA94_MGA_zone_54: int
    GDA94_MGA_zone_55: int
    GDA94_MGA_zone_56: int
    GDA94_MGA_zone_57: int
    GDA94_MGA_zone_58: int
    Pulkovo_Gauss_zone_4: int
    Pulkovo_Gauss_zone_5: int
    Pulkovo_Gauss_zone_6: int
    Pulkovo_Gauss_zone_7: int
    Pulkovo_Gauss_zone_8: int
    Pulkovo_Gauss_zone_9: int
    Pulkovo_Gauss_zone_10: int
    Pulkovo_Gauss_zone_11: int
    Pulkovo_Gauss_zone_12: int
    Pulkovo_Gauss_zone_13: int
    Pulkovo_Gauss_zone_14: int
    Pulkovo_Gauss_zone_15: int
    Pulkovo_Gauss_zone_16: int
    Pulkovo_Gauss_zone_17: int
    Pulkovo_Gauss_zone_18: int
    Pulkovo_Gauss_zone_19: int
    Pulkovo_Gauss_zone_20: int
    Pulkovo_Gauss_zone_21: int
    Pulkovo_Gauss_zone_22: int
    Pulkovo_Gauss_zone_23: int
    Pulkovo_Gauss_zone_24: int
    Pulkovo_Gauss_zone_25: int
    Pulkovo_Gauss_zone_26: int
    Pulkovo_Gauss_zone_27: int
    Pulkovo_Gauss_zone_28: int
    Pulkovo_Gauss_zone_29: int
    Pulkovo_Gauss_zone_30: int
    Pulkovo_Gauss_zone_31: int
    Pulkovo_Gauss_zone_32: int
    Pulkovo_Gauss_4N: int
    Pulkovo_Gauss_5N: int
    Pulkovo_Gauss_6N: int
    Pulkovo_Gauss_7N: int
    Pulkovo_Gauss_8N: int
    Pulkovo_Gauss_9N: int
    Pulkovo_Gauss_10N: int
    Pulkovo_Gauss_11N: int
    Pulkovo_Gauss_12N: int
    Pulkovo_Gauss_13N: int
    Pulkovo_Gauss_14N: int
    Pulkovo_Gauss_15N: int
    Pulkovo_Gauss_16N: int
    Pulkovo_Gauss_17N: int
    Pulkovo_Gauss_18N: int
    Pulkovo_Gauss_19N: int
    Pulkovo_Gauss_20N: int
    Pulkovo_Gauss_21N: int
    Pulkovo_Gauss_22N: int
    Pulkovo_Gauss_23N: int
    Pulkovo_Gauss_24N: int
    Pulkovo_Gauss_25N: int
    Pulkovo_Gauss_26N: int
    Pulkovo_Gauss_27N: int
    Pulkovo_Gauss_28N: int
    Pulkovo_Gauss_29N: int
    Pulkovo_Gauss_30N: int
    Pulkovo_Gauss_31N: int
    Pulkovo_Gauss_32N: int
    Qatar_National_Grid: int
    RD_Netherlands_Old: int
    RD_Netherlands_New: int
    SAD69_UTM_zone_18N: int
    SAD69_UTM_zone_19N: int
    SAD69_UTM_zone_20N: int
    SAD69_UTM_zone_21N: int
    SAD69_UTM_zone_22N: int
    SAD69_UTM_zone_17S: int
    SAD69_UTM_zone_18S: int
    SAD69_UTM_zone_19S: int
    SAD69_UTM_zone_20S: int
    SAD69_UTM_zone_21S: int
    SAD69_UTM_zone_22S: int
    SAD69_UTM_zone_23S: int
    SAD69_UTM_zone_24S: int
    SAD69_UTM_zone_25S: int
    Sapper_Hill_UTM_20S: int
    Sapper_Hill_UTM_21S: int
    Schwarzeck_UTM_33S: int
    Sudan_UTM_zone_35N: int
    Sudan_UTM_zone_36N: int
    Tananarive_Laborde: int
    Tananarive_UTM_38S: int
    Tananarive_UTM_39S: int
    Timbalai_1948_Borneo: int
    Timbalai_1948_UTM_49N: int
    Timbalai_1948_UTM_50N: int
    TM65_Irish_Nat_Grid: int
    Trinidad_1903_Trinidad: int
    TC_1948_UTM_zone_39N: int
    TC_1948_UTM_zone_40N: int
    Voirol_N_Algerie_ancien: int
    Voirol_S_Algerie_ancien: int
    Voirol_Unifie_N_Algerie: int
    Voirol_Unifie_S_Algerie: int
    Bern_1938_Swiss_New: int
    Nord_Sahara_UTM_29N: int
    Nord_Sahara_UTM_30N: int
    Nord_Sahara_UTM_31N: int
    Nord_Sahara_UTM_32N: int
    Yoff_UTM_zone_28N: int
    Zanderij_UTM_zone_21N: int
    MGI_Austria_West: int
    MGI_Austria_Central: int
    MGI_Austria_East: int
    Belge_Lambert_72: int
    DHDN_Germany_zone_1: int
    DHDN_Germany_zone_2: int
    DHDN_Germany_zone_3: int
    DHDN_Germany_zone_4: int
    DHDN_Germany_zone_5: int
    NAD27_Montana_North: int
    NAD27_Montana_Central: int
    NAD27_Montana_South: int
    NAD27_Nebraska_North: int
    NAD27_Nebraska_South: int
    NAD27_Nevada_East: int
    NAD27_Nevada_Central: int
    NAD27_Nevada_West: int
    NAD27_New_Hampshire: int
    NAD27_New_Jersey: int
    NAD27_New_Mexico_East: int
    NAD27_New_Mexico_Cent: int
    NAD27_New_Mexico_West: int
    NAD27_New_York_East: int
    NAD27_New_York_Central: int
    NAD27_New_York_West: int
    NAD27_New_York_Long_Is: int
    NAD27_North_Carolina: int
    NAD27_North_Dakota_N: int
    NAD27_North_Dakota_S: int
    NAD27_Ohio_North: int
    NAD27_Ohio_South: int
    NAD27_Oklahoma_North: int
    NAD27_Oklahoma_South: int
    NAD27_Oregon_North: int
    NAD27_Oregon_South: int
    NAD27_Pennsylvania_N: int
    NAD27_Pennsylvania_S: int
    NAD27_Rhode_Island: int
    NAD27_South_Carolina_N: int
    NAD27_South_Carolina_S: int
    NAD27_South_Dakota_N: int
    NAD27_South_Dakota_S: int
    NAD27_Tennessee: int
    NAD27_Texas_North: int
    NAD27_Texas_North_Cen: int
    NAD27_Texas_Central: int
    NAD27_Texas_South_Cen: int
    NAD27_Texas_South: int
    NAD27_Utah_North: int
    NAD27_Utah_Central: int
    NAD27_Utah_South: int
    NAD27_Vermont: int
    NAD27_Virginia_North: int
    NAD27_Virginia_South: int
    NAD27_Washington_North: int
    NAD27_Washington_South: int
    NAD27_West_Virginia_N: int
    NAD27_West_Virginia_S: int
    NAD27_Wisconsin_North: int
    NAD27_Wisconsin_Cen: int
    NAD27_Wisconsin_South: int
    NAD27_Wyoming_East: int
    NAD27_Wyoming_E_Cen: int
    NAD27_Wyoming_W_Cen: int
    NAD27_Wyoming_West: int
    NAD27_Puerto_Rico: int
    NAD27_St_Croix: int
    NAD83_Montana: int
    NAD83_Nebraska: int
    NAD83_Nevada_East: int
    NAD83_Nevada_Central: int
    NAD83_Nevada_West: int
    NAD83_New_Hampshire: int
    NAD83_New_Jersey: int
    NAD83_New_Mexico_East: int
    NAD83_New_Mexico_Cent: int
    NAD83_New_Mexico_West: int
    NAD83_New_York_East: int
    NAD83_New_York_Central: int
    NAD83_New_York_West: int
    NAD83_New_York_Long_Is: int
    NAD83_North_Carolina: int
    NAD83_North_Dakota_N: int
    NAD83_North_Dakota_S: int
    NAD83_Ohio_North: int
    NAD83_Ohio_South: int
    NAD83_Oklahoma_North: int
    NAD83_Oklahoma_South: int
    NAD83_Oregon_North: int
    NAD83_Oregon_South: int
    NAD83_Pennsylvania_N: int
    NAD83_Pennsylvania_S: int
    NAD83_Rhode_Island: int
    NAD83_South_Carolina: int
    NAD83_South_Dakota_N: int
    NAD83_South_Dakota_S: int
    NAD83_Tennessee: int
    NAD83_Texas_North: int
    NAD83_Texas_North_Cen: int
    NAD83_Texas_Central: int
    NAD83_Texas_South_Cen: int
    NAD83_Texas_South: int
    NAD83_Utah_North: int
    NAD83_Utah_Central: int
    NAD83_Utah_South: int
    NAD83_Vermont: int
    NAD83_Virginia_North: int
    NAD83_Virginia_South: int
    NAD83_Washington_North: int
    NAD83_Washington_South: int
    NAD83_West_Virginia_N: int
    NAD83_West_Virginia_S: int
    NAD83_Wisconsin_North: int
    NAD83_Wisconsin_Cen: int
    NAD83_Wisconsin_South: int
    NAD83_Wyoming_East: int
    NAD83_Wyoming_E_Cen: int
    NAD83_Wyoming_W_Cen: int
    NAD83_Wyoming_West: int
    NAD83_Puerto_Rico_Virgin_Is: int
    WGS72_UTM_zone_1N: int
    WGS72_UTM_zone_2N: int
    WGS72_UTM_zone_3N: int
    WGS72_UTM_zone_4N: int
    WGS72_UTM_zone_5N: int
    WGS72_UTM_zone_6N: int
    WGS72_UTM_zone_7N: int
    WGS72_UTM_zone_8N: int
    WGS72_UTM_zone_9N: int
    WGS72_UTM_zone_10N: int
    WGS72_UTM_zone_11N: int
    WGS72_UTM_zone_12N: int
    WGS72_UTM_zone_13N: int
    WGS72_UTM_zone_14N: int
    WGS72_UTM_zone_15N: int
    WGS72_UTM_zone_16N: int
    WGS72_UTM_zone_17N: int
    WGS72_UTM_zone_18N: int
    WGS72_UTM_zone_19N: int
    WGS72_UTM_zone_20N: int
    WGS72_UTM_zone_21N: int
    WGS72_UTM_zone_22N: int
    WGS72_UTM_zone_23N: int
    WGS72_UTM_zone_24N: int
    WGS72_UTM_zone_25N: int
    WGS72_UTM_zone_26N: int
    WGS72_UTM_zone_27N: int
    WGS72_UTM_zone_28N: int
    WGS72_UTM_zone_29N: int
    WGS72_UTM_zone_30N: int
    WGS72_UTM_zone_31N: int
    WGS72_UTM_zone_32N: int
    WGS72_UTM_zone_33N: int
    WGS72_UTM_zone_34N: int
    WGS72_UTM_zone_35N: int
    WGS72_UTM_zone_36N: int
    WGS72_UTM_zone_37N: int
    WGS72_UTM_zone_38N: int
    WGS72_UTM_zone_39N: int
    WGS72_UTM_zone_40N: int
    WGS72_UTM_zone_41N: int
    WGS72_UTM_zone_42N: int
    WGS72_UTM_zone_43N: int
    WGS72_UTM_zone_44N: int
    WGS72_UTM_zone_45N: int
    WGS72_UTM_zone_46N: int
    WGS72_UTM_zone_47N: int
    WGS72_UTM_zone_48N: int
    WGS72_UTM_zone_49N: int
    WGS72_UTM_zone_50N: int
    WGS72_UTM_zone_51N: int
    WGS72_UTM_zone_52N: int
    WGS72_UTM_zone_53N: int
    WGS72_UTM_zone_54N: int
    WGS72_UTM_zone_55N: int
    WGS72_UTM_zone_56N: int
    WGS72_UTM_zone_57N: int
    WGS72_UTM_zone_58N: int
    WGS72_UTM_zone_59N: int
    WGS72_UTM_zone_60N: int
    WGS72_UTM_zone_1S: int
    WGS72_UTM_zone_2S: int
    WGS72_UTM_zone_3S: int
    WGS72_UTM_zone_4S: int
    WGS72_UTM_zone_5S: int
    WGS72_UTM_zone_6S: int
    WGS72_UTM_zone_7S: int
    WGS72_UTM_zone_8S: int
    WGS72_UTM_zone_9S: int
    WGS72_UTM_zone_10S: int
    WGS72_UTM_zone_11S: int
    WGS72_UTM_zone_12S: int
    WGS72_UTM_zone_13S: int
    WGS72_UTM_zone_14S: int
    WGS72_UTM_zone_15S: int
    WGS72_UTM_zone_16S: int
    WGS72_UTM_zone_17S: int
    WGS72_UTM_zone_18S: int
    WGS72_UTM_zone_19S: int
    WGS72_UTM_zone_20S: int
    WGS72_UTM_zone_21S: int
    WGS72_UTM_zone_22S: int
    WGS72_UTM_zone_23S: int
    WGS72_UTM_zone_24S: int
    WGS72_UTM_zone_25S: int
    WGS72_UTM_zone_26S: int
    WGS72_UTM_zone_27S: int
    WGS72_UTM_zone_28S: int
    WGS72_UTM_zone_29S: int
    WGS72_UTM_zone_30S: int
    WGS72_UTM_zone_31S: int
    WGS72_UTM_zone_32S: int
    WGS72_UTM_zone_33S: int
    WGS72_UTM_zone_34S: int
    WGS72_UTM_zone_35S: int
    WGS72_UTM_zone_36S: int
    WGS72_UTM_zone_37S: int
    WGS72_UTM_zone_38S: int
    WGS72_UTM_zone_39S: int
    WGS72_UTM_zone_40S: int
    WGS72_UTM_zone_41S: int
    WGS72_UTM_zone_42S: int
    WGS72_UTM_zone_43S: int
    WGS72_UTM_zone_44S: int
    WGS72_UTM_zone_45S: int
    WGS72_UTM_zone_46S: int
    WGS72_UTM_zone_47S: int
    WGS72_UTM_zone_48S: int
    WGS72_UTM_zone_49S: int
    WGS72_UTM_zone_50S: int
    WGS72_UTM_zone_51S: int
    WGS72_UTM_zone_52S: int
    WGS72_UTM_zone_53S: int
    WGS72_UTM_zone_54S: int
    WGS72_UTM_zone_55S: int
    WGS72_UTM_zone_56S: int
    WGS72_UTM_zone_57S: int
    WGS72_UTM_zone_58S: int
    WGS72_UTM_zone_59S: int
    WGS72_UTM_zone_60S: int
    WGS72BE_UTM_zone_1N: int
    WGS72BE_UTM_zone_2N: int
    WGS72BE_UTM_zone_3N: int
    WGS72BE_UTM_zone_4N: int
    WGS72BE_UTM_zone_5N: int
    WGS72BE_UTM_zone_6N: int
    WGS72BE_UTM_zone_7N: int
    WGS72BE_UTM_zone_8N: int
    WGS72BE_UTM_zone_9N: int
    WGS72BE_UTM_zone_10N: int
    WGS72BE_UTM_zone_11N: int
    WGS72BE_UTM_zone_12N: int
    WGS72BE_UTM_zone_13N: int
    WGS72BE_UTM_zone_14N: int
    WGS72BE_UTM_zone_15N: int
    WGS72BE_UTM_zone_16N: int
    WGS72BE_UTM_zone_17N: int
    WGS72BE_UTM_zone_18N: int
    WGS72BE_UTM_zone_19N: int
    WGS72BE_UTM_zone_20N: int
    WGS72BE_UTM_zone_21N: int
    WGS72BE_UTM_zone_22N: int
    WGS72BE_UTM_zone_23N: int
    WGS72BE_UTM_zone_24N: int
    WGS72BE_UTM_zone_25N: int
    WGS72BE_UTM_zone_26N: int
    WGS72BE_UTM_zone_27N: int
    WGS72BE_UTM_zone_28N: int
    WGS72BE_UTM_zone_29N: int
    WGS72BE_UTM_zone_30N: int
    WGS72BE_UTM_zone_31N: int
    WGS72BE_UTM_zone_32N: int
    WGS72BE_UTM_zone_33N: int
    WGS72BE_UTM_zone_34N: int
    WGS72BE_UTM_zone_35N: int
    WGS72BE_UTM_zone_36N: int
    WGS72BE_UTM_zone_37N: int
    WGS72BE_UTM_zone_38N: int
    WGS72BE_UTM_zone_39N: int
    WGS72BE_UTM_zone_40N: int
    WGS72BE_UTM_zone_41N: int
    WGS72BE_UTM_zone_42N: int
    WGS72BE_UTM_zone_43N: int
    WGS72BE_UTM_zone_44N: int
    WGS72BE_UTM_zone_45N: int
    WGS72BE_UTM_zone_46N: int
    WGS72BE_UTM_zone_47N: int
    WGS72BE_UTM_zone_48N: int
    WGS72BE_UTM_zone_49N: int
    WGS72BE_UTM_zone_50N: int
    WGS72BE_UTM_zone_51N: int
    WGS72BE_UTM_zone_52N: int
    WGS72BE_UTM_zone_53N: int
    WGS72BE_UTM_zone_54N: int
    WGS72BE_UTM_zone_55N: int
    WGS72BE_UTM_zone_56N: int
    WGS72BE_UTM_zone_57N: int
    WGS72BE_UTM_zone_58N: int
    WGS72BE_UTM_zone_59N: int
    WGS72BE_UTM_zone_60N: int
    WGS72BE_UTM_zone_1S: int
    WGS72BE_UTM_zone_2S: int
    WGS72BE_UTM_zone_3S: int
    WGS72BE_UTM_zone_4S: int
    WGS72BE_UTM_zone_5S: int
    WGS72BE_UTM_zone_6S: int
    WGS72BE_UTM_zone_7S: int
    WGS72BE_UTM_zone_8S: int
    WGS72BE_UTM_zone_9S: int
    WGS72BE_UTM_zone_10S: int
    WGS72BE_UTM_zone_11S: int
    WGS72BE_UTM_zone_12S: int
    WGS72BE_UTM_zone_13S: int
    WGS72BE_UTM_zone_14S: int
    WGS72BE_UTM_zone_15S: int
    WGS72BE_UTM_zone_16S: int
    WGS72BE_UTM_zone_17S: int
    WGS72BE_UTM_zone_18S: int
    WGS72BE_UTM_zone_19S: int
    WGS72BE_UTM_zone_20S: int
    WGS72BE_UTM_zone_21S: int
    WGS72BE_UTM_zone_22S: int
    WGS72BE_UTM_zone_23S: int
    WGS72BE_UTM_zone_24S: int
    WGS72BE_UTM_zone_25S: int
    WGS72BE_UTM_zone_26S: int
    WGS72BE_UTM_zone_27S: int
    WGS72BE_UTM_zone_28S: int
    WGS72BE_UTM_zone_29S: int
    WGS72BE_UTM_zone_30S: int
    WGS72BE_UTM_zone_31S: int
    WGS72BE_UTM_zone_32S: int
    WGS72BE_UTM_zone_33S: int
    WGS72BE_UTM_zone_34S: int
    WGS72BE_UTM_zone_35S: int
    WGS72BE_UTM_zone_36S: int
    WGS72BE_UTM_zone_37S: int
    WGS72BE_UTM_zone_38S: int
    WGS72BE_UTM_zone_39S: int
    WGS72BE_UTM_zone_40S: int
    WGS72BE_UTM_zone_41S: int
    WGS72BE_UTM_zone_42S: int
    WGS72BE_UTM_zone_43S: int
    WGS72BE_UTM_zone_44S: int
    WGS72BE_UTM_zone_45S: int
    WGS72BE_UTM_zone_46S: int
    WGS72BE_UTM_zone_47S: int
    WGS72BE_UTM_zone_48S: int
    WGS72BE_UTM_zone_49S: int
    WGS72BE_UTM_zone_50S: int
    WGS72BE_UTM_zone_51S: int
    WGS72BE_UTM_zone_52S: int
    WGS72BE_UTM_zone_53S: int
    WGS72BE_UTM_zone_54S: int
    WGS72BE_UTM_zone_55S: int
    WGS72BE_UTM_zone_56S: int
    WGS72BE_UTM_zone_57S: int
    WGS72BE_UTM_zone_58S: int
    WGS72BE_UTM_zone_59S: int
    WGS72BE_UTM_zone_60S: int
    WGS84_UTM_zone_1N: int
    WGS84_UTM_zone_2N: int
    WGS84_UTM_zone_3N: int
    WGS84_UTM_zone_4N: int
    WGS84_UTM_zone_5N: int
    WGS84_UTM_zone_6N: int
    WGS84_UTM_zone_7N: int
    WGS84_UTM_zone_8N: int
    WGS84_UTM_zone_9N: int
    WGS84_UTM_zone_10N: int
    WGS84_UTM_zone_11N: int
    WGS84_UTM_zone_12N: int
    WGS84_UTM_zone_13N: int
    WGS84_UTM_zone_14N: int
    WGS84_UTM_zone_15N: int
    WGS84_UTM_zone_16N: int
    WGS84_UTM_zone_17N: int
    WGS84_UTM_zone_18N: int
    WGS84_UTM_zone_19N: int
    WGS84_UTM_zone_20N: int
    WGS84_UTM_zone_21N: int
    WGS84_UTM_zone_22N: int
    WGS84_UTM_zone_23N: int
    WGS84_UTM_zone_24N: int
    WGS84_UTM_zone_25N: int
    WGS84_UTM_zone_26N: int
    WGS84_UTM_zone_27N: int
    WGS84_UTM_zone_28N: int
    WGS84_UTM_zone_29N: int
    WGS84_UTM_zone_30N: int
    WGS84_UTM_zone_31N: int
    WGS84_UTM_zone_32N: int
    WGS84_UTM_zone_33N: int
    WGS84_UTM_zone_34N: int
    WGS84_UTM_zone_35N: int
    WGS84_UTM_zone_36N: int
    WGS84_UTM_zone_37N: int
    WGS84_UTM_zone_38N: int
    WGS84_UTM_zone_39N: int
    WGS84_UTM_zone_40N: int
    WGS84_UTM_zone_41N: int
    WGS84_UTM_zone_42N: int
    WGS84_UTM_zone_43N: int
    WGS84_UTM_zone_44N: int
    WGS84_UTM_zone_45N: int
    WGS84_UTM_zone_46N: int
    WGS84_UTM_zone_47N: int
    WGS84_UTM_zone_48N: int
    WGS84_UTM_zone_49N: int
    WGS84_UTM_zone_50N: int
    WGS84_UTM_zone_51N: int
    WGS84_UTM_zone_52N: int
    WGS84_UTM_zone_53N: int
    WGS84_UTM_zone_54N: int
    WGS84_UTM_zone_55N: int
    WGS84_UTM_zone_56N: int
    WGS84_UTM_zone_57N: int
    WGS84_UTM_zone_58N: int
    WGS84_UTM_zone_59N: int
    WGS84_UTM_zone_60N: int
    WGS84_UTM_zone_1S: int
    WGS84_UTM_zone_2S: int
    WGS84_UTM_zone_3S: int
    WGS84_UTM_zone_4S: int
    WGS84_UTM_zone_5S: int
    WGS84_UTM_zone_6S: int
    WGS84_UTM_zone_7S: int
    WGS84_UTM_zone_8S: int
    WGS84_UTM_zone_9S: int
    WGS84_UTM_zone_10S: int
    WGS84_UTM_zone_11S: int
    WGS84_UTM_zone_12S: int
    WGS84_UTM_zone_13S: int
    WGS84_UTM_zone_14S: int
    WGS84_UTM_zone_15S: int
    WGS84_UTM_zone_16S: int
    WGS84_UTM_zone_17S: int
    WGS84_UTM_zone_18S: int
    WGS84_UTM_zone_19S: int
    WGS84_UTM_zone_20S: int
    WGS84_UTM_zone_21S: int
    WGS84_UTM_zone_22S: int
    WGS84_UTM_zone_23S: int
    WGS84_UTM_zone_24S: int
    WGS84_UTM_zone_25S: int
    WGS84_UTM_zone_26S: int
    WGS84_UTM_zone_27S: int
    WGS84_UTM_zone_28S: int
    WGS84_UTM_zone_29S: int
    WGS84_UTM_zone_30S: int
    WGS84_UTM_zone_31S: int
    WGS84_UTM_zone_32S: int
    WGS84_UTM_zone_33S: int
    WGS84_UTM_zone_34S: int
    WGS84_UTM_zone_35S: int
    WGS84_UTM_zone_36S: int
    WGS84_UTM_zone_37S: int
    WGS84_UTM_zone_38S: int
    WGS84_UTM_zone_39S: int
    WGS84_UTM_zone_40S: int
    WGS84_UTM_zone_41S: int
    WGS84_UTM_zone_42S: int
    WGS84_UTM_zone_43S: int
    WGS84_UTM_zone_44S: int
    WGS84_UTM_zone_45S: int
    WGS84_UTM_zone_46S: int
    WGS84_UTM_zone_47S: int
    WGS84_UTM_zone_48S: int
    WGS84_UTM_zone_49S: int
    WGS84_UTM_zone_50S: int
    WGS84_UTM_zone_51S: int
    WGS84_UTM_zone_52S: int
    WGS84_UTM_zone_53S: int
    WGS84_UTM_zone_54S: int
    WGS84_UTM_zone_55S: int
    WGS84_UTM_zone_56S: int
    WGS84_UTM_zone_57S: int
    WGS84_UTM_zone_58S: int
    WGS84_UTM_zone_59S: int
    WGS84_UTM_zone_60S: int
    GGRS87_Greek_Grid: int
    KKJ_Finland_zone_1: int
    KKJ_Finland_zone_2: int
    KKJ_Finland_zone_3: int
    KKJ_Finland_zone_4: int
    RT90_2_5_gon_W: int
    Lietuvos_Koordinoei_Sistema_1994: int
    Estonian_Coordinate_System_of_1992: int
    HD72_EOV: int
    Dealul_Piscului_1970_Stereo_70: int
    Hjorsey_1955_Lambert: int
    ISN93_Lambert_1993: int
    ETRS89_Poland_CS2000_zone_5: int
    ETRS89_Poland_CS2000_zone_6: int
    ETRS89_Poland_CS2000_zone_7: int
    ETRS89_Poland_CS2000_zone_8: int
    ETRS89_Poland_CS92: int

class GCSE(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Airy1830: int
    AiryModified1849: int
    AustralianNationalSpheroid: int
    Bessel1841: int
    BesselModified: int
    BesselNamibia: int
    Clarke1858: int
    Clarke1866: int
    Clarke1866Michigan: int
    Clarke1880_Benoit: int
    Clarke1880_IGN: int
    Clarke1880_RGS: int
    Clarke1880_Arc: int
    Clarke1880_SGA1922: int
    Everest1830_1937Adjustment: int
    Everest1830_1967Definition: int
    Everest1830_1975Definition: int
    Everest1830Modified: int
    GRS1980: int
    Helmert1906: int
    IndonesianNationalSpheroid: int
    International1924: int
    International1967: int
    Krassowsky1940: int
    NWL9D: int
    NWL10D: int
    Plessis1817: int
    Struve1860: int
    WarOffice: int
    WGS84: int
    GEM10C: int
    OSU86F: int
    OSU91A: int
    Clarke1880: int
    Sphere: int

class GCS(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Adindan: int
    AGD66: int
    AGD84: int
    Ain_el_Abd: int
    Afgooye: int
    Agadez: int
    Lisbon: int
    Aratu: int
    Arc_1950: int
    Arc_1960: int
    Batavia: int
    Barbados: int
    Beduaram: int
    Beijing_1954: int
    Belge_1950: int
    Bermuda_1957: int
    Bern_1898: int
    Bogota: int
    Bukit_Rimpah: int
    Camacupa: int
    Campo_Inchauspe: int
    Cape: int
    Carthage: int
    Chua: int
    Corrego_Alegre: int
    Cote_d_Ivoire: int
    Deir_ez_Zor: int
    Douala: int
    Egypt_1907: int
    ED50: int
    ED87: int
    Fahud: int
    Gandajika_1970: int
    Garoua: int
    Guyane_Francaise: int
    Hu_Tzu_Shan: int
    HD72: int
    ID74: int
    Indian_1954: int
    Indian_1975: int
    Jamaica_1875: int
    JAD69: int
    Kalianpur: int
    Kandawala: int
    Kertau: int
    KOC: int
    La_Canoa: int
    PSAD56: int
    Lake: int
    Leigon: int
    Liberia_1964: int
    Lome: int
    Luzon_1911: int
    Hito_XVIII_1963: int
    Herat_North: int
    Mahe_1971: int
    Makassar: int
    EUREF89: int
    Malongo_1987: int
    Manoca: int
    Merchich: int
    Massawa: int
    Minna: int
    Mhast: int
    Monte_Mario: int
    M_poraloko: int
    NAD27: int
    NAD_Michigan: int
    NAD83: int
    Nahrwan_1967: int
    Naparima_1972: int
    GD49: int
    NGO_1948: int
    Datum_73: int
    NTF: int
    NSWC_9Z_2: int
    OSGB_1936: int
    OSGB70: int
    OS_SN80: int
    Padang: int
    Palestine_1923: int
    Pointe_Noire: int
    GDA94: int
    Pulkovo_1942: int
    Qatar: int
    Qatar_1948: int
    Qornoq: int
    Loma_Quintana: int
    Amersfoort: int
    RT38: int
    SAD69: int
    Sapper_Hill_1943: int
    Schwarzeck: int
    Segora: int
    Serindung: int
    Sudan: int
    Tananarive: int
    Timbalai_1948: int
    TM65: int
    TM75: int
    Tokyo: int
    Trinidad_1903: int
    TC_1948: int
    Voirol_1875: int
    Voirol_Unifie: int
    Bern_1938: int
    Nord_Sahara_1959: int
    Stockholm_1938: int
    Yacare: int
    Yoff: int
    Zanderij: int
    MGI: int
    Belge_1972: int
    DHDN: int
    Conakry_1905: int
    WGS_72: int
    WGS_72BE: int
    WGS_84: int
    Bern_1898_Bern: int
    Bogota_Bogota: int
    Lisbon_Lisbon: int
    Makassar_Jakarta: int
    MGI_Ferro: int
    Monte_Mario_Rome: int
    NTF_Paris: int
    Padang_Jakarta: int
    Belge_1950_Brussels: int
    Tananarive_Paris: int
    Voirol_1875_Paris: int
    Voirol_Unifie_Paris: int
    Batavia_Jakarta: int
    ATF_Paris: int
    NDG_Paris: int
    Greek: int
    GGRS87: int
    KKJ: int
    RT90: int
    EST92: int
    Dealul_Piscului_1970: int
    Greek_Athens: int

class Ellipse(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Airy_1830: int
    Airy_Modified_1849: int
    Australian_National_Spheroid: int
    Bessel_1841: int
    Bessel_Modified: int
    Bessel_Namibia: int
    Clarke_1858: int
    Clarke_1866: int
    Clarke_1866_Michigan: int
    Clarke_1880_Benoit: int
    Clarke_1880_IGN: int
    Clarke_1880_RGS: int
    Clarke_1880_Arc: int
    Clarke_1880_SGA_1922: int
    Everest_1830_1937_Adjustment: int
    Everest_1830_1967_Definition: int
    Everest_1830_1975_Definition: int
    Everest_1830_Modified: int
    GRS_1980: int
    Helmert_1906: int
    Indonesian_National_Spheroid: int
    International_1924: int
    International_1967: int
    Krassowsky_1940: int
    NWL_9D: int
    NWL_10D: int
    Plessis_1817: int
    Struve_1860: int
    War_Office: int
    WGS_84: int
    GEM_10C: int
    OSU86F: int
    OSU91A: int
    Clarke_1880: int
    Sphere: int

class DatumE(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Airy1830: int
    AiryModified1849: int
    AustralianNationalSpheroid: int
    Bessel1841: int
    BesselModified: int
    BesselNamibia: int
    Clarke1858: int
    Clarke1866: int
    Clarke1866Michigan: int
    Clarke1880_Benoit: int
    Clarke1880_IGN: int
    Clarke1880_RGS: int
    Clarke1880_Arc: int
    Clarke1880_SGA1922: int
    Everest1830_1937Adjustment: int
    Everest1830_1967Definition: int
    Everest1830_1975Definition: int
    Everest1830Modified: int
    GRS1980: int
    Helmert1906: int
    IndonesianNationalSpheroid: int
    International1924: int
    International1967: int
    Krassowsky1960: int
    NWL9D: int
    NWL10D: int
    Plessis1817: int
    Struve1860: int
    WarOffice: int
    WGS84: int
    GEM10C: int
    OSU86F: int
    OSU91A: int
    Clarke1880: int
    Sphere: int

class Datum(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Adindan: int
    Australian_Geodetic_Datum_1966: int
    Australian_Geodetic_Datum_1984: int
    Ain_el_Abd_1970: int
    Afgooye: int
    Agadez: int
    Lisbon: int
    Aratu: int
    Arc_1950: int
    Arc_1960: int
    Batavia: int
    Barbados: int
    Beduaram: int
    Beijing_1954: int
    Reseau_National_Belge_1950: int
    Bermuda_1957: int
    Bern_1898: int
    Bogota: int
    Bukit_Rimpah: int
    Camacupa: int
    Campo_Inchauspe: int
    Cape: int
    Carthage: int
    Chua: int
    Corrego_Alegre: int
    Cote_d_Ivoire: int
    Deir_ez_Zor: int
    Douala: int
    Egypt_1907: int
    European_Datum_1950: int
    European_Datum_1987: int
    Fahud: int
    Gandajika_1970: int
    Garoua: int
    Guyane_Francaise: int
    Hu_Tzu_Shan: int
    Hungarian_Datum_1972: int
    Indonesian_Datum_1974: int
    Indian_1954: int
    Indian_1975: int
    Jamaica_1875: int
    Jamaica_1969: int
    Kalianpur: int
    Kandawala: int
    Kertau: int
    Kuwait_Oil_Company: int
    La_Canoa: int
    Provisional_S_American_Datum_1956: int
    Lake: int
    Leigon: int
    Liberia_1964: int
    Lome: int
    Luzon_1911: int
    Hito_XVIII_1963: int
    Herat_North: int
    Mahe_1971: int
    Makassar: int
    European_Reference_System_1989: int
    Malongo_1987: int
    Manoca: int
    Merchich: int
    Massawa: int
    Minna: int
    Mhast: int
    Monte_Mario: int
    M_poraloko: int
    North_American_Datum_1927: int
    NAD_Michigan: int
    North_American_Datum_1983: int
    Nahrwan_1967: int
    Naparima_1972: int
    New_Zealand_Geodetic_Datum_1949: int
    NGO_1948: int
    Datum_73: int
    Nouvelle_Triangulation_Francaise: int
    NSWC_9Z_2: int
    OSGB_1936: int
    OSGB_1970_SN: int
    OS_SN_1980: int
    Padang_1884: int
    Palestine_1923: int
    Pointe_Noire: int
    Geocentric_Datum_of_Australia_1994: int
    Pulkovo_1942: int
    Qatar: int
    Qatar_1948: int
    Qornoq: int
    Loma_Quintana: int
    Amersfoort: int
    RT38: int
    South_American_Datum_1969: int
    Sapper_Hill_1943: int
    Schwarzeck: int
    Segora: int
    Serindung: int
    Sudan: int
    Tananarive_1925: int
    Timbalai_1948: int
    TM65: int
    TM75: int
    Tokyo: int
    Trinidad_1903: int
    Trucial_Coast_1948: int
    Voirol_1875: int
    Voirol_Unifie_1960: int
    Bern_1938: int
    Nord_Sahara_1959: int
    Stockholm_1938: int
    Yacare: int
    Yoff: int
    Zanderij: int
    Militar_Geographische_Institut: int
    Reseau_National_Belge_1972: int
    Deutsche_Hauptdreiecksnetz: int
    Conakry_1905: int
    Dealul_Piscului_1930: int
    Dealul_Piscului_1970: int
    WGS72: int
    WGS72_Transit_Broadcast_Ephemeris: int
    WGS84: int
    Ancienne_Triangulation_Francaise: int
    Nord_de_Guerre: int

class ModelType(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Projected: int
    Geographic: int
    Geocentric: int

class RasterPixel(enum.IntEnum):
    Undefined: int
    User_Defined: int
    IsArea: int
    IsPoint: int

class Linear(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Meter: int
    Foot: int
    Foot_US_Survey: int
    Foot_Modified_American: int
    Foot_Clarke: int
    Foot_Indian: int
    Link: int
    Link_Benoit: int
    Link_Sears: int
    Chain_Benoit: int
    Chain_Sears: int
    Yard_Sears: int
    Yard_Indian: int
    Fathom: int
    Mile_International_Nautical: int

class Angular(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Radian: int
    Degree: int
    Arc_Minute: int
    Arc_Second: int
    Grad: int
    Gon: int
    DMS: int
    DMS_Hemisphere: int

class PM(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Greenwich: int
    Lisbon: int
    Paris: int
    Bogota: int
    Madrid: int
    Rome: int
    Bern: int
    Jakarta: int
    Ferro: int
    Brussels: int
    Stockholm: int

class CT(enum.IntEnum):
    Undefined: int
    User_Defined: int
    TransverseMercator: int
    TransvMercator_Modified_Alaska: int
    ObliqueMercator: int
    ObliqueMercator_Laborde: int
    ObliqueMercator_Rosenmund: int
    ObliqueMercator_Spherical: int
    Mercator: int
    LambertConfConic_2SP: int
    LambertConfConic_Helmert: int
    LambertAzimEqualArea: int
    AlbersEqualArea: int
    AzimuthalEquidistant: int
    EquidistantConic: int
    Stereographic: int
    PolarStereographic: int
    ObliqueStereographic: int
    Equirectangular: int
    CassiniSoldner: int
    Gnomonic: int
    MillerCylindrical: int
    Orthographic: int
    Polyconic: int
    Robinson: int
    Sinusoidal: int
    VanDerGrinten: int
    NewZealandMapGrid: int
    TransvMercator_SouthOriented: int
    CylindricalEqualArea: int
    HotineObliqueMercatorAzimuthCenter: int

class VertCS(enum.IntEnum):
    Undefined: int
    User_Defined: int
    Airy_1830_ellipsoid: int
    Airy_Modified_1849_ellipsoid: int
    ANS_ellipsoid: int
    Bessel_1841_ellipsoid: int
    Bessel_Modified_ellipsoid: int
    Bessel_Namibia_ellipsoid: int
    Clarke_1858_ellipsoid: int
    Clarke_1866_ellipsoid: int
    Clarke_1880_Benoit_ellipsoid: int
    Clarke_1880_IGN_ellipsoid: int
    Clarke_1880_RGS_ellipsoid: int
    Clarke_1880_Arc_ellipsoid: int
    Clarke_1880_SGA_1922_ellipsoid: int
    Everest_1830_1937_Adjustment_ellipsoid: int
    Everest_1830_1967_Definition_ellipsoid: int
    Everest_1830_1975_Definition_ellipsoid: int
    Everest_1830_Modified_ellipsoid: int
    GRS_1980_ellipsoid: int
    Helmert_1906_ellipsoid: int
    INS_ellipsoid: int
    International_1924_ellipsoid: int
    International_1967_ellipsoid: int
    Krassowsky_1940_ellipsoid: int
    NWL_9D_ellipsoid: int
    NWL_10D_ellipsoid: int
    Plessis_1817_ellipsoid: int
    Struve_1860_ellipsoid: int
    War_Office_ellipsoid: int
    WGS_84_ellipsoid: int
    GEM_10C_ellipsoid: int
    OSU86F_ellipsoid: int
    OSU91A_ellipsoid: int
    Newlyn: int
    North_American_Vertical_Datum_1929: int
    North_American_Vertical_Datum_1988: int
    Yellow_Sea_1956: int
    Baltic_Sea: int
    Caspian_Sea: int

GEO_CODES: dict[int, type[enum.IntEnum]]
