from _typeshed import Incomplete

def shortest_augmenting_path(G, s, t, capacity: str = ..., residual: Incomplete | None = ..., value_only: bool = ..., two_phase: bool = ..., cutoff: Incomplete | None = ...): ...
