from _typeshed import Incomplete
from networkx.classes.graph import Graph

class _CachedPropertyResetterAdjAndSucc:
    def __set__(self, obj, value) -> None: ...

class _CachedPropertyResetterPred:
    def __set__(self, obj, value) -> None: ...

class DiGraph(Graph):
    graph: Incomplete
    def __init__(self, incoming_graph_data: Incomplete | None = ..., **attr) -> None: ...
    def adj(self): ...
    def succ(self): ...
    def pred(self): ...
    def add_node(self, node_for_adding, **attr) -> None: ...
    def add_nodes_from(self, nodes_for_adding, **attr) -> None: ...
    def remove_node(self, n) -> None: ...
    def remove_nodes_from(self, nodes) -> None: ...
    def add_edge(self, u_of_edge, v_of_edge, **attr) -> None: ...
    def add_edges_from(self, ebunch_to_add, **attr) -> None: ...
    def remove_edge(self, u, v) -> None: ...
    def remove_edges_from(self, ebunch) -> None: ...
    def has_successor(self, u, v): ...
    def has_predecessor(self, u, v): ...
    def successors(self, n): ...
    neighbors: Incomplete
    def predecessors(self, n): ...
    def edges(self): ...
    def out_edges(self): ...
    def in_edges(self): ...
    def degree(self): ...
    def in_degree(self): ...
    def out_degree(self): ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    def is_multigraph(self): ...
    def is_directed(self): ...
    def to_undirected(self, reciprocal: bool = ..., as_view: bool = ...): ...
    def reverse(self, copy: bool = ...): ...
