from _typeshed import Incomplete
from networkx.generators.classic import barbell_graph as barbell_graph, cycle_graph as cycle_graph, path_graph as path_graph
from networkx.utils import graphs_equal as graphs_equal

np: Incomplete
sp: Incomplete

class TestConvertScipy:
    G1: Incomplete
    G2: Incomplete
    G3: Incomplete
    G4: Incomplete
    def setup_method(self) -> None: ...
    def test_exceptions(self) -> None: ...
    def create_weighted(self, G): ...
    def identity_conversion(self, G, A, create_using) -> None: ...
    def test_shape(self) -> None: ...
    def test_identity_graph_matrix(self) -> None: ...
    def test_identity_digraph_matrix(self) -> None: ...
    def test_identity_weighted_graph_matrix(self) -> None: ...
    def test_identity_weighted_digraph_matrix(self) -> None: ...
    def test_nodelist(self) -> None: ...
    def test_weight_keyword(self) -> None: ...
    def test_format_keyword(self) -> None: ...
    def test_format_keyword_raise(self) -> None: ...
    def test_null_raise(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_ordering(self) -> None: ...
    def test_selfloop_graph(self) -> None: ...
    def test_selfloop_digraph(self) -> None: ...
    def test_from_scipy_sparse_array_parallel_edges(self) -> None: ...
    def test_symmetric(self) -> None: ...

def test_from_scipy_sparse_array_formats(sparse_format) -> None: ...
def test_scipy_sparse_matrix_deprecations() -> None: ...
