from _typeshed import Incomplete

class ClusterError(Exception): ...

def whiten(obs, check_finite: bool = ...): ...
def vq(obs, code_book, check_finite: bool = ...): ...
def kmeans(obs, k_or_guess, iter: int = ..., thresh: float = ..., check_finite: bool = ..., *, seed: Incomplete | None = ...): ...
def kmeans2(data, k, iter: int = ..., thresh: float = ..., minit: str = ..., missing: str = ..., check_finite: bool = ..., *, seed: Incomplete | None = ...): ...
