from .. import util as util
from _typeshed import Incomplete

class Camera:
    name: Incomplete
    z_far: Incomplete
    z_near: Incomplete
    def __init__(self, name: Incomplete | None = ..., resolution: Incomplete | None = ..., focal: Incomplete | None = ..., fov: Incomplete | None = ..., z_near: float = ..., z_far: float = ...) -> None: ...
    def copy(self): ...
    @property
    def resolution(self): ...
    @resolution.setter
    def resolution(self, values) -> None: ...
    @property
    def focal(self): ...
    @focal.setter
    def focal(self, values) -> None: ...
    @property
    def K(self): ...
    @K.setter
    def K(self, values) -> None: ...
    @property
    def fov(self): ...
    @fov.setter
    def fov(self, values) -> None: ...
    def to_rays(self): ...
    def angles(self): ...
    def look_at(self, points, **kwargs): ...

def look_at(points, fov, rotation: Incomplete | None = ..., distance: Incomplete | None = ..., center: Incomplete | None = ..., pad: Incomplete | None = ...): ...
def ray_pixel_coords(camera): ...
def camera_to_rays(camera): ...
