from _typeshed import Incomplete

def astar_path(G, source, target, heuristic: Incomplete | None = ..., weight: str = ...): ...
def astar_path_length(G, source, target, heuristic: Incomplete | None = ..., weight: str = ...): ...
