from _typeshed import Incomplete

def has_path(G, source, target): ...
def shortest_path(G, source: Incomplete | None = ..., target: Incomplete | None = ..., weight: Incomplete | None = ..., method: str = ...): ...
def shortest_path_length(G, source: Incomplete | None = ..., target: Incomplete | None = ..., weight: Incomplete | None = ..., method: str = ...): ...
def average_shortest_path_length(G, weight: Incomplete | None = ..., method: Incomplete | None = ...): ...
def all_shortest_paths(G, source, target, weight: Incomplete | None = ..., method: str = ...): ...
