import glooey
import pyglet
from .. import rendering as rendering
from .trackball import Trackball as Trackball
from .windowed import SceneViewer as SceneViewer, geometry_hash as geometry_hash
from _typeshed import Incomplete

class SceneGroup(pyglet.graphics.Group):
    rect: Incomplete
    scene: Incomplete
    def __init__(self, rect, scene, background: Incomplete | None = ..., pixel_per_point=..., parent: Incomplete | None = ...) -> None: ...
    def set_state(self) -> None: ...
    def unset_state(self) -> None: ...

class MeshGroup(pyglet.graphics.Group):
    transform: Incomplete
    texture: Incomplete
    def __init__(self, transform: Incomplete | None = ..., texture: Incomplete | None = ..., parent: Incomplete | None = ...) -> None: ...
    def set_state(self) -> None: ...
    def unset_state(self) -> None: ...

class SceneWidget(glooey.Widget):
    scene: Incomplete
    mesh_group: Incomplete
    vertex_list: Incomplete
    vertex_list_hash: Incomplete
    textures: Incomplete
    def __init__(self, scene, **kwargs) -> None: ...
    @property
    def scene_group(self): ...
    def clear(self) -> None: ...
    view: Incomplete
    def reset_view(self) -> None: ...
    def do_claim(self): ...
    def do_regroup(self) -> None: ...
    def do_draw(self) -> None: ...
    def do_undraw(self) -> None: ...
    def on_mouse_press(self, x, y, buttons, modifiers) -> None: ...
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers) -> None: ...
    def on_mouse_scroll(self, x, y, dx, dy) -> None: ...
