import numpy as np
from _typeshed import Incomplete
from collections.abc import Generator
from datetime import tzinfo
from pandas import DataFrame as DataFrame
from pandas._libs import lib as lib, tslib as tslib
from pandas._libs.tslibs import BaseOffset as BaseOffset, NaT as NaT, NaTType as NaTType, Resolution as Resolution, Timestamp as Timestamp, astype_overflowsafe as astype_overflowsafe, fields as fields, get_resolution as get_resolution, get_unit_from_dtype as get_unit_from_dtype, ints_to_pydatetime as ints_to_pydatetime, is_date_array_normalized as is_date_array_normalized, is_supported_unit as is_supported_unit, is_unitless as is_unitless, normalize_i8_timestamps as normalize_i8_timestamps, timezones as timezones, to_offset as to_offset, tz_convert_from_utc as tz_convert_from_utc, tzconversion as tzconversion
from pandas._typing import npt as npt
from pandas.core.arrays import PeriodArray as PeriodArray, TimedeltaArray as TimedeltaArray, datetimelike as dtl
from pandas.core.arrays._ranges import generate_regular_range as generate_regular_range
from pandas.core.dtypes.astype import astype_dt64_to_dt64tz as astype_dt64_to_dt64tz
from pandas.core.dtypes.common import DT64NS_DTYPE as DT64NS_DTYPE, INT64_DTYPE as INT64_DTYPE, is_bool_dtype as is_bool_dtype, is_datetime64_any_dtype as is_datetime64_any_dtype, is_datetime64_dtype as is_datetime64_dtype, is_datetime64_ns_dtype as is_datetime64_ns_dtype, is_datetime64tz_dtype as is_datetime64tz_dtype, is_dtype_equal as is_dtype_equal, is_extension_array_dtype as is_extension_array_dtype, is_float_dtype as is_float_dtype, is_object_dtype as is_object_dtype, is_period_dtype as is_period_dtype, is_sparse as is_sparse, is_string_dtype as is_string_dtype, is_timedelta64_dtype as is_timedelta64_dtype, pandas_dtype as pandas_dtype
from pandas.core.dtypes.dtypes import DatetimeTZDtype as DatetimeTZDtype
from pandas.core.dtypes.missing import isna as isna
from pandas.errors import OutOfBoundsDatetime as OutOfBoundsDatetime, PerformanceWarning as PerformanceWarning
from pandas.tseries.frequencies import get_period_alias as get_period_alias
from pandas.tseries.offsets import BDay as BDay, Day as Day, Tick as Tick
from pandas.util._exceptions import find_stack_level as find_stack_level
from pandas.util._validators import validate_inclusive as validate_inclusive

def tz_to_dtype(tz: Union[tzinfo, None], unit: str = ...): ...

class DatetimeArray(dtl.TimelikeOps, dtl.DatelikeOps):
    __array_priority__: int
    @property
    def dtype(self) -> Union[np.dtype, DatetimeTZDtype]: ...
    @property
    def tz(self) -> Union[tzinfo, None]: ...
    @tz.setter
    def tz(self, value) -> None: ...
    @property
    def tzinfo(self) -> Union[tzinfo, None]: ...
    @property
    def is_normalized(self) -> bool: ...
    def __array__(self, dtype: Incomplete | None = ...) -> np.ndarray: ...
    def __iter__(self): ...
    def astype(self, dtype, copy: bool = ...): ...
    def tz_convert(self, tz) -> DatetimeArray: ...
    def tz_localize(self, tz, ambiguous: str = ..., nonexistent: str = ...) -> DatetimeArray: ...
    def to_pydatetime(self) -> npt.NDArray[np.object_]: ...
    def normalize(self) -> DatetimeArray: ...
    def to_period(self, freq: Incomplete | None = ...) -> PeriodArray: ...
    def to_perioddelta(self, freq) -> TimedeltaArray: ...
    def month_name(self, locale: Incomplete | None = ...) -> npt.NDArray[np.object_]: ...
    def day_name(self, locale: Incomplete | None = ...) -> npt.NDArray[np.object_]: ...
    @property
    def time(self) -> npt.NDArray[np.object_]: ...
    @property
    def timetz(self) -> npt.NDArray[np.object_]: ...
    @property
    def date(self) -> npt.NDArray[np.object_]: ...
    def isocalendar(self) -> DataFrame: ...
    @property
    def weekofyear(self): ...
    week: Incomplete
    year: Incomplete
    month: Incomplete
    day: Incomplete
    hour: Incomplete
    minute: Incomplete
    second: Incomplete
    microsecond: Incomplete
    nanosecond: Incomplete
    day_of_week: Incomplete
    dayofweek: Incomplete
    weekday: Incomplete
    day_of_year: Incomplete
    dayofyear: Incomplete
    quarter: Incomplete
    days_in_month: Incomplete
    daysinmonth: Incomplete
    is_month_start: Incomplete
    is_month_end: Incomplete
    is_quarter_start: Incomplete
    is_quarter_end: Incomplete
    is_year_start: Incomplete
    is_year_end: Incomplete
    is_leap_year: Incomplete
    def to_julian_date(self) -> npt.NDArray[np.float64]: ...
    def std(self, axis: Incomplete | None = ..., dtype: Incomplete | None = ..., out: Incomplete | None = ..., ddof: int = ..., keepdims: bool = ..., skipna: bool = ...): ...

def sequence_to_datetimes(data, require_iso8601: bool = ...) -> DatetimeArray: ...
def objects_to_datetime64ns(data: np.ndarray, dayfirst, yearfirst, utc: bool = ..., errors: str = ..., require_iso8601: bool = ..., allow_object: bool = ..., allow_mixed: bool = ...): ...
def maybe_convert_dtype(data, copy: bool, tz: Union[tzinfo, None] = ...): ...
def validate_tz_from_dtype(dtype, tz: Union[tzinfo, None]) -> Union[tzinfo, None]: ...
def generate_range(start: Incomplete | None = ..., end: Incomplete | None = ..., periods: Incomplete | None = ..., offset=...) -> Generator[Incomplete, None, None]: ...
