import numpy as np
from _typeshed import Incomplete
from pandas import DataFrame as DataFrame
from pandas._libs import lib as lib, tslibs as tslibs
from pandas._libs.tslibs import BaseOffset as BaseOffset, NaT as NaT, NaTType as NaTType, Tick as Tick, Timedelta as Timedelta, astype_overflowsafe as astype_overflowsafe, iNaT as iNaT, periods_per_second as periods_per_second, to_offset as to_offset
from pandas._libs.tslibs.conversion import precision_from_unit as precision_from_unit
from pandas._libs.tslibs.fields import get_timedelta_field as get_timedelta_field
from pandas._libs.tslibs.timedeltas import array_to_timedelta64 as array_to_timedelta64, ints_to_pytimedelta as ints_to_pytimedelta, parse_timedelta_unit as parse_timedelta_unit
from pandas._typing import DtypeObj as DtypeObj, NpDtype as NpDtype, npt as npt
from pandas.core import nanops as nanops
from pandas.core.arrays import datetimelike as dtl
from pandas.core.arrays._ranges import generate_regular_range as generate_regular_range
from pandas.core.dtypes.astype import astype_td64_unit_conversion as astype_td64_unit_conversion
from pandas.core.dtypes.common import TD64NS_DTYPE as TD64NS_DTYPE, is_dtype_equal as is_dtype_equal, is_float_dtype as is_float_dtype, is_integer_dtype as is_integer_dtype, is_object_dtype as is_object_dtype, is_scalar as is_scalar, is_string_dtype as is_string_dtype, is_timedelta64_dtype as is_timedelta64_dtype, pandas_dtype as pandas_dtype
from pandas.core.dtypes.missing import isna as isna
from pandas.core.ops.common import unpack_zerodim_and_defer as unpack_zerodim_and_defer
from pandas.util._validators import validate_endpoints as validate_endpoints

class TimedeltaArray(dtl.TimelikeOps):
    __array_priority__: int
    @property
    def dtype(self) -> np.dtype: ...
    def astype(self, dtype, copy: bool = ...): ...
    def __iter__(self): ...
    def sum(self, *, axis: Union[int, None] = ..., dtype: Union[NpDtype, None] = ..., out: Incomplete | None = ..., keepdims: bool = ..., initial: Incomplete | None = ..., skipna: bool = ..., min_count: int = ...): ...
    def std(self, *, axis: Union[int, None] = ..., dtype: Union[NpDtype, None] = ..., out: Incomplete | None = ..., ddof: int = ..., keepdims: bool = ..., skipna: bool = ...): ...
    def __mul__(self, other) -> TimedeltaArray: ...
    __rmul__: Incomplete
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __mod__(self, other): ...
    def __rmod__(self, other): ...
    def __divmod__(self, other): ...
    def __rdivmod__(self, other): ...
    def __neg__(self) -> TimedeltaArray: ...
    def __pos__(self) -> TimedeltaArray: ...
    def __abs__(self) -> TimedeltaArray: ...
    def total_seconds(self) -> npt.NDArray[np.float64]: ...
    def to_pytimedelta(self) -> npt.NDArray[np.object_]: ...
    days: Incomplete
    seconds: Incomplete
    microseconds: Incomplete
    nanoseconds: Incomplete
    @property
    def components(self) -> DataFrame: ...

def sequence_to_td64ns(data, copy: bool = ..., unit: Incomplete | None = ..., errors: str = ...) -> tuple[np.ndarray, Union[Tick, None]]: ...
def ints_to_td64ns(data, unit: str = ...): ...
