from _typeshed import Incomplete

def histogram(image, nbins: int = ..., source_range: str = ..., normalize: bool = ..., *, channel_axis: Incomplete | None = ...): ...
def cumulative_distribution(image, nbins: int = ...): ...
def equalize_hist(image, nbins: int = ..., mask: Incomplete | None = ...): ...
def rescale_intensity(image, in_range: str = ..., out_range: str = ...): ...
def adjust_gamma(image, gamma: int = ..., gain: int = ...): ...
def adjust_log(image, gain: int = ..., inv: bool = ...): ...
def adjust_sigmoid(image, cutoff: float = ..., gain: int = ..., inv: bool = ...): ...
