from _typeshed import Incomplete
from networkx.algorithms.flow import boykov_kolmogorov as boykov_kolmogorov, dinitz as dinitz, edmonds_karp as edmonds_karp, preflow_push as preflow_push, shortest_augmenting_path as shortest_augmenting_path

flow_funcs: Incomplete

class TestGomoryHuTree:
    def minimum_edge_weight(self, T, u, v): ...
    def compute_cutset(self, G, T_orig, edge): ...
    def test_default_flow_function_karate_club_graph(self) -> None: ...
    def test_karate_club_graph(self) -> None: ...
    def test_davis_southern_women_graph(self) -> None: ...
    def test_florentine_families_graph(self) -> None: ...
    def test_les_miserables_graph_cutset(self) -> None: ...
    def test_karate_club_graph_cutset(self) -> None: ...
    def test_wikipedia_example(self) -> None: ...
    def test_directed_raises(self) -> None: ...
    def test_empty_raises(self) -> None: ...
