from _typeshed import Incomplete
from networkx.algorithms.flow import boykov_kolmogorov as boykov_kolmogorov, build_flow_dict as build_flow_dict, build_residual_network as build_residual_network, dinitz as dinitz, edmonds_karp as edmonds_karp, preflow_push as preflow_push, shortest_augmenting_path as shortest_augmenting_path

flow_funcs: Incomplete

def gen_pyramid(N): ...
def read_graph(name): ...
def validate_flows(G, s, t, soln_value, R, flow_func) -> None: ...

class TestMaxflowLargeGraph:
    def test_complete_graph(self) -> None: ...
    def test_pyramid(self) -> None: ...
    def test_gl1(self) -> None: ...
    def test_gw1(self) -> None: ...
    def test_wlm3(self) -> None: ...
    def test_preflow_push_global_relabel(self) -> None: ...
