from typing import Any

circle_perimeter: function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _hough_circle(*args, **kwargs) -> Any: ...
def _hough_ellipse(*args, **kwargs) -> Any: ...
def _hough_line(*args, **kwargs) -> Any: ...
def _probabilistic_hough_line(*args, **kwargs) -> Any: ...
