from _typeshed import Incomplete

def hough_line_peaks(hspace, angles, dists, min_distance: int = ..., min_angle: int = ..., threshold: Incomplete | None = ..., num_peaks=...): ...
def hough_circle(image, radius, normalize: bool = ..., full_output: bool = ...): ...
def hough_ellipse(image, threshold: int = ..., accuracy: int = ..., min_size: int = ..., max_size: Incomplete | None = ...): ...
def hough_line(image, theta: Incomplete | None = ...): ...
def probabilistic_hough_line(image, threshold: int = ..., line_length: int = ..., line_gap: int = ..., theta: Incomplete | None = ..., seed: Incomplete | None = ...): ...
def hough_circle_peaks(hspaces, radii, min_xdistance: int = ..., min_ydistance: int = ..., threshold: Incomplete | None = ..., num_peaks=..., total_num_peaks=..., normalize: bool = ...): ...
def label_distant_points(xs, ys, min_xdistance, min_ydistance, max_points): ...
