from .._shared import utils as utils
from .._shared.filters import gaussian as gaussian
from .._shared.utils import convert_to_float as convert_to_float
from ..transform import resize as resize
from _typeshed import Incomplete
from collections.abc import Generator

def pyramid_reduce(image, downscale: int = ..., sigma: Incomplete | None = ..., order: int = ..., mode: str = ..., cval: int = ..., multichannel: bool = ..., preserve_range: bool = ..., *, channel_axis: Incomplete | None = ...): ...
def pyramid_expand(image, upscale: int = ..., sigma: Incomplete | None = ..., order: int = ..., mode: str = ..., cval: int = ..., multichannel: bool = ..., preserve_range: bool = ..., *, channel_axis: Incomplete | None = ...): ...
def pyramid_gaussian(image, max_layer: int = ..., downscale: int = ..., sigma: Incomplete | None = ..., order: int = ..., mode: str = ..., cval: int = ..., multichannel: bool = ..., preserve_range: bool = ..., *, channel_axis: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
def pyramid_laplacian(image, max_layer: int = ..., downscale: int = ..., sigma: Incomplete | None = ..., order: int = ..., mode: str = ..., cval: int = ..., multichannel: bool = ..., preserve_range: bool = ..., *, channel_axis: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
