from _typeshed import Incomplete
from networkx.exception import NetworkXError as NetworkXError
from networkx.generators.degree_seq import havel_hakimi_graph as havel_hakimi_graph

np: Incomplete

def test_incidence_matrix_simple() -> None: ...

class TestGraphMatrix:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_incidence_matrix(self) -> None: ...
    def test_weighted_incidence_matrix(self) -> None: ...
    def test_adjacency_matrix(self) -> None: ...
