from _typeshed import Incomplete
from networkx.generators.degree_seq import havel_hakimi_graph as havel_hakimi_graph

np: Incomplete

class TestModularity:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_modularity(self) -> None: ...
    def test_modularity_weight(self) -> None: ...
    def test_directed_modularity(self) -> None: ...
