from _typeshed import Incomplete
from networkx.generators.degree_seq import havel_hakimi_graph as havel_hakimi_graph
from networkx.generators.expanders import margulis_gabber_galil_graph as margulis_gabber_galil_graph

np: Incomplete

class TestLaplacian:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_laplacian(self) -> None: ...
    def test_normalized_laplacian(self) -> None: ...

def test_directed_laplacian() -> None: ...
def test_directed_combinatorial_laplacian() -> None: ...
