from _typeshed import Incomplete

np: Incomplete

def test_attr_matrix(): ...
def test_attr_matrix_directed() -> None: ...
def test_attr_matrix_multigraph() -> None: ...
def test_attr_sparse_matrix() -> None: ...
def test_attr_sparse_matrix_directed() -> None: ...
