from _typeshed import Incomplete

np: Incomplete
methods: Incomplete

def test_algebraic_connectivity_tracemin_chol() -> None: ...
def test_fiedler_vector_tracemin_chol() -> None: ...
def test_spectral_ordering_tracemin_chol() -> None: ...
def test_fiedler_vector_tracemin_unknown() -> None: ...
def check_eigenvector(A, l, x) -> None: ...

class TestAlgebraicConnectivity:
    def test_directed(self, method) -> None: ...
    def test_null_and_singleton(self, method) -> None: ...
    def test_disconnected(self, method) -> None: ...
    def test_unrecognized_method(self) -> None: ...
    def test_two_nodes(self, method) -> None: ...
    def test_two_nodes_multigraph(self, method) -> None: ...
    def test_abbreviation_of_method(self) -> None: ...
    def test_path(self, method) -> None: ...
    def test_problematic_graph_issue_2381(self, method) -> None: ...
    def test_cycle(self, method) -> None: ...
    def test_seed_argument(self, method) -> None: ...
    def test_buckminsterfullerene(self, normalized, sigma, laplacian_fn, method) -> None: ...

class TestSpectralOrdering:
    def test_nullgraph(self, graph) -> None: ...
    def test_singleton(self, graph) -> None: ...
    def test_unrecognized_method(self) -> None: ...
    def test_three_nodes(self, method) -> None: ...
    def test_three_nodes_multigraph(self, method) -> None: ...
    def test_path(self, method) -> None: ...
    def test_seed_argument(self, method) -> None: ...
    def test_disconnected(self, method) -> None: ...
    def test_cycle(self, normalized, expected_order, method) -> None: ...
