from ..util._map_array import map_array as map_array
from _typeshed import Incomplete

def pixel_graph(image, *, mask: Incomplete | None = ..., edge_function: Incomplete | None = ..., connectivity: int = ..., spacing: Incomplete | None = ...): ...
def central_pixel(graph, nodes: Incomplete | None = ..., shape: Incomplete | None = ..., partition_size: int = ...): ...
