from typing import Any, ClassVar

import skimage.graph._mcp

class MCP_Diff(skimage.graph._mcp.MCP):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, costs, offsets = ..., fully_connected = ...) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_MCP_Diff(*args, **kwargs) -> Any: ...
