from typing import Any, ClassVar

class BinaryHeap:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    count: Any
    levels: Any
    min_levels: Any
    def __init__(self, initial_capacity = ...) -> Any: ...
    def min_val(self) -> Any: ...
    def pop(self) -> Any: ...
    def push(self, value, reference = ...) -> Any: ...
    def references(self) -> Any: ...
    def reset(self) -> Any: ...
    def values(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class FastUpdateBinaryHeap(BinaryHeap):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    max_reference: Any
    def __init__(self, initial_capacity = ..., max_reference = ...) -> Any: ...
    def cross_references(self, *args, **kwargs) -> Any: ...
    def push(self, value, reference) -> Any: ...
    def push_if_lower(self, value, reference) -> Any: ...
    def reset(self) -> Any: ...
    def value_of(self, reference) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
