def test_directed_tree_str() -> None: ...
def test_empty_graph() -> None: ...
def test_directed_multi_tree_forest() -> None: ...
def test_undirected_multi_tree_forest() -> None: ...
def test_undirected_tree_str() -> None: ...
def test_forest_str_errors() -> None: ...
def test_overspecified_sources() -> None: ...
