from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class TestPajek:
    @classmethod
    def setup_class(cls) -> None: ...
    @classmethod
    def teardown_class(cls) -> None: ...
    def test_parse_pajek_simple(self) -> None: ...
    def test_parse_pajek(self) -> None: ...
    def test_parse_pajet_mat(self) -> None: ...
    def test_read_pajek(self) -> None: ...
    def test_write_pajek(self) -> None: ...
    def test_ignored_attribute(self) -> None: ...
    def test_noname(self) -> None: ...
    def test_unicode(self) -> None: ...
