from networkx.utils import edges_equal as edges_equal, graphs_equal as graphs_equal, nodes_equal as nodes_equal

class TestGpickle:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_gpickle(self) -> None: ...
    def test_protocol(self) -> None: ...
