from _typeshed import Incomplete
from networkx.readwrite.graphml import GraphMLWriter as GraphMLWriter
from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class BaseGraphML:
    @classmethod
    def setup_class(cls) -> None: ...

class TestReadGraphML(BaseGraphML):
    def test_read_simple_directed_graphml(self) -> None: ...
    def test_read_simple_undirected_graphml(self) -> None: ...
    def test_read_undirected_multigraph_graphml(self) -> None: ...
    def test_read_undirected_multigraph_no_multiedge_graphml(self) -> None: ...
    def test_read_undirected_multigraph_only_ids_for_multiedges_graphml(self) -> None: ...
    def test_read_attribute_graphml(self) -> None: ...
    def test_node_default_attribute_graphml(self) -> None: ...
    def test_directed_edge_in_undirected(self) -> None: ...
    def test_undirected_edge_in_directed(self) -> None: ...
    def test_key_raise(self) -> None: ...
    def test_hyperedge_raise(self) -> None: ...
    def test_multigraph_keys(self) -> None: ...
    def test_preserve_multi_edge_data(self) -> None: ...
    def test_yfiles_extension(self) -> None: ...
    def test_bool(self) -> None: ...
    def test_graphml_header_line(self) -> None: ...
    def test_read_attributes_with_groups(self) -> None: ...
    def test_long_attribute_type(self) -> None: ...

class TestWriteGraphML(BaseGraphML):
    writer: Incomplete
    @classmethod
    def setup_class(cls) -> None: ...
    def test_write_interface(self) -> None: ...
    def test_write_read_simple_directed_graphml(self) -> None: ...
    def test_GraphMLWriter_add_graphs(self) -> None: ...
    def test_write_read_simple_no_prettyprint(self) -> None: ...
    def test_write_read_attribute_named_key_ids_graphml(self) -> None: ...
    def test_write_read_attribute_numeric_type_graphml(self) -> None: ...
    def test_more_multigraph_keys(self) -> None: ...
    def test_default_attribute(self) -> None: ...
    def test_mixed_type_attributes(self) -> None: ...
    def test_str_number_mixed_type_attributes(self) -> None: ...
    def test_mixed_int_type_number_attributes(self) -> None: ...
    def test_numpy_float(self) -> None: ...
    def test_multigraph_to_graph(self) -> None: ...
    def test_write_generate_edge_id_from_attribute(self) -> None: ...
    def test_multigraph_write_generate_edge_id_from_attribute(self) -> None: ...
    def test_numpy_float64(self) -> None: ...
    def test_numpy_float32(self) -> None: ...
    def test_numpy_float64_inference(self) -> None: ...
    def test_unicode_attributes(self) -> None: ...
    def test_unicode_escape(self) -> None: ...

class TestXMLGraphML(TestWriteGraphML):
    writer: Incomplete
    @classmethod
    def setup_class(cls) -> None: ...

def test_exception_for_unsupported_datatype_node_attr() -> None: ...
def test_exception_for_unsupported_datatype_edge_attr() -> None: ...
def test_exception_for_unsupported_datatype_graph_attr() -> None: ...
