class TestGEXF:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_read_simple_directed_graphml(self) -> None: ...
    def test_write_read_simple_directed_graphml(self) -> None: ...
    def test_read_simple_undirected_graphml(self) -> None: ...
    def test_read_attribute_graphml(self) -> None: ...
    def test_directed_edge_in_undirected(self) -> None: ...
    def test_undirected_edge_in_directed(self) -> None: ...
    def test_key_raises(self) -> None: ...
    def test_relabel(self) -> None: ...
    def test_default_attribute(self) -> None: ...
    def test_serialize_ints_to_strings(self) -> None: ...
    def test_write_with_node_attributes(self) -> None: ...
    def test_edge_id_construct(self) -> None: ...
    def test_numpy_type(self) -> None: ...
    def test_bool(self) -> None: ...
    def test_specials(self) -> None: ...
    def test_simple_list(self) -> None: ...
    def test_dynamic_mode(self) -> None: ...
    def test_multigraph_with_missing_attributes(self) -> None: ...
    def test_missing_viz_attributes(self) -> None: ...
    def test_slice_and_spell(self) -> None: ...
    def test_add_parent(self) -> None: ...
