from networkx.readwrite.p2g import read_p2g as read_p2g, write_p2g as write_p2g
from networkx.utils import edges_equal as edges_equal

class TestP2G:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_read_p2g(self) -> None: ...
    def test_write_p2g(self) -> None: ...
    def test_write_read_p2g(self) -> None: ...
