from _typeshed import Incomplete

ogr: Incomplete

class TestShp:
    names: Incomplete
    paths: Incomplete
    simplified_names: Incomplete
    simplified_paths: Incomplete
    multi_names: Incomplete
    shppath: Incomplete
    multi_shppath: Incomplete
    testdir: Incomplete
    drv: Incomplete
    def setup_method(self): ...
    def deletetmp(self, drv, *paths) -> None: ...
    def testload(self) -> None: ...
    def checkgeom(self, lyr, expected) -> None: ...
    def test_geometryexport(self) -> None: ...
    def test_attributeexport(self) -> None: ...
    def test_nodeattributeexport(self) -> None: ...
    def test_wkt_export(self) -> None: ...
    def teardown_method(self) -> None: ...

def test_read_shp_nofile() -> None: ...

class TestMissingGeometry:
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    path: Incomplete
    def setup_path(self) -> None: ...
    def create_shapedir(self) -> None: ...
    def delete_shapedir(self) -> None: ...
    def test_missing_geometry(self) -> None: ...

class TestMissingAttrWrite:
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    path: Incomplete
    def setup_path(self) -> None: ...
    def delete_shapedir(self) -> None: ...
    def test_missing_attributes(self) -> None: ...
