from networkx.utils import edges_equal as edges_equal, graphs_equal as graphs_equal, nodes_equal as nodes_equal

class TestAdjlist:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_read_multiline_adjlist_1(self) -> None: ...
    def test_unicode(self) -> None: ...
    def test_latin1_err(self) -> None: ...
    def test_latin1(self) -> None: ...
    def test_parse_adjlist(self) -> None: ...
    def test_adjlist_graph(self) -> None: ...
    def test_adjlist_digraph(self) -> None: ...
    def test_adjlist_integers(self) -> None: ...
    def test_adjlist_multigraph(self) -> None: ...
    def test_adjlist_multidigraph(self) -> None: ...
    def test_adjlist_delimiter(self) -> None: ...

class TestMultilineAdjlist:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_parse_multiline_adjlist(self) -> None: ...
    def test_multiline_adjlist_graph(self) -> None: ...
    def test_multiline_adjlist_digraph(self) -> None: ...
    def test_multiline_adjlist_integers(self) -> None: ...
    def test_multiline_adjlist_multigraph(self) -> None: ...
    def test_multiline_adjlist_multidigraph(self) -> None: ...
    def test_multiline_adjlist_delimiter(self) -> None: ...
