from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class TestSparseGraph6:
    def test_from_sparse6_bytes(self) -> None: ...
    def test_from_bytes_multigraph_graph(self) -> None: ...
    def test_read_sparse6(self) -> None: ...
    def test_read_many_graph6(self) -> None: ...

class TestWriteSparse6:
    def test_null_graph(self) -> None: ...
    def test_trivial_graph(self) -> None: ...
    def test_empty_graph(self) -> None: ...
    def test_large_empty_graph(self) -> None: ...
    def test_very_large_empty_graph(self) -> None: ...
    def test_complete_graph(self) -> None: ...
    def test_no_header(self) -> None: ...
    def test_padding(self) -> None: ...
    def test_complete_bipartite(self) -> None: ...
    def test_read_write_inverse(self) -> None: ...
    def test_no_directed_graphs(self) -> None: ...
    def test_write_path(self) -> None: ...
