from _typeshed import Incomplete

np: Incomplete

class TestPageRank:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pagerank(self, alg) -> None: ...
    def test_pagerank_max_iter(self, alg) -> None: ...
    def test_numpy_pagerank(self) -> None: ...
    def test_google_matrix(self) -> None: ...
    def test_personalization(self, alg) -> None: ...
    def test_zero_personalization_vector(self, alg) -> None: ...
    def test_one_nonzero_personalization_value(self, alg) -> None: ...
    def test_incomplete_personalization(self, alg) -> None: ...
    def test_dangling_matrix(self) -> None: ...
    def test_dangling_pagerank(self, alg) -> None: ...
    def test_empty(self) -> None: ...
    def test_multigraph(self, alg) -> None: ...

class TestPageRankScipy(TestPageRank):
    def test_scipy_pagerank(self) -> None: ...
    def test_scipy_pagerank_max_iter(self) -> None: ...
    def test_dangling_scipy_pagerank(self) -> None: ...
    def test_empty_scipy(self) -> None: ...

def test_deprecation_warnings(pagerank_alg) -> None: ...
