from _typeshed import Incomplete

np: Incomplete
sp: Incomplete

class TestHITS:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_hits_numpy(self) -> None: ...
    def test_hits(self, hits_alg) -> None: ...
    def test_empty(self) -> None: ...
    def test_hits_not_convergent(self) -> None: ...

def test_deprecation_warnings(hits_alg) -> None: ...
