from _typeshed import Incomplete
from scipy.cluster.vq import ClusterError as ClusterError, kmeans as kmeans, kmeans2 as kmeans2, py_vq as py_vq, vq as vq, whiten as whiten
from scipy.sparse._sputils import matrix as matrix

TESTDATA_2D: Incomplete
X: Incomplete
CODET1: Incomplete
CODET2: Incomplete
LABEL1: Incomplete

class TestWhiten:
    def test_whiten(self) -> None: ...
    def test_whiten_zero_std(self) -> None: ...
    def test_whiten_not_finite(self) -> None: ...

class TestVq:
    def test_py_vq(self) -> None: ...
    def test_vq(self) -> None: ...
    def test_vq_1d(self) -> None: ...
    def test__vq_sametype(self) -> None: ...
    def test__vq_invalid_type(self) -> None: ...
    def test_vq_large_nfeat(self) -> None: ...
    def test_vq_large_features(self) -> None: ...

class TestKMean:
    def test_large_features(self) -> None: ...
    def test_kmeans_simple(self) -> None: ...
    def test_kmeans_lost_cluster(self) -> None: ...
    def test_kmeans2_simple(self) -> None: ...
    def test_kmeans2_rank1(self) -> None: ...
    def test_kmeans2_rank1_2(self) -> None: ...
    def test_kmeans2_high_dim(self) -> None: ...
    def test_kmeans2_init(self) -> None: ...
    def test_krandinit(self) -> None: ...
    def test_kmeans2_empty(self) -> None: ...
    def test_kmeans_0k(self) -> None: ...
    def test_kmeans_large_thres(self) -> None: ...
    def test_kmeans2_kpp_low_dim(self) -> None: ...
    def test_kmeans2_kpp_high_dim(self) -> None: ...
    def test_kmeans_diff_convergence(self) -> None: ...
    def test_kmeans_and_kmeans2_random_seed(self) -> None: ...
