from _typeshed import Incomplete
from collections.abc import Generator
from scipy.cluster.hierarchy import DisjointSet as DisjointSet

def generate_random_token() -> Generator[Incomplete, None, None]: ...
def get_elements(n): ...
def test_init() -> None: ...
def test_len() -> None: ...
def test_contains(n) -> None: ...
def test_add(n) -> None: ...
def test_element_not_present() -> None: ...
def test_linear_union_sequence(n, direction) -> None: ...
def test_self_unions(n) -> None: ...
def test_equal_size_ordering(n, order) -> None: ...
def test_binary_tree(kmax) -> None: ...
def test_subsets(n) -> None: ...
