from . import hierarchy_test_data as hierarchy_test_data
from scipy.cluster._hierarchy import Heap as Heap
from scipy.cluster.hierarchy import ClusterWarning as ClusterWarning, cophenet as cophenet, correspond as correspond, cut_tree as cut_tree, dendrogram as dendrogram, fcluster as fcluster, fclusterdata as fclusterdata, from_mlab_linkage as from_mlab_linkage, inconsistent as inconsistent, is_isomorphic as is_isomorphic, is_monotonic as is_monotonic, is_valid_im as is_valid_im, is_valid_linkage as is_valid_linkage, leaders as leaders, leaves_list as leaves_list, linkage as linkage, maxRstat as maxRstat, maxdists as maxdists, maxinconsts as maxinconsts, num_obs_linkage as num_obs_linkage, optimal_leaf_ordering as optimal_leaf_ordering, set_link_color_palette as set_link_color_palette, single as single, to_mlab_linkage as to_mlab_linkage, to_tree as to_tree
from scipy.spatial.distance import pdist as pdist

have_matplotlib: bool

class TestLinkage:
    def test_linkage_non_finite_elements_in_distance_matrix(self) -> None: ...
    def test_linkage_empty_distance_matrix(self) -> None: ...
    def test_linkage_tdist(self) -> None: ...
    def check_linkage_tdist(self, method) -> None: ...
    def test_linkage_X(self) -> None: ...
    def check_linkage_q(self, method) -> None: ...
    def test_compare_with_trivial(self) -> None: ...
    def test_optimal_leaf_ordering(self) -> None: ...

class TestLinkageTies:
    def test_linkage_ties(self) -> None: ...
    def check_linkage_ties(self, method) -> None: ...

class TestInconsistent:
    def test_inconsistent_tdist(self) -> None: ...
    def check_inconsistent_tdist(self, depth) -> None: ...

class TestCopheneticDistance:
    def test_linkage_cophenet_tdist_Z(self) -> None: ...
    def test_linkage_cophenet_tdist_Z_Y(self) -> None: ...

class TestMLabLinkageConversion:
    def test_mlab_linkage_conversion_empty(self) -> None: ...
    def test_mlab_linkage_conversion_single_row(self) -> None: ...
    def test_mlab_linkage_conversion_multiple_rows(self) -> None: ...

class TestFcluster:
    def test_fclusterdata(self) -> None: ...
    def check_fclusterdata(self, t, criterion) -> None: ...
    def test_fcluster(self) -> None: ...
    def check_fcluster(self, t, criterion) -> None: ...
    def test_fcluster_monocrit(self) -> None: ...
    def check_fcluster_monocrit(self, t) -> None: ...
    def check_fcluster_maxclust_monocrit(self, t) -> None: ...

class TestLeaders:
    def test_leaders_single(self) -> None: ...

class TestIsIsomorphic:
    def test_is_isomorphic_1(self) -> None: ...
    def test_is_isomorphic_2(self) -> None: ...
    def test_is_isomorphic_3(self) -> None: ...
    def test_is_isomorphic_4A(self) -> None: ...
    def test_is_isomorphic_4B(self) -> None: ...
    def test_is_isomorphic_4C(self) -> None: ...
    def test_is_isomorphic_5(self) -> None: ...
    def test_is_isomorphic_6(self) -> None: ...
    def test_is_isomorphic_7(self) -> None: ...
    def help_is_isomorphic_randperm(self, nobs, nclusters, noniso: bool = ..., nerrors: int = ...) -> None: ...

class TestIsValidLinkage:
    def test_is_valid_linkage_various_size(self) -> None: ...
    def check_is_valid_linkage_various_size(self, nrow, ncol, valid) -> None: ...
    def test_is_valid_linkage_int_type(self) -> None: ...
    def test_is_valid_linkage_empty(self) -> None: ...
    def test_is_valid_linkage_4_and_up(self) -> None: ...
    def test_is_valid_linkage_4_and_up_neg_index_left(self) -> None: ...
    def test_is_valid_linkage_4_and_up_neg_index_right(self) -> None: ...
    def test_is_valid_linkage_4_and_up_neg_dist(self) -> None: ...
    def test_is_valid_linkage_4_and_up_neg_counts(self) -> None: ...

class TestIsValidInconsistent:
    def test_is_valid_im_int_type(self) -> None: ...
    def test_is_valid_im_various_size(self) -> None: ...
    def check_is_valid_im_various_size(self, nrow, ncol, valid) -> None: ...
    def test_is_valid_im_empty(self) -> None: ...
    def test_is_valid_im_4_and_up(self) -> None: ...
    def test_is_valid_im_4_and_up_neg_index_left(self) -> None: ...
    def test_is_valid_im_4_and_up_neg_index_right(self) -> None: ...
    def test_is_valid_im_4_and_up_neg_dist(self) -> None: ...

class TestNumObsLinkage:
    def test_num_obs_linkage_empty(self) -> None: ...
    def test_num_obs_linkage_1x4(self) -> None: ...
    def test_num_obs_linkage_2x4(self) -> None: ...
    def test_num_obs_linkage_4_and_up(self) -> None: ...

class TestLeavesList:
    def test_leaves_list_1x4(self) -> None: ...
    def test_leaves_list_2x4(self) -> None: ...
    def test_leaves_list_Q(self) -> None: ...
    def check_leaves_list_Q(self, method) -> None: ...
    def test_Q_subtree_pre_order(self) -> None: ...

class TestCorrespond:
    def test_correspond_empty(self) -> None: ...
    def test_correspond_2_and_up(self) -> None: ...
    def test_correspond_4_and_up(self) -> None: ...
    def test_correspond_4_and_up_2(self) -> None: ...
    def test_num_obs_linkage_multi_matrix(self) -> None: ...

class TestIsMonotonic:
    def test_is_monotonic_empty(self) -> None: ...
    def test_is_monotonic_1x4(self) -> None: ...
    def test_is_monotonic_2x4_T(self) -> None: ...
    def test_is_monotonic_2x4_F(self) -> None: ...
    def test_is_monotonic_3x4_T(self) -> None: ...
    def test_is_monotonic_3x4_F1(self) -> None: ...
    def test_is_monotonic_3x4_F2(self) -> None: ...
    def test_is_monotonic_3x4_F3(self) -> None: ...
    def test_is_monotonic_tdist_linkage1(self) -> None: ...
    def test_is_monotonic_tdist_linkage2(self) -> None: ...
    def test_is_monotonic_Q_linkage(self) -> None: ...

class TestMaxDists:
    def test_maxdists_empty_linkage(self) -> None: ...
    def test_maxdists_one_cluster_linkage(self) -> None: ...
    def test_maxdists_Q_linkage(self) -> None: ...
    def check_maxdists_Q_linkage(self, method) -> None: ...

class TestMaxInconsts:
    def test_maxinconsts_empty_linkage(self) -> None: ...
    def test_maxinconsts_difrow_linkage(self) -> None: ...
    def test_maxinconsts_one_cluster_linkage(self) -> None: ...
    def test_maxinconsts_Q_linkage(self) -> None: ...
    def check_maxinconsts_Q_linkage(self, method) -> None: ...

class TestMaxRStat:
    def test_maxRstat_invalid_index(self) -> None: ...
    def check_maxRstat_invalid_index(self, i) -> None: ...
    def test_maxRstat_empty_linkage(self) -> None: ...
    def check_maxRstat_empty_linkage(self, i) -> None: ...
    def test_maxRstat_difrow_linkage(self) -> None: ...
    def check_maxRstat_difrow_linkage(self, i) -> None: ...
    def test_maxRstat_one_cluster_linkage(self) -> None: ...
    def check_maxRstat_one_cluster_linkage(self, i) -> None: ...
    def test_maxRstat_Q_linkage(self) -> None: ...
    def check_maxRstat_Q_linkage(self, method, i) -> None: ...

class TestDendrogram:
    def test_dendrogram_single_linkage_tdist(self) -> None: ...
    def test_valid_orientation(self) -> None: ...
    def test_labels_as_array_or_list(self) -> None: ...
    def test_valid_label_size(self) -> None: ...
    def test_dendrogram_plot(self) -> None: ...
    def check_dendrogram_plot(self, orientation) -> None: ...
    def test_dendrogram_truncate_mode(self) -> None: ...
    def test_dendrogram_colors(self) -> None: ...
    def test_dendrogram_leaf_colors_zero_dist(self) -> None: ...
    def test_dendrogram_leaf_colors(self) -> None: ...

def calculate_maximum_distances(Z): ...
def calculate_maximum_inconsistencies(Z, R, k: int = ...): ...
def test_unsupported_uncondensed_distance_matrix_linkage_warning() -> None: ...
def test_euclidean_linkage_value_error() -> None: ...
def test_2x2_linkage() -> None: ...
def test_node_compare() -> None: ...
def test_cut_tree() -> None: ...
def test_optimal_leaf_ordering() -> None: ...
def test_Heap() -> None: ...
