from _typeshed import Incomplete

def latapy_clustering(G, nodes: Incomplete | None = ..., mode: str = ...): ...
clustering = latapy_clustering

def average_clustering(G, nodes: Incomplete | None = ..., mode: str = ...): ...
def robins_alexander_clustering(G): ...
