from _typeshed import Incomplete

def complete_bipartite_graph(n1, n2, create_using: Incomplete | None = ...): ...
def configuration_model(aseq, bseq, create_using: Incomplete | None = ..., seed: Incomplete | None = ...): ...
def havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = ...): ...
def reverse_havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = ...): ...
def alternating_havel_hakimi_graph(aseq, bseq, create_using: Incomplete | None = ...): ...
def preferential_attachment_graph(aseq, p, create_using: Incomplete | None = ..., seed: Incomplete | None = ...): ...
def random_graph(n, m, p, seed: Incomplete | None = ..., directed: bool = ...): ...
def gnmk_random_graph(n, m, k, seed: Incomplete | None = ..., directed: bool = ...): ...
