from _typeshed import Incomplete

def biadjacency_matrix(G, row_order, column_order: Incomplete | None = ..., dtype: Incomplete | None = ..., weight: str = ..., format: str = ...): ...
def from_biadjacency_matrix(A, create_using: Incomplete | None = ..., edge_attribute: str = ...): ...
