from typing import Any

interpolation_types: dict
is_monotonic: fused_cython_function
rolling_rank_tiebreakers: dict

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def ewm(*args, **kwargs) -> Any: ...
def ewmcov(*args, **kwargs) -> Any: ...
def roll_apply(*args, **kwargs) -> Any: ...
def roll_kurt(*args, **kwargs) -> Any: ...
def roll_max(*args, **kwargs) -> Any: ...
def roll_mean(*args, **kwargs) -> Any: ...
def roll_median_c(*args, **kwargs) -> Any: ...
def roll_min(*args, **kwargs) -> Any: ...
def roll_quantile(*args, **kwargs) -> Any: ...
def roll_rank(*args, **kwargs) -> Any: ...
def roll_skew(*args, **kwargs) -> Any: ...
def roll_sum(*args, **kwargs) -> Any: ...
def roll_var(*args, **kwargs) -> Any: ...
def roll_weighted_mean(*args, **kwargs) -> Any: ...
def roll_weighted_sum(*args, **kwargs) -> Any: ...
def roll_weighted_var(*args, **kwargs) -> Any: ...
