from _typeshed import Incomplete
from scipy import sparse as sparse
from scipy.linalg import eig as eig, eigh as eigh, orth as orth, toeplitz as toeplitz
from scipy.sparse import csr_matrix as csr_matrix, diags as diags, eye as eye, spdiags as spdiags
from scipy.sparse.linalg import LinearOperator as LinearOperator, eigs as eigs
from scipy.sparse.linalg._eigen.lobpcg import lobpcg as lobpcg

INT_DTYPES: Incomplete
REAL_DTYPES: Incomplete
COMPLEX_DTYPES: Incomplete
VDTYPES: Incomplete
MDTYPES: Incomplete

def sign_align(A, B): ...
def ElasticRod(n): ...
def MikotaPair(n): ...
def compare_solutions(A, B, m) -> None: ...
def test_Small() -> None: ...
def test_ElasticRod() -> None: ...
def test_MikotaPair() -> None: ...
def test_b_orthonormalize(n, m, Vdtype, Bdtype, BVdtype): ...
def test_nonhermitian_warning(capsys) -> None: ...
def test_regression() -> None: ...
def test_diagonal(n, m, m_excluded): ...
def test_fiedler_small_8() -> None: ...
def test_fiedler_large_12() -> None: ...
def test_failure_to_run_iterations() -> None: ...
def test_failure_to_run_iterations_nonsymmetric() -> None: ...
def test_hermitian() -> None: ...
def test_eigs_consistency(n, atol) -> None: ...
def test_verbosity() -> None: ...
def test_tolerance_float32() -> None: ...
def test_dtypes(vdtype, mdtype, arr_type) -> None: ...
def test_inplace_warning() -> None: ...
def test_maxit() -> None: ...
def test_diagonal_data_types(n, m): ...
