from networkx.utils import edges_equal as edges_equal

def test_union_attributes() -> None: ...
def test_intersection() -> None: ...
def test_intersection_node_sets_different() -> None: ...
def test_intersection_attributes() -> None: ...
def test_intersection_attributes_node_sets_different() -> None: ...
def test_intersection_multigraph_attributes() -> None: ...
def test_intersection_multigraph_attributes_node_set_different() -> None: ...
def test_difference() -> None: ...
def test_difference2() -> None: ...
def test_difference_attributes() -> None: ...
def test_difference_multigraph_attributes() -> None: ...
def test_difference_raise() -> None: ...
def test_symmetric_difference_multigraph() -> None: ...
def test_union_and_compose() -> None: ...
def test_union_multigraph() -> None: ...
def test_disjoint_union_multigraph() -> None: ...
def test_compose_multigraph() -> None: ...
def test_full_join_graph() -> None: ...
def test_full_join_multigraph() -> None: ...
def test_mixed_type_union() -> None: ...
