from networkx.utils import edges_equal as edges_equal

def test_union_all_attributes() -> None: ...
def test_intersection_all() -> None: ...
def test_intersection_all_different_node_sets() -> None: ...
def test_intersection_all_attributes() -> None: ...
def test_intersection_all_attributes_different_node_sets() -> None: ...
def test_intersection_all_multigraph_attributes() -> None: ...
def test_intersection_all_multigraph_attributes_different_node_sets() -> None: ...
def test_union_all_and_compose_all() -> None: ...
def test_union_all_multigraph() -> None: ...
def test_input_output() -> None: ...
def test_mixed_type_union() -> None: ...
def test_mixed_type_disjoint_union() -> None: ...
def test_mixed_type_intersection() -> None: ...
def test_mixed_type_compose() -> None: ...
def test_empty_union() -> None: ...
def test_empty_disjoint_union() -> None: ...
def test_empty_compose_all() -> None: ...
def test_empty_intersection_all() -> None: ...
