class Flags:
    def __init__(self, obj, *, allows_duplicate_labels) -> None: ...
    @property
    def allows_duplicate_labels(self) -> bool: ...
    @allows_duplicate_labels.setter
    def allows_duplicate_labels(self, value: bool) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __eq__(self, other): ...
