import numpy as np
from _typeshed import Incomplete
from datetime import tzinfo
from pandas import DataFrame as DataFrame, Float64Index as Float64Index, PeriodIndex as PeriodIndex, TimedeltaIndex as TimedeltaIndex
from pandas._libs import NaT as NaT, Period as Period, Timestamp as Timestamp, lib as lib
from pandas._libs.tslibs import BaseOffset as BaseOffset, Resolution as Resolution, periods_per_day as periods_per_day, timezones as timezones, to_offset as to_offset
from pandas._libs.tslibs.dtypes import NpyDatetimeUnit as NpyDatetimeUnit
from pandas._libs.tslibs.offsets import prefix_mapping as prefix_mapping
from pandas._typing import Dtype as Dtype, DtypeObj as DtypeObj, IntervalClosedType as IntervalClosedType, IntervalLeftRight as IntervalLeftRight, npt as npt
from pandas.core.arrays.datetimes import DatetimeArray as DatetimeArray, tz_to_dtype as tz_to_dtype
from pandas.core.dtypes.common import is_datetime64_dtype as is_datetime64_dtype, is_datetime64tz_dtype as is_datetime64tz_dtype, is_dtype_equal as is_dtype_equal, is_scalar as is_scalar
from pandas.core.dtypes.missing import is_valid_na_for_dtype as is_valid_na_for_dtype
from pandas.core.indexes.base import Index as Index, get_unanimous_names as get_unanimous_names, maybe_extract_name as maybe_extract_name
from pandas.core.indexes.datetimelike import DatetimeTimedeltaMixin as DatetimeTimedeltaMixin
from pandas.core.indexes.extension import inherit_names as inherit_names
from pandas.core.tools.times import to_time as to_time
from pandas.util._decorators import cache_readonly as cache_readonly, doc as doc
from pandas.util._exceptions import find_stack_level as find_stack_level
from typing import Hashable, Literal

class DatetimeIndex(DatetimeTimedeltaMixin):
    inferred_freq: Union[str, None]
    tz: Union[tzinfo, None]
    def strftime(self, date_format) -> Index: ...
    def tz_convert(self, tz) -> DatetimeIndex: ...
    def tz_localize(self, tz, ambiguous: str = ..., nonexistent: str = ...) -> DatetimeIndex: ...
    def to_period(self, freq: Incomplete | None = ...) -> PeriodIndex: ...
    def to_perioddelta(self, freq) -> TimedeltaIndex: ...
    def to_julian_date(self) -> Float64Index: ...
    def isocalendar(self) -> DataFrame: ...
    def __new__(cls, data: Incomplete | None = ..., freq: Union[str, BaseOffset, lib.NoDefault] = ..., tz: Incomplete | None = ..., normalize: bool = ..., closed: Incomplete | None = ..., ambiguous: str = ..., dayfirst: bool = ..., yearfirst: bool = ..., dtype: Union[Dtype, None] = ..., copy: bool = ..., name: Hashable = ...) -> DatetimeIndex: ...
    def __reduce__(self): ...
    def union_many(self, others): ...
    def to_series(self, keep_tz=..., index: Incomplete | None = ..., name: Incomplete | None = ...): ...
    def snap(self, freq: str = ...) -> DatetimeIndex: ...
    def get_loc(self, key, method: Incomplete | None = ..., tolerance: Incomplete | None = ...): ...
    def slice_indexer(self, start: Incomplete | None = ..., end: Incomplete | None = ..., step: Incomplete | None = ..., kind=...): ...
    @property
    def inferred_type(self) -> str: ...
    def indexer_at_time(self, time, asof: bool = ...) -> npt.NDArray[np.intp]: ...
    def indexer_between_time(self, start_time, end_time, include_start: bool = ..., include_end: bool = ...) -> npt.NDArray[np.intp]: ...

def date_range(start: Incomplete | None = ..., end: Incomplete | None = ..., periods: Incomplete | None = ..., freq: Incomplete | None = ..., tz: Incomplete | None = ..., normalize: bool = ..., name: Hashable = ..., closed: Union[Literal['left', 'right'], None, lib.NoDefault] = ..., inclusive: Union[IntervalClosedType, None] = ..., **kwargs) -> DatetimeIndex: ...
def bdate_range(start: Incomplete | None = ..., end: Incomplete | None = ..., periods: Union[int, None] = ..., freq: str = ..., tz: Incomplete | None = ..., normalize: bool = ..., name: Hashable = ..., weekmask: Incomplete | None = ..., holidays: Incomplete | None = ..., closed: Union[IntervalLeftRight, lib.NoDefault, None] = ..., inclusive: Union[IntervalClosedType, None] = ..., **kwargs) -> DatetimeIndex: ...
