from .. import util as util
from ..constants import log as log
from _typeshed import Incomplete

def arc_center(points, return_normal: bool = ..., return_angle: bool = ...): ...
def discretize_arc(points, close: bool = ..., scale: float = ...): ...
def to_threepoint(center, radius, angles: Incomplete | None = ...): ...
