from . import arc as arc
from .. import transformations as transformations, util as util
from ..geometry import plane_transform as plane_transform
from .entities import Arc as Arc, Line as Line
from _typeshed import Incomplete

def circle_pattern(pattern_radius, circle_radius, count, center=..., angle: Incomplete | None = ..., **kwargs): ...
def circle(radius, center: Incomplete | None = ..., **kwargs): ...
def rectangle(bounds, **kwargs): ...
def box_outline(extents: Incomplete | None = ..., transform: Incomplete | None = ..., **kwargs): ...
def grid(side, count: int = ..., transform: Incomplete | None = ..., plane_origin: Incomplete | None = ..., plane_normal: Incomplete | None = ..., include_circle: bool = ..., sections_circle: int = ...): ...
