from _typeshed import Incomplete

def discretize_bezier(points, count: Incomplete | None = ..., scale: float = ...): ...
def discretize_bspline(control, knots, count: Incomplete | None = ..., scale: float = ...): ...
def binomial(n): ...
