from ..constants import log as log
from _typeshed import Incomplete

class RectangleBin:
    child: Incomplete
    occupied: bool
    bounds: Incomplete
    def __init__(self, bounds: Incomplete | None = ..., size: Incomplete | None = ...) -> None: ...
    @property
    def extents(self): ...
    def insert(self, rectangle): ...
    def split(self, length, vertical: bool = ...): ...

def rectangles_single(rectangles, sheet_size: Incomplete | None = ..., shuffle: bool = ...): ...
def paths(paths, **kwargs): ...
def polygons(polygons, sheet_size: Incomplete | None = ..., iterations: int = ..., density_escape: float = ..., spacing: float = ..., quantity: Incomplete | None = ..., **kwargs): ...
def rectangles(rectangles, sheet_size: Incomplete | None = ..., density_escape: float = ..., spacing: float = ..., iterations: int = ..., quanta: Incomplete | None = ...): ...
def images(images, power_resize: bool = ...): ...
