from _typeshed import Incomplete

class _fcycle:
    funcs: Incomplete
    def __init__(self, iterable) -> None: ...
    def __call__(self, *args, **kwargs): ...

def disk_level_set(image_shape, *, center: Incomplete | None = ..., radius: Incomplete | None = ...): ...
def checkerboard_level_set(image_shape, square_size: int = ...): ...
def inverse_gaussian_gradient(image, alpha: float = ..., sigma: float = ...): ...
def morphological_chan_vese(image, num_iter, init_level_set: str = ..., smoothing: int = ..., lambda1: int = ..., lambda2: int = ..., iter_callback=...): ...
def morphological_geodesic_active_contour(gimage, num_iter, init_level_set: str = ..., smoothing: int = ..., threshold: str = ..., balloon: int = ..., iter_callback=...): ...
