from _typeshed import Incomplete

def local_node_connectivity(G, source, target, cutoff: Incomplete | None = ...): ...
def node_connectivity(G, s: Incomplete | None = ..., t: Incomplete | None = ...): ...
def all_pairs_node_connectivity(G, nbunch: Incomplete | None = ..., cutoff: Incomplete | None = ...): ...
