from _typeshed import Incomplete

def randomized_partitioning(G, seed: Incomplete | None = ..., p: float = ..., weight: Incomplete | None = ...): ...
def one_exchange(G, initial_cut: Incomplete | None = ..., seed: Incomplete | None = ..., weight: Incomplete | None = ...): ...
