from networkx.utils import arbitrary_element as arbitrary_element, graphs_equal as graphs_equal

def test_basic_prefix_tree(prefix_tree_fn): ...
def test_implementations_consistent(strings) -> None: ...
def test_random_tree() -> None: ...
