class TestConfigurationModel:
    def test_empty_degree_sequence(self) -> None: ...
    def test_degree_zero(self) -> None: ...
    def test_degree_sequence(self) -> None: ...
    def test_random_seed(self) -> None: ...
    def test_directed_disallowed(self) -> None: ...
    def test_odd_degree_sum(self) -> None: ...

def test_directed_configuation_raise_unequal() -> None: ...
def test_directed_configuation_model() -> None: ...
def test_simple_directed_configuation_model() -> None: ...
def test_expected_degree_graph_empty() -> None: ...
def test_expected_degree_graph() -> None: ...
def test_expected_degree_graph_selfloops() -> None: ...
def test_expected_degree_graph_skew() -> None: ...
def test_havel_hakimi_construction() -> None: ...
def test_directed_havel_hakimi() -> None: ...
def test_degree_sequence_tree() -> None: ...
def test_random_degree_sequence_graph() -> None: ...
def test_random_degree_sequence_graph_raise() -> None: ...
def test_random_degree_sequence_large() -> None: ...
