from networkx.exception import NetworkXError as NetworkXError
from networkx.generators.duplication import duplication_divergence_graph as duplication_divergence_graph, partial_duplication_graph as partial_duplication_graph

class TestDuplicationDivergenceGraph:
    def test_final_size(self) -> None: ...
    def test_probability_too_large(self) -> None: ...
    def test_probability_too_small(self) -> None: ...

class TestPartialDuplicationGraph:
    def test_final_size(self) -> None: ...
    def test_initial_clique_size(self) -> None: ...
    def test_invalid_initial_size(self) -> None: ...
    def test_invalid_probabilities(self) -> None: ...
