from networkx import adjacency_matrix as adjacency_matrix, number_of_nodes as number_of_nodes
from networkx.generators.expanders import chordal_cycle_graph as chordal_cycle_graph, margulis_gabber_galil_graph as margulis_gabber_galil_graph, paley_graph as paley_graph

def test_margulis_gabber_galil_graph() -> None: ...
def test_chordal_cycle_graph() -> None: ...
def test_paley_graph() -> None: ...
def test_margulis_gabber_galil_graph_badinput() -> None: ...
