class TestIntersectionGraph:
    def test_random_intersection_graph(self) -> None: ...
    def test_k_random_intersection_graph(self) -> None: ...
    def test_k_random_intersection_graph_seeded(self) -> None: ...
    def test_general_random_intersection_graph(self) -> None: ...
