from networkx.classes import Graph as Graph, MultiDiGraph as MultiDiGraph
from networkx.generators.directed import gn_graph as gn_graph, gnc_graph as gnc_graph, gnr_graph as gnr_graph, random_k_out_graph as random_k_out_graph, random_uniform_k_out_graph as random_uniform_k_out_graph, scale_free_graph as scale_free_graph

class TestGeneratorsDirected:
    def test_smoke_test_random_graphs(self) -> None: ...
    def test_create_using_keyword_arguments(self) -> None: ...

def test_scale_free_graph_initial_graph_kwarg(ig) -> None: ...

class TestRandomKOutGraph:
    def test_regularity(self) -> None: ...
    def test_no_self_loops(self) -> None: ...

class TestUniformRandomKOutGraph:
    def test_regularity(self) -> None: ...
    def test_no_self_loops(self) -> None: ...
    def test_with_replacement(self) -> None: ...
    def test_without_replacement(self) -> None: ...
