from networkx import graph_atlas as graph_atlas, graph_atlas_g as graph_atlas_g
from networkx.generators.atlas import NUM_GRAPHS as NUM_GRAPHS
from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal, pairwise as pairwise

class TestAtlasGraph:
    def test_index_too_small(self) -> None: ...
    def test_index_too_large(self) -> None: ...
    def test_graph(self) -> None: ...

class TestAtlasGraphG:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_sizes(self) -> None: ...
    def test_names(self) -> None: ...
    def test_nondecreasing_nodes(self) -> None: ...
    def test_nondecreasing_edges(self) -> None: ...
    def test_nondecreasing_degree_sequence(self) -> None: ...
