from networkx.utils import edges_equal as edges_equal

class TestGeneratorNonIsomorphicTrees:
    def test_tree_structure(self): ...
    def test_nonisomorphism(self): ...
    def test_number_of_nonisomorphic_trees(self) -> None: ...
    def test_nonisomorphic_trees(self): ...
    def test_nonisomorphic_trees_matrix(self) -> None: ...
