from networkx.generators.interval_graph import interval_graph as interval_graph
from networkx.utils import edges_equal as edges_equal

class TestIntervalGraph:
    def test_empty(self) -> None: ...
    def test_interval_graph_check_invalid(self) -> None: ...
    def test_interval_graph_0(self) -> None: ...
    def test_interval_graph_1(self) -> None: ...
    def test_interval_graph_2(self) -> None: ...
    def test_interval_graph_3(self) -> None: ...
    def test_interval_graph_4(self) -> None: ...
    def test_interval_graph_5(self) -> None: ...
