class TestStochasticGraph:
    def test_default_weights(self) -> None: ...
    def test_in_place(self) -> None: ...
    def test_arbitrary_weights(self) -> None: ...
    def test_multidigraph(self) -> None: ...
    def test_graph_disallowed(self) -> None: ...
    def test_multigraph_disallowed(self) -> None: ...
