from _typeshed import Incomplete
from networkx.algorithms.isomorphism.isomorph import graph_could_be_isomorphic as graph_could_be_isomorphic

is_isomorphic = graph_could_be_isomorphic
null: Incomplete

class TestGeneratorsSmall:
    def test_make_small_graph(self) -> None: ...
    def test__LCF_graph(self) -> None: ...
    def test_properties_named_small_graphs(self) -> None: ...

def tests_raises_with_directed_create_using(fn, create_using) -> None: ...
