from scipy.sparse import csgraph as csgraph

def test_weak_connections() -> None: ...
def test_strong_connections() -> None: ...
def test_strong_connections2() -> None: ...
def test_weak_connections2() -> None: ...
def test_ticket1876() -> None: ...
def test_fully_connected_graph() -> None: ...
