from _typeshed import Incomplete
from scipy import sparse as sparse
from scipy.sparse import csgraph as csgraph

def check_int_type(mat): ...
def test_laplacian_value_error() -> None: ...
def test_symmetric_graph_laplacian() -> None: ...

INT_DTYPES: Incomplete
REAL_DTYPES: Incomplete
COMPLEX_DTYPES: Incomplete
DTYPES: Incomplete

def test_asymmetric_laplacian(use_out_degree, normed, copy, dtype, arr_type) -> None: ...
def test_sparse_formats(fmt, normed, copy) -> None: ...
def test_laplacian_symmetrized(arr_type, form) -> None: ...
def test_format(dtype, arr_type, normed, symmetrized, use_out_degree, form) -> None: ...
def test_format_error_message() -> None: ...
