from scipy.sparse import coo_matrix as coo_matrix, csc_matrix as csc_matrix, csr_matrix as csr_matrix
from scipy.sparse.csgraph import reverse_cuthill_mckee as reverse_cuthill_mckee, structural_rank as structural_rank

def test_graph_reverse_cuthill_mckee() -> None: ...
def test_graph_reverse_cuthill_mckee_ordering() -> None: ...
def test_graph_structural_rank() -> None: ...
