from scipy.sparse import csr_matrix as csr_matrix
from scipy.sparse.csgraph import csgraph_from_dense as csgraph_from_dense, csgraph_to_dense as csgraph_to_dense

def test_csgraph_from_dense() -> None: ...
def test_csgraph_to_dense() -> None: ...
def test_multiple_edges() -> None: ...
