from _typeshed import Incomplete
from scipy.sparse import csc_matrix as csc_matrix, csr_matrix as csr_matrix
from scipy.sparse.csgraph import maximum_flow as maximum_flow

methods: Incomplete

def test_raises_on_dense_input() -> None: ...
def test_raises_on_csc_input() -> None: ...
def test_raises_on_floating_point_input() -> None: ...
def test_raises_on_non_square_input() -> None: ...
def test_raises_when_source_is_sink() -> None: ...
def test_raises_when_source_is_out_of_bounds(source, method) -> None: ...
def test_raises_when_sink_is_out_of_bounds(sink, method) -> None: ...
def test_simple_graph(method) -> None: ...
def test_bottle_neck_graph(method) -> None: ...
def test_backwards_flow(method) -> None: ...
def test_example_from_clrs_chapter_26_1(method) -> None: ...
def test_disconnected_graph(method) -> None: ...
def test_add_reverse_edges_large_graph(method) -> None: ...
def test_add_reverse_edges(a, b_data_expected) -> None: ...
def test_make_edge_pointers(a, expected) -> None: ...
def test_make_tails(a, expected) -> None: ...
