from networkx.algorithms.traversal.edgedfs import FORWARD as FORWARD, REVERSE as REVERSE

class TestEdgeBFS:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_empty(self) -> None: ...
    def test_graph_single_source(self) -> None: ...
    def test_graph(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_digraph_orientation_invalid(self) -> None: ...
    def test_digraph_orientation_none(self) -> None: ...
    def test_digraph_orientation_original(self) -> None: ...
    def test_digraph2(self) -> None: ...
    def test_digraph_rev(self) -> None: ...
    def test_digraph_rev2(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_multidigraph(self) -> None: ...
    def test_multidigraph_rev(self) -> None: ...
    def test_digraph_ignore(self) -> None: ...
    def test_digraph_ignore2(self) -> None: ...
    def test_multidigraph_ignore(self) -> None: ...
