class TestDFS:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_preorder_nodes(self) -> None: ...
    def test_postorder_nodes(self) -> None: ...
    def test_successor(self) -> None: ...
    def test_predecessor(self) -> None: ...
    def test_dfs_tree(self) -> None: ...
    def test_dfs_edges(self) -> None: ...
    def test_dfs_labeled_edges(self) -> None: ...
    def test_dfs_labeled_disconnected_edges(self) -> None: ...
    def test_dfs_tree_isolates(self) -> None: ...

class TestDepthLimitedSearch:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_dls_preorder_nodes(self) -> None: ...
    def test_dls_postorder_nodes(self) -> None: ...
    def test_dls_successor(self) -> None: ...
    def test_dls_predecessor(self) -> None: ...
    def test_dls_tree(self) -> None: ...
    def test_dls_edges(self) -> None: ...
    def test_dls_labeled_edges(self) -> None: ...
    def test_dls_labeled_disconnected_edges(self) -> None: ...
