class TestBFS:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_successor(self) -> None: ...
    def test_predecessor(self) -> None: ...
    def test_bfs_tree(self) -> None: ...
    def test_bfs_edges(self) -> None: ...
    def test_bfs_edges_reverse(self) -> None: ...
    def test_bfs_edges_sorting(self) -> None: ...
    def test_bfs_tree_isolates(self) -> None: ...
    def test_bfs_layers(self) -> None: ...
    def test_bfs_layers_missing_source(self) -> None: ...
    def test_descendants_at_distance(self) -> None: ...
    def test_descendants_at_distance_missing_source(self) -> None: ...

class TestBreadthLimitedSearch:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_limited_bfs_successor(self) -> None: ...
    def test_limited_bfs_predecessor(self) -> None: ...
    def test_limited_bfs_tree(self) -> None: ...
    def test_limited_bfs_edges(self) -> None: ...
    def test_limited_bfs_layers(self) -> None: ...
    def test_limited_descendants_at_distance(self) -> None: ...
