from _typeshed import Incomplete
from skimage.feature import multiscale_basic_features as multiscale_basic_features

has_sklearn: bool

class NotFittedError(Exception): ...

class TrainableSegmenter:
    clf: Incomplete
    features_func: Incomplete
    def __init__(self, clf: Incomplete | None = ..., features_func: Incomplete | None = ...) -> None: ...
    features: Incomplete
    def compute_features(self, image) -> None: ...
    def fit(self, image, labels) -> None: ...
    def predict(self, image): ...

def fit_segmenter(labels, features, clf): ...
def predict_segmenter(features, clf): ...
