from _typeshed import Incomplete

def katz_centrality(G, alpha: float = ..., beta: float = ..., max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., normalized: bool = ..., weight: Incomplete | None = ...): ...
def katz_centrality_numpy(G, alpha: float = ..., beta: float = ..., normalized: bool = ..., weight: Incomplete | None = ...): ...
