def validate_grid_path(r, c, s, t, p) -> None: ...

class TestUnweightedPath:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_bidirectional_shortest_path(self) -> None: ...
    def test_shortest_path_length(self) -> None: ...
    def test_single_source_shortest_path(self) -> None: ...
    def test_single_source_shortest_path_length(self) -> None: ...
    def test_single_target_shortest_path(self) -> None: ...
    def test_single_target_shortest_path_length(self) -> None: ...
    def test_all_pairs_shortest_path(self) -> None: ...
    def test_all_pairs_shortest_path_length(self) -> None: ...
    def test_predecessor_path(self) -> None: ...
    def test_predecessor_cycle(self) -> None: ...
    def test_predecessor_cutoff(self) -> None: ...
    def test_predecessor_target(self) -> None: ...
