from networkx.utils import pairwise as pairwise

class TestAStar:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_multiple_optimal_paths(self): ...
    def test_astar_directed(self) -> None: ...
    def test_astar_multigraph(self) -> None: ...
    def test_astar_undirected(self) -> None: ...
    def test_astar_directed2(self) -> None: ...
    def test_astar_undirected2(self) -> None: ...
    def test_astar_undirected3(self) -> None: ...
    def test_astar_directed3(self): ...
    def test_astar_directed4(self) -> None: ...
    def test_astar_w1(self) -> None: ...
    def test_astar_nopath(self) -> None: ...
    def test_cycle(self) -> None: ...
    def test_unorderable_nodes(self) -> None: ...
