class TestFloyd:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_floyd_warshall_predecessor_and_distance(self) -> None: ...
    def test_reconstruct_path(self) -> None: ...
    def test_cycle(self) -> None: ...
    def test_weighted(self) -> None: ...
    def test_weighted2(self) -> None: ...
    def test_weight_parameter(self) -> None: ...
    def test_zero_distance(self) -> None: ...
    def test_zero_weight(self) -> None: ...
