from _typeshed import Incomplete

np: Incomplete

def test_cycle_numpy() -> None: ...
def test_weighted_numpy_three_edges() -> None: ...
def test_weighted_numpy_two_edges() -> None: ...
def test_weight_parameter_numpy() -> None: ...
def test_directed_cycle_numpy() -> None: ...
def test_zero_weight() -> None: ...
def test_nodelist() -> None: ...
