class TestIsSemiconnected:
    def test_undirected(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_single_node_graph(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cycle(self) -> None: ...
    def test_tree(self) -> None: ...
    def test_dumbbell(self) -> None: ...
    def test_alternating_path(self) -> None: ...
