from networkx import NetworkXNotImplemented as NetworkXNotImplemented

class TestConnected:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_connected_components(self) -> None: ...
    def test_number_connected_components(self) -> None: ...
    def test_number_connected_components2(self) -> None: ...
    def test_connected_components2(self) -> None: ...
    def test_node_connected_components(self) -> None: ...
    def test_is_connected(self) -> None: ...
    def test_connected_raise(self) -> None: ...
    def test_connected_mutability(self) -> None: ...
