from networkx import NetworkXNotImplemented as NetworkXNotImplemented

class TestAttractingComponents:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_attracting_components(self) -> None: ...
    def test_number_attacting_components(self) -> None: ...
    def test_is_attracting_component(self) -> None: ...
    def test_connected_raise(self) -> None: ...
