from networkx import NetworkXNotImplemented as NetworkXNotImplemented

class TestWeaklyConnected:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_weakly_connected_components(self) -> None: ...
    def test_number_weakly_connected_components(self) -> None: ...
    def test_is_weakly_connected(self) -> None: ...
    def test_null_graph(self) -> None: ...
    def test_connected_raise(self) -> None: ...
    def test_connected_mutability(self) -> None: ...
