from _typeshed import Incomplete
from networkx import NetworkXNotImplemented as NetworkXNotImplemented

class TestStronglyConnected:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_tarjan(self) -> None: ...
    def test_tarjan_recursive(self) -> None: ...
    def test_kosaraju(self) -> None: ...
    def test_number_strongly_connected_components(self) -> None: ...
    def test_is_strongly_connected(self) -> None: ...
    def test_contract_scc1(self) -> None: ...
    def test_contract_scc_isolate(self) -> None: ...
    def test_contract_scc_edge(self) -> None: ...
    def test_condensation_mapping_and_members(self) -> None: ...
    def test_null_graph(self) -> None: ...
    def test_connected_raise(self) -> None: ...
    strong_cc_methods: Incomplete
    def test_connected_mutability(self, get_components) -> None: ...
