from _typeshed import Incomplete

class TestEfficiency:
    G1: Incomplete
    G2: Incomplete
    G3: Incomplete
    def setup_method(self) -> None: ...
    def test_efficiency_disconnected_nodes(self) -> None: ...
    def test_local_efficiency_disconnected_graph(self) -> None: ...
    def test_efficiency(self) -> None: ...
    def test_global_efficiency(self) -> None: ...
    def test_global_efficiency_complete_graph(self) -> None: ...
    def test_local_efficiency_complete_graph(self) -> None: ...
    def test_using_ego_graph(self) -> None: ...
