from networkx.utils import nodes_equal as nodes_equal

class TestCore:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_trivial(self) -> None: ...
    def test_core_number(self) -> None: ...
    def test_core_number2(self) -> None: ...
    def test_directed_core_number(self) -> None: ...
    def test_main_core(self) -> None: ...
    def test_k_core(self) -> None: ...
    def test_main_crust(self) -> None: ...
    def test_k_crust(self) -> None: ...
    def test_main_shell(self) -> None: ...
    def test_k_shell(self) -> None: ...
    def test_k_corona(self) -> None: ...
    def test_k_truss(self) -> None: ...
    def test_onion_layers(self) -> None: ...
