from networkx.algorithms.matching import matching_dict_to_set as matching_dict_to_set
from networkx.utils import edges_equal as edges_equal

class TestMaxWeightMatching:
    def test_trivial1(self) -> None: ...
    def test_selfloop(self) -> None: ...
    def test_single_edge(self) -> None: ...
    def test_two_path(self) -> None: ...
    def test_path(self) -> None: ...
    def test_square(self) -> None: ...
    def test_edge_attribute_name(self) -> None: ...
    def test_floating_point_weights(self) -> None: ...
    def test_negative_weights(self) -> None: ...
    def test_s_blossom(self) -> None: ...
    def test_s_t_blossom(self) -> None: ...
    def test_nested_s_blossom(self) -> None: ...
    def test_nested_s_blossom_relabel(self) -> None: ...
    def test_nested_s_blossom_expand(self) -> None: ...
    def test_s_blossom_relabel_expand(self) -> None: ...
    def test_nested_s_blossom_relabel_expand(self) -> None: ...
    def test_nasty_blossom1(self) -> None: ...
    def test_nasty_blossom2(self) -> None: ...
    def test_nasty_blossom_least_slack(self) -> None: ...
    def test_nasty_blossom_augmenting(self) -> None: ...
    def test_nasty_blossom_expand_recursively(self) -> None: ...
    def test_wrong_graph_type(self) -> None: ...

class TestIsMatching:
    def test_dict(self) -> None: ...
    def test_empty_matching(self) -> None: ...
    def test_single_edge(self) -> None: ...
    def test_edge_order(self) -> None: ...
    def test_valid_matching(self) -> None: ...
    def test_invalid_input(self) -> None: ...
    def test_selfloops(self) -> None: ...
    def test_invalid_matching(self) -> None: ...
    def test_invalid_edge(self) -> None: ...

class TestIsMaximalMatching:
    def test_dict(self) -> None: ...
    def test_valid(self) -> None: ...
    def test_not_matching(self) -> None: ...
    def test_not_maximal(self) -> None: ...

class TestIsPerfectMatching:
    def test_dict(self) -> None: ...
    def test_valid(self) -> None: ...
    def test_valid_not_path(self) -> None: ...
    def test_not_matching(self) -> None: ...
    def test_maximal_but_not_perfect(self) -> None: ...

class TestMaximalMatching:
    def test_valid_matching(self) -> None: ...
    def test_single_edge_matching(self) -> None: ...
    def test_self_loops(self) -> None: ...
    def test_ordering(self) -> None: ...
    def test_wrong_graph_type(self) -> None: ...
