from networkx import DiGraph as DiGraph, complete_graph as complete_graph, empty_graph as empty_graph, path_graph as path_graph, wiener_index as wiener_index

class TestWienerIndex:
    def test_disconnected_graph(self) -> None: ...
    def test_directed(self) -> None: ...
    def test_complete_graph(self) -> None: ...
    def test_path_graph(self) -> None: ...
