class TestClosenessVitality:
    def test_unweighted(self) -> None: ...
    def test_weighted(self) -> None: ...
    def test_unweighted_digraph(self) -> None: ...
    def test_weighted_digraph(self) -> None: ...
    def test_weighted_multidigraph(self) -> None: ...
    def test_disconnecting_graph(self) -> None: ...
