from _typeshed import Incomplete

sympy: Incomplete

def test_tutte_polynomial(G, expected) -> None: ...
def test_tutte_polynomial_disjoint(G) -> None: ...
def test_chromatic_polynomial(G, expected) -> None: ...
def test_chromatic_polynomial_disjoint(G) -> None: ...
