def test_richclub() -> None: ...
def test_richclub_seed() -> None: ...
def test_richclub_normalized() -> None: ...
def test_richclub2() -> None: ...
def test_richclub3() -> None: ...
def test_richclub4() -> None: ...
def test_richclub_exception() -> None: ...
def test_rich_club_exception2() -> None: ...
