from _typeshed import Incomplete

class TestStructuralHoles:
    D: Incomplete
    D_weights: Incomplete
    G: Incomplete
    G_weights: Incomplete
    def setup(self) -> None: ...
    def test_constraint_directed(self) -> None: ...
    def test_effective_size_directed(self) -> None: ...
    def test_constraint_weighted_directed(self) -> None: ...
    def test_effective_size_weighted_directed(self) -> None: ...
    def test_constraint_undirected(self) -> None: ...
    def test_effective_size_undirected_borgatti(self) -> None: ...
    def test_effective_size_undirected(self) -> None: ...
    def test_constraint_weighted_undirected(self) -> None: ...
    def test_effective_size_weighted_undirected(self) -> None: ...
    def test_constraint_isolated(self) -> None: ...
    def test_effective_size_isolated(self) -> None: ...
    def test_effective_size_borgatti_isolated(self) -> None: ...
