class TestTriangles:
    def test_empty(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...

class TestDirectedClustering:
    def test_clustering(self) -> None: ...
    def test_path(self) -> None: ...
    def test_k5(self) -> None: ...
    def test_triangle_and_edge(self) -> None: ...

class TestDirectedWeightedClustering:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_clustering(self) -> None: ...
    def test_path(self) -> None: ...
    def test_k5(self) -> None: ...
    def test_triangle_and_edge(self) -> None: ...

class TestWeightedClustering:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_clustering(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...
    def test_triangle_and_edge(self) -> None: ...
    def test_triangle_and_signed_edge(self) -> None: ...

class TestClustering:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_clustering(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...
    def test_k5_signed(self) -> None: ...

class TestTransitivity:
    def test_transitivity(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...

class TestSquareClustering:
    def test_clustering(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...
    def test_bipartite_k5(self) -> None: ...
    def test_lind_square_clustering(self) -> None: ...
    def test_peng_square_clustering(self) -> None: ...

class TestAverageClustering:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_empty(self) -> None: ...
    def test_average_clustering(self) -> None: ...
    def test_average_clustering_signed(self) -> None: ...

class TestDirectedAverageClustering:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_empty(self) -> None: ...
    def test_average_clustering(self) -> None: ...

class TestGeneralizedDegree:
    def test_generalized_degree(self) -> None: ...
    def test_path(self) -> None: ...
    def test_cubical(self) -> None: ...
    def test_k5(self) -> None: ...
