from networkx.generators import directed as directed

def test_empty_graph_hash() -> None: ...
def test_directed() -> None: ...
def test_reversed() -> None: ...
def test_isomorphic() -> None: ...
def test_isomorphic_edge_attr() -> None: ...
def test_missing_edge_attr() -> None: ...
def test_isomorphic_node_attr() -> None: ...
def test_missing_node_attr() -> None: ...
def test_isomorphic_edge_attr_and_node_attr() -> None: ...
def test_digest_size() -> None: ...
def is_subiteration(a, b): ...
def hexdigest_sizes_correct(a, digest_size): ...
def test_empty_graph_subgraph_hash() -> None: ...
def test_directed_subgraph_hash() -> None: ...
def test_reversed_subgraph_hash() -> None: ...
def test_isomorphic_subgraph_hash() -> None: ...
def test_isomorphic_edge_attr_subgraph_hash() -> None: ...
def test_missing_edge_attr_subgraph_hash() -> None: ...
def test_isomorphic_node_attr_subgraph_hash() -> None: ...
def test_missing_node_attr_subgraph_hash() -> None: ...
def test_isomorphic_edge_attr_and_node_attr_subgraph_hash() -> None: ...
def test_iteration_depth() -> None: ...
def test_iteration_depth_edge_attr() -> None: ...
def test_iteration_depth_node_attr() -> None: ...
def test_iteration_depth_node_edge_attr() -> None: ...
def test_digest_size_subgraph_hash() -> None: ...
