class TestReciprocity:
    def test_reciprocity_digraph(self) -> None: ...
    def test_overall_reciprocity_empty_graph(self) -> None: ...
    def test_reciprocity_graph_nodes(self) -> None: ...
    def test_reciprocity_graph_node(self) -> None: ...
    def test_reciprocity_graph_isolated_nodes(self) -> None: ...
