class TestKFactor:
    def test_k_factor_trivial(self) -> None: ...
    def test_k_factor1(self) -> None: ...
    def test_k_factor2(self) -> None: ...
    def test_k_factor3(self) -> None: ...
    def test_k_factor4(self) -> None: ...
    def test_k_factor5(self) -> None: ...

class TestIsRegular:
    def test_is_regular1(self) -> None: ...
    def test_is_regular2(self) -> None: ...
    def test_is_regular3(self) -> None: ...
    def test_is_regular4(self) -> None: ...

class TestIsKRegular:
    def test_is_k_regular1(self) -> None: ...
    def test_is_k_regular2(self) -> None: ...
    def test_is_k_regular3(self) -> None: ...
