def test_hmn_deprecation_warning() -> None: ...
def test_lgc_deprecation_warning() -> None: ...
def test_no_warn_on_function_import(recwarn) -> None: ...
def test_no_warn_on_package_import(recwarn) -> None: ...
