from _typeshed import Incomplete

class TestCliques:
    G: Incomplete
    cl: Incomplete
    H: Incomplete
    def setup_method(self) -> None: ...
    def test_find_cliques1(self) -> None: ...
    def test_selfloops(self) -> None: ...
    def test_find_cliques2(self) -> None: ...
    def test_find_cliques3(self) -> None: ...
    def test_clique_number(self) -> None: ...
    def test_clique_number2(self) -> None: ...
    def test_clique_number3(self) -> None: ...
    def test_number_of_cliques(self) -> None: ...
    def test_node_clique_number(self) -> None: ...
    def test_cliques_containing_node(self) -> None: ...
    def test_make_clique_bipartite(self) -> None: ...
    def test_make_max_clique_graph(self) -> None: ...
    def test_directed(self) -> None: ...

class TestEnumerateAllCliques:
    def test_paper_figure_4(self) -> None: ...
