from _typeshed import Incomplete

def test_extrema_bounding_deprecated(compute) -> None: ...
def test__extrema_bounding_invalid_compute_kwarg() -> None: ...

class TestDistance:
    G: Incomplete
    def setup_method(self) -> None: ...
    def test_eccentricity(self) -> None: ...
    def test_diameter(self) -> None: ...
    def test_radius(self) -> None: ...
    def test_periphery(self) -> None: ...
    def test_center(self) -> None: ...
    def test_bound_diameter(self) -> None: ...
    def test_bound_radius(self) -> None: ...
    def test_bound_periphery(self) -> None: ...
    def test_bound_center(self) -> None: ...
    def test_radius_exception(self) -> None: ...
    def test_eccentricity_infinite(self) -> None: ...
    def test_eccentricity_undirected_not_connected(self) -> None: ...
    def test_eccentricity_directed_weakly_connected(self) -> None: ...

class TestResistanceDistance:
    @classmethod
    def setup_class(cls) -> None: ...
    G: Incomplete
    def setup_method(self) -> None: ...
    def test_resistance_distance(self) -> None: ...
    def test_resistance_distance_noinv(self) -> None: ...
    def test_resistance_distance_no_weight(self) -> None: ...
    def test_resistance_distance_neg_weight(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_resistance_distance_div0(self) -> None: ...
    def test_resistance_distance_not_connected(self) -> None: ...
    def test_resistance_distance_same_node(self) -> None: ...
    def test_resistance_distance_nodeA_not_in_graph(self) -> None: ...
    def test_resistance_distance_nodeB_not_in_graph(self) -> None: ...

class TestBarycenter:
    def barycenter_as_subgraph(self, g, **kwargs): ...
    def test_must_be_connected(self) -> None: ...
    def test_sp_kwarg(self) -> None: ...
    def test_trees(self) -> None: ...
    def test_this_one_specific_tree(self) -> None: ...
