from _typeshed import Incomplete

class TestMaximumWeightClique:
    def test_basic_cases(self) -> None: ...
    def test_key_error(self) -> None: ...
    def test_error_on_non_integer_weight(self) -> None: ...
    def test_unaffected_by_self_loops(self) -> None: ...
    def test_30_node_prob(self) -> None: ...

def verify_clique(graph, clique, reported_clique_weight, expected_clique_weight, weight_accessor): ...
def empty_graph(): ...
def one_node_graph(): ...
def two_node_graph(): ...
def three_node_clique(): ...
def three_node_independent_set(): ...
def disconnected(): ...

TEST_CASES: Incomplete
