from networkx import lattice_reference as lattice_reference, omega as omega, random_reference as random_reference, sigma as sigma

rng: int

def test_random_reference() -> None: ...
def test_lattice_reference() -> None: ...
def test_sigma() -> None: ...
def test_omega() -> None: ...
