def test_hierarchy_exception() -> None: ...
def test_hierarchy_cycle() -> None: ...
def test_hierarchy_tree() -> None: ...
def test_hierarchy_1() -> None: ...
def test_hierarchy_weight() -> None: ...
