from _typeshed import Incomplete
from collections.abc import Generator

def cycles(seq) -> Generator[Incomplete, None, None]: ...
def cyclic_equals(seq1, seq2): ...

class TestChainDecomposition:
    def assertContainsChain(self, chain, expected) -> None: ...
    def test_decomposition(self) -> None: ...
    def test_barbell_graph(self) -> None: ...
    def test_disconnected_graph(self) -> None: ...
    def test_disconnected_graph_root_node(self) -> None: ...
    def test_chain_decomposition_root_not_in_G(self) -> None: ...
