def test_random_seed() -> None: ...
def test_K5(graph) -> None: ...
def test_exceptions() -> None: ...
def test_florentine_family() -> None: ...
def test_bipartite() -> None: ...
def test_random_graphs() -> None: ...
