from networkx.utils import py_random_state as py_random_state

def test_spanner_trivial() -> None: ...
def test_spanner_unweighted_complete_graph() -> None: ...
def test_spanner_weighted_complete_graph() -> None: ...
def test_spanner_unweighted_gnp_graph() -> None: ...
def test_spanner_weighted_gnp_graph() -> None: ...
def test_spanner_unweighted_disconnected_graph() -> None: ...
def test_spanner_invalid_stretch() -> None: ...
