from networkx.algorithms import node_classification as node_classification

class TestHarmonicFunction:
    def test_path_graph(self) -> None: ...
    def test_no_labels(self) -> None: ...
    def test_no_nodes(self) -> None: ...
    def test_no_edges(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_one_labeled_node(self) -> None: ...
    def test_nodes_all_labeled(self) -> None: ...
    def test_labeled_nodes_are_not_changed(self) -> None: ...

class TestLocalAndGlobalConsistency:
    def test_path_graph(self) -> None: ...
    def test_no_labels(self) -> None: ...
    def test_no_nodes(self) -> None: ...
    def test_no_edges(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_one_labeled_node(self) -> None: ...
    def test_nodes_all_labeled(self) -> None: ...
