class TestMCS:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_is_chordal_not_implemented(self, G) -> None: ...
    def test_is_chordal(self) -> None: ...
    def test_induced_nodes(self) -> None: ...
    def test_graph_treewidth(self) -> None: ...
    def test_chordal_find_cliques(self) -> None: ...
    def test_chordal_find_cliques_path(self) -> None: ...
    def test_chordal_find_cliquesCC(self) -> None: ...
    def test_complete_to_chordal_graph(self) -> None: ...
