from networkx.utils import edges_equal as edges_equal

class TestNodeBoundary:
    def test_null_graph(self) -> None: ...
    def test_path_graph(self) -> None: ...
    def test_complete_graph(self) -> None: ...
    def test_petersen(self): ...
    def test_directed(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_multidigraph(self) -> None: ...

class TestEdgeBoundary:
    def test_null_graph(self) -> None: ...
    def test_path_graph(self) -> None: ...
    def test_complete_graph(self): ...
    def test_directed(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_multidigraph(self) -> None: ...
