class TestBridges:
    def test_single_bridge(self) -> None: ...
    def test_barbell_graph(self) -> None: ...
    def test_multiedge_bridge(self) -> None: ...

class TestHasBridges:
    def test_single_bridge(self) -> None: ...
    def test_has_bridges_raises_root_not_in_G(self) -> None: ...
    def test_multiedge_bridge(self) -> None: ...
    def test_bridges_multiple_components(self) -> None: ...

class TestLocalBridges:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_nospan(self) -> None: ...
    def test_no_weight(self) -> None: ...
    def test_weight(self): ...
