from networkx.algorithms.communicability_alg import communicability as communicability, communicability_exp as communicability_exp

class TestCommunicability:
    def test_communicability(self) -> None: ...
    def test_communicability2(self) -> None: ...
