from .._shared.utils import deprecate_kwarg as deprecate_kwarg
from _typeshed import Incomplete

def flood_fill(image, seed_point, new_value, *, footprint: Incomplete | None = ..., connectivity: Incomplete | None = ..., tolerance: Incomplete | None = ..., in_place: bool = ...): ...
def flood(image, seed_point, *, footprint: Incomplete | None = ..., connectivity: Incomplete | None = ..., tolerance: Incomplete | None = ...): ...
