from .._shared.utils import check_nD as check_nD, deprecate_kwarg as deprecate_kwarg
from ..util import crop as crop, img_as_ubyte as img_as_ubyte
from _typeshed import Incomplete

def skeletonize(image, *, method: Incomplete | None = ...): ...
def skeletonize_2d(image): ...

G123_LUT: Incomplete
G123P_LUT: Incomplete

def thin(image, max_num_iter: Incomplete | None = ...): ...
def medial_axis(image, mask: Incomplete | None = ..., return_distance: bool = ..., *, random_state: Incomplete | None = ...): ...
def skeletonize_3d(image): ...
