from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _fast_skeletonize(*args, **kwargs) -> Any: ...
def _skeletonize_loop(*args, **kwargs) -> Any: ...
def _table_lookup_index(*args, **kwargs) -> Any: ...
