from .._shared.utils import deprecate_kwarg as deprecate_kwarg
from .misc import default_footprint as default_footprint
from _typeshed import Incomplete

def binary_erosion(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def binary_dilation(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def binary_opening(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def binary_closing(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
