from . import grayreconstruct as grayreconstruct
from .._shared.utils import deprecate_kwarg as deprecate_kwarg, warn as warn
from ..util import crop as crop, dtype_limits as dtype_limits, invert as invert
from _typeshed import Incomplete

def h_maxima(image, h, footprint: Incomplete | None = ...): ...
def h_minima(image, h, footprint: Incomplete | None = ...): ...
def local_maxima(image, footprint: Incomplete | None = ..., connectivity: Incomplete | None = ..., indices: bool = ..., allow_borders: bool = ...): ...
def local_minima(image, footprint: Incomplete | None = ..., connectivity: Incomplete | None = ..., indices: bool = ..., allow_borders: bool = ...): ...
