from .. import draw as draw
from .._shared.utils import deprecate_kwarg as deprecate_kwarg

def square(width, dtype=...): ...
def rectangle(nrows, ncols, dtype=...): ...
def diamond(radius, dtype=...): ...
def disk(radius, dtype=...): ...
def ellipse(width, height, dtype=...): ...
def cube(width, dtype=...): ...
def octahedron(radius, dtype=...): ...
def ball(radius, dtype=...): ...
def octagon(m, n, dtype=...): ...
def star(a, dtype=...): ...
