from _typeshed import Incomplete

def erosion(image, footprint: Incomplete | None = ..., out: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ...): ...
def dilation(image, footprint: Incomplete | None = ..., out: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ...): ...
def opening(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def closing(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def white_tophat(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
def black_tophat(image, footprint: Incomplete | None = ..., out: Incomplete | None = ...): ...
