from _typeshed import Incomplete

def cytoscape_data(G, attrs: Incomplete | None = ..., name: str = ..., ident: str = ...): ...
def cytoscape_graph(data, attrs: Incomplete | None = ..., name: str = ..., ident: str = ...): ...
