from _typeshed import Incomplete

def node_link_data(G, attrs: Incomplete | None = ..., *, source: str = ..., target: str = ..., name: str = ..., key: str = ..., link: str = ...): ...
def node_link_graph(data, directed: bool = ..., multigraph: bool = ..., attrs: Incomplete | None = ..., *, source: str = ..., target: str = ..., name: str = ..., key: str = ..., link: str = ...): ...
