from _typeshed import Incomplete

def tree_data(G, root, attrs: Incomplete | None = ..., ident: str = ..., children: str = ...): ...
def tree_graph(data, attrs: Incomplete | None = ..., ident: str = ..., children: str = ...): ...
