from _typeshed import Incomplete

def ufftn(inarray, dim: Incomplete | None = ...): ...
def uifftn(inarray, dim: Incomplete | None = ...): ...
def urfftn(inarray, dim: Incomplete | None = ...): ...
def uirfftn(inarray, dim: Incomplete | None = ..., shape: Incomplete | None = ...): ...
def ufft2(inarray): ...
def uifft2(inarray): ...
def urfft2(inarray): ...
def uirfft2(inarray, shape: Incomplete | None = ...): ...
def image_quad_norm(inarray): ...
def ir2tf(imp_resp, shape, dim: Incomplete | None = ..., is_real: bool = ...): ...
def laplacian(ndim, shape, is_real: bool = ...): ...
