from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.core.indexes.api import MultiIndex as MultiIndex
from pandas.util._exceptions import find_stack_level as find_stack_level

def flex_binary_moment(arg1, arg2, f, pairwise: bool = ...): ...
def zsqrt(x): ...
def prep_binary(arg1, arg2): ...
def maybe_warn_args_and_kwargs(cls, kernel: str, args, kwargs) -> None: ...
