from _typeshed import Incomplete
from pandas import DataFrame as DataFrame, Series as Series
from pandas._libs.tslibs import BaseOffset as BaseOffset, to_offset as to_offset
from pandas._typing import ArrayLike as ArrayLike, Axis as Axis, NDFrameT as NDFrameT, QuantileInterpolation as QuantileInterpolation, WindowingRankType as WindowingRankType
from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.core._numba import executor as executor
from pandas.core.algorithms import factorize as factorize
from pandas.core.apply import ResamplerWindowApply as ResamplerWindowApply
from pandas.core.arrays import ExtensionArray as ExtensionArray
from pandas.core.base import SelectionMixin as SelectionMixin
from pandas.core.dtypes.common import ensure_float64 as ensure_float64, is_bool as is_bool, is_integer as is_integer, is_list_like as is_list_like, is_numeric_dtype as is_numeric_dtype, is_scalar as is_scalar, needs_i8_conversion as needs_i8_conversion
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.core.dtypes.missing import notna as notna
from pandas.core.generic import NDFrame as NDFrame
from pandas.core.groupby.ops import BaseGrouper as BaseGrouper
from pandas.core.indexers.objects import BaseIndexer as BaseIndexer, FixedWindowIndexer as FixedWindowIndexer, GroupbyIndexer as GroupbyIndexer, VariableWindowIndexer as VariableWindowIndexer
from pandas.core.indexes.api import DatetimeIndex as DatetimeIndex, Index as Index, MultiIndex as MultiIndex, PeriodIndex as PeriodIndex, TimedeltaIndex as TimedeltaIndex
from pandas.core.reshape.concat import concat as concat
from pandas.core.util.numba_ import get_jit_arguments as get_jit_arguments, maybe_use_numba as maybe_use_numba
from pandas.core.window.common import flex_binary_moment as flex_binary_moment, maybe_warn_args_and_kwargs as maybe_warn_args_and_kwargs, zsqrt as zsqrt
from pandas.core.window.doc import args_compat as args_compat, create_section_header as create_section_header, kwargs_compat as kwargs_compat, kwargs_numeric_only as kwargs_numeric_only, kwargs_scipy as kwargs_scipy, numba_notes as numba_notes, template_header as template_header, template_returns as template_returns, template_see_also as template_see_also, window_agg_numba_parameters as window_agg_numba_parameters, window_apply_parameters as window_apply_parameters
from pandas.core.window.numba_ import generate_manual_numpy_nan_agg_with_axis as generate_manual_numpy_nan_agg_with_axis, generate_numba_apply_func as generate_numba_apply_func, generate_numba_table_func as generate_numba_table_func
from pandas.errors import DataError as DataError
from pandas.util._decorators import doc as doc
from pandas.util._exceptions import find_stack_level as find_stack_level
from typing import Any, Callable, Hashable

class BaseWindow(SelectionMixin):
    exclusions: frozenset[Hashable]
    obj: Incomplete
    on: Incomplete
    closed: Incomplete
    step: Incomplete
    window: Incomplete
    min_periods: Incomplete
    center: Incomplete
    axis: Incomplete
    method: Incomplete
    def __init__(self, obj: NDFrame, window: Incomplete | None = ..., min_periods: Union[int, None] = ..., center: Union[bool, None] = ..., win_type: Union[str, None] = ..., axis: Axis = ..., on: Union[str, Index, None] = ..., closed: Union[str, None] = ..., step: Union[int, None] = ..., method: str = ..., *, selection: Incomplete | None = ...) -> None: ...
    @property
    def win_type(self): ...
    @property
    def is_datetimelike(self) -> bool: ...
    def validate(self) -> None: ...
    def __getattr__(self, attr: str): ...
    def __iter__(self): ...
    def aggregate(self, func, *args, **kwargs): ...
    agg: Incomplete

class BaseWindowGroupby(BaseWindow):
    def __init__(self, obj: Union[DataFrame, Series], *args, _grouper: BaseGrouper, _as_index: bool = ..., **kwargs) -> None: ...

class Window(BaseWindow):
    def aggregate(self, func, *args, **kwargs): ...
    agg: Incomplete
    def sum(self, numeric_only: bool = ..., *args, **kwargs): ...
    def mean(self, numeric_only: bool = ..., *args, **kwargs): ...
    def var(self, ddof: int = ..., numeric_only: bool = ..., *args, **kwargs): ...
    def std(self, ddof: int = ..., numeric_only: bool = ..., *args, **kwargs): ...

class RollingAndExpandingMixin(BaseWindow):
    def count(self, numeric_only: bool = ...): ...
    def apply(self, func: Callable[..., Any], raw: bool = ..., engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., args: Union[tuple[Any, ...], None] = ..., kwargs: Union[dict[str, Any], None] = ...): ...
    def sum(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def max(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def min(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def mean(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def median(self, numeric_only: bool = ..., engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def std(self, ddof: int = ..., numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def var(self, ddof: int = ..., numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def skew(self, numeric_only: bool = ..., **kwargs): ...
    def sem(self, ddof: int = ..., numeric_only: bool = ..., *args, **kwargs): ...
    def kurt(self, numeric_only: bool = ..., **kwargs): ...
    def quantile(self, quantile: float, interpolation: QuantileInterpolation = ..., numeric_only: bool = ..., **kwargs): ...
    def rank(self, method: WindowingRankType = ..., ascending: bool = ..., pct: bool = ..., numeric_only: bool = ..., **kwargs): ...
    def cov(self, other: Union[DataFrame, Series, None] = ..., pairwise: Union[bool, None] = ..., ddof: int = ..., numeric_only: bool = ..., **kwargs): ...
    def corr(self, other: Union[DataFrame, Series, None] = ..., pairwise: Union[bool, None] = ..., ddof: int = ..., numeric_only: bool = ..., **kwargs): ...

class Rolling(RollingAndExpandingMixin):
    def aggregate(self, func, *args, **kwargs): ...
    agg: Incomplete
    min_periods: int
    def count(self, numeric_only: bool = ...): ...
    def apply(self, func: Callable[..., Any], raw: bool = ..., engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., args: Union[tuple[Any, ...], None] = ..., kwargs: Union[dict[str, Any], None] = ...): ...
    def sum(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def max(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def min(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def mean(self, numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def median(self, numeric_only: bool = ..., engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def std(self, ddof: int = ..., numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def var(self, ddof: int = ..., numeric_only: bool = ..., *args, engine: Union[str, None] = ..., engine_kwargs: Union[dict[str, bool], None] = ..., **kwargs): ...
    def skew(self, numeric_only: bool = ..., **kwargs): ...
    def sem(self, ddof: int = ..., numeric_only: bool = ..., *args, **kwargs): ...
    def kurt(self, numeric_only: bool = ..., **kwargs): ...
    def quantile(self, quantile: float, interpolation: QuantileInterpolation = ..., numeric_only: bool = ..., **kwargs): ...
    def rank(self, method: WindowingRankType = ..., ascending: bool = ..., pct: bool = ..., numeric_only: bool = ..., **kwargs): ...
    def cov(self, other: Union[DataFrame, Series, None] = ..., pairwise: Union[bool, None] = ..., ddof: int = ..., numeric_only: bool = ..., **kwargs): ...
    def corr(self, other: Union[DataFrame, Series, None] = ..., pairwise: Union[bool, None] = ..., ddof: int = ..., numeric_only: bool = ..., **kwargs): ...

class RollingGroupby(BaseWindowGroupby, Rolling): ...
