from _typeshed import Incomplete

def cut_threshold(labels, rag, thresh, in_place: bool = ...): ...
def cut_normalized(labels, rag, thresh: float = ..., num_cuts: int = ..., in_place: bool = ..., max_edge: float = ..., *, random_state: Incomplete | None = ...): ...
def partition_by_cut(cut, rag): ...
def get_min_ncut(ev, d, w, num_cuts): ...
