from _typeshed import Incomplete
from networkx.utils import BinaryHeap as BinaryHeap, PairingHeap as PairingHeap

class X:
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __gt__(self, other): ...
    def __hash__(self): ...

x: Incomplete
data: Incomplete

def test_PairingHeap() -> None: ...
def test_BinaryHeap() -> None: ...
