from networkx.utils.mapped_queue import MappedQueue as MappedQueue

def test_HeapElement_gtlt() -> None: ...
def test_HeapElement_eq() -> None: ...
def test_HeapElement_iter() -> None: ...
def test_HeapElement_getitem() -> None: ...

class TestMappedQueue:
    def setup(self) -> None: ...
    def test_heapify(self) -> None: ...
    def test_init(self) -> None: ...
    def test_len(self) -> None: ...
    def test_siftup_leaf(self) -> None: ...
    def test_siftup_one_child(self) -> None: ...
    def test_siftup_left_child(self) -> None: ...
    def test_siftup_right_child(self) -> None: ...
    def test_siftup_multiple(self) -> None: ...
    def test_siftdown_leaf(self) -> None: ...
    def test_siftdown_single(self) -> None: ...
    def test_siftdown_multiple(self) -> None: ...
    def test_push(self) -> None: ...
    def test_push_duplicate(self) -> None: ...
    def test_pop(self) -> None: ...
    def test_remove_leaf(self) -> None: ...
    def test_remove_root(self) -> None: ...
    def test_update_leaf(self) -> None: ...
    def test_update_root(self) -> None: ...

class TestMappedDict(TestMappedQueue):
    def test_push(self) -> None: ...
    def test_push_duplicate(self) -> None: ...
    def test_update_leaf(self) -> None: ...
    def test_update_root(self) -> None: ...
