from networkx.utils import powerlaw_sequence as powerlaw_sequence, random_weighted_sample as random_weighted_sample, weighted_choice as weighted_choice, zipf_rv as zipf_rv

def test_degree_sequences() -> None: ...
def test_zipf_rv() -> None: ...
def test_random_weighted_sample() -> None: ...
def test_random_weighted_choice() -> None: ...
