from _typeshed import Incomplete
from networkx.utils.decorators import argmap as argmap, not_implemented_for as not_implemented_for, np_random_state as np_random_state, open_file as open_file, preserve_random_state as preserve_random_state, py_random_state as py_random_state, random_state as random_state
from networkx.utils.misc import PythonRandomInterface as PythonRandomInterface

def test_not_implemented_decorator() -> None: ...
def test_not_implemented_decorator_key() -> None: ...
def test_not_implemented_decorator_raise() -> None: ...

class TestOpenFileDecorator:
    text: Incomplete
    fobj: Incomplete
    name: Incomplete
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def write(self, path) -> None: ...
    def read(self, path): ...
    @staticmethod
    def writer_arg0(path) -> None: ...
    def writer_arg1(self, path) -> None: ...
    def writer_arg2default(self, x, path: Incomplete | None = ...) -> None: ...
    def writer_arg4default(self, x, y, other: str = ..., path: Incomplete | None = ..., **kwargs) -> None: ...
    def writer_kwarg(self, **kwargs) -> None: ...
    def test_writer_arg0_str(self) -> None: ...
    def test_writer_arg0_fobj(self) -> None: ...
    def test_writer_arg0_pathlib(self) -> None: ...
    def test_writer_arg1_str(self) -> None: ...
    def test_writer_arg1_fobj(self) -> None: ...
    def test_writer_arg2default_str(self) -> None: ...
    def test_writer_arg2default_fobj(self) -> None: ...
    def test_writer_arg2default_fobj_path_none(self) -> None: ...
    def test_writer_arg4default_fobj(self) -> None: ...
    def test_writer_kwarg_str(self) -> None: ...
    def test_writer_kwarg_fobj(self) -> None: ...
    def test_writer_kwarg_path_none(self) -> None: ...

def test_preserve_random_state() -> None: ...

class TestRandomState:
    @classmethod
    def setup_class(cls) -> None: ...
    def instantiate_np_random_state(self, random_state): ...
    def instantiate_py_random_state(self, random_state): ...
    def test_random_state_None(self) -> None: ...
    def test_random_state_np_random(self) -> None: ...
    def test_random_state_int(self) -> None: ...
    def test_random_state_np_random_RandomState(self) -> None: ...
    def test_random_state_py_random(self) -> None: ...

def test_random_state_string_arg_index() -> None: ...
def test_py_random_state_string_arg_index() -> None: ...
def test_random_state_invalid_arg_index() -> None: ...
def test_py_random_state_invalid_arg_index() -> None: ...

class TestArgmap:
    class ArgmapError(RuntimeError): ...
    def test_trivial_function(self): ...
    def test_trivial_iterator(self) -> None: ...
    def test_contextmanager(self): ...
    def test_tryfinally_generator(self): ...
    def test_actual_vararg(self): ...
    def test_signature_destroying_intermediate_decorator(self): ...
    def test_actual_kwarg(self): ...
    def test_nested_tuple(self): ...
    def test_flatten(self) -> None: ...
    def test_indent(self) -> None: ...
    def test_immediate_raise(self) -> None: ...
