from pandas._typing import JSONSerializable as JSONSerializable
from pandas.compat._optional import VERSIONS as VERSIONS, get_version as get_version, import_optional_dependency as import_optional_dependency

def show_versions(as_json: Union[str, bool] = ...) -> None: ...
def main() -> int: ...
