from _typeshed import Incomplete

def load_gmsh(file_name, gmsh_args: Incomplete | None = ...): ...
def to_volume(mesh, file_name: Incomplete | None = ..., max_element: Incomplete | None = ..., mesher_id: int = ...): ...
