from _typeshed import Incomplete

class MatrixRankWarning(UserWarning): ...

def use_solver(**kwargs) -> None: ...
def spsolve(A, b, permc_spec: Incomplete | None = ..., use_umfpack: bool = ...): ...
def splu(A, permc_spec: Incomplete | None = ..., diag_pivot_thresh: Incomplete | None = ..., relax: Incomplete | None = ..., panel_size: Incomplete | None = ..., options=...): ...
def spilu(A, drop_tol: Incomplete | None = ..., fill_factor: Incomplete | None = ..., drop_rule: Incomplete | None = ..., permc_spec: Incomplete | None = ..., diag_pivot_thresh: Incomplete | None = ..., relax: Incomplete | None = ..., panel_size: Incomplete | None = ..., options: Incomplete | None = ...): ...
def factorized(A): ...
def spsolve_triangular(A, b, lower: bool = ..., overwrite_A: bool = ..., overwrite_b: bool = ..., unit_diagonal: bool = ...): ...
