from networkx.algorithms.tree.decomposition import junction_tree as junction_tree

def test_junction_tree_directed_confounders() -> None: ...
def test_junction_tree_directed_unconnected_nodes() -> None: ...
def test_junction_tree_directed_cascade() -> None: ...
def test_junction_tree_directed_unconnected_edges() -> None: ...
def test_junction_tree_undirected() -> None: ...
