from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class TestJoin:
    def test_empty_sequence(self) -> None: ...
    def test_single(self) -> None: ...
    def test_basic(self) -> None: ...
