from _typeshed import Incomplete

class TestTreeRecognition:
    graph: Incomplete
    multigraph: Incomplete
    @classmethod
    def setup_class(cls) -> None: ...
    def test_null_tree(self) -> None: ...
    def test_null_tree2(self) -> None: ...
    def test_null_forest(self) -> None: ...
    def test_null_forest2(self) -> None: ...
    def test_is_tree(self) -> None: ...
    def test_is_not_tree(self) -> None: ...
    def test_is_forest(self) -> None: ...
    def test_is_not_forest(self) -> None: ...

class TestDirectedTreeRecognition(TestTreeRecognition):
    graph: Incomplete
    multigraph: Incomplete

def test_disconnected_graph() -> None: ...
def test_dag_nontree() -> None: ...
def test_multicycle() -> None: ...
def test_emptybranch() -> None: ...
def test_path() -> None: ...
def test_notbranching1() -> None: ...
def test_notbranching2() -> None: ...
def test_notarborescence1() -> None: ...
def test_notarborescence2() -> None: ...
