from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class TestPruferSequence:
    def test_nontree(self) -> None: ...
    def test_null_graph(self) -> None: ...
    def test_trivial_graph(self) -> None: ...
    def test_bad_integer_labels(self) -> None: ...
    def test_encoding(self) -> None: ...
    def test_decoding(self) -> None: ...
    def test_decoding2(self) -> None: ...
    def test_inverse(self) -> None: ...

class TestNestedTuple:
    def test_nontree(self) -> None: ...
    def test_unknown_root(self) -> None: ...
    def test_encoding(self) -> None: ...
    def test_canonical_form(self) -> None: ...
    def test_decoding(self) -> None: ...
    def test_sensible_relabeling(self) -> None: ...
