import numpy as np
from _typeshed import Incomplete
from pandas._libs.tslibs import Timestamp
from pandas._libs.tslibs.offsets import BaseOffset, Day as Day, to_offset as to_offset
from pandas._typing import npt

def get_period_alias(offset_str: str) -> Union[str, None]: ...
def get_offset(name: str) -> BaseOffset: ...
def infer_freq(index, warn: bool = ...) -> Union[str, None]: ...

class _FrequencyInferer:
    index: Incomplete
    i8values: Incomplete
    warn: Incomplete
    is_monotonic: Incomplete
    def __init__(self, index, warn: bool = ...) -> None: ...
    def deltas(self) -> npt.NDArray[np.int64]: ...
    def deltas_asi8(self) -> npt.NDArray[np.int64]: ...
    def is_unique(self) -> bool: ...
    def is_unique_asi8(self) -> bool: ...
    def get_freq(self) -> Union[str, None]: ...
    def day_deltas(self) -> list[int]: ...
    def hour_deltas(self) -> list[int]: ...
    def fields(self) -> np.ndarray: ...
    def rep_stamp(self) -> Timestamp: ...
    def month_position_check(self) -> Union[str, None]: ...
    def mdiffs(self) -> npt.NDArray[np.int64]: ...
    def ydiffs(self) -> npt.NDArray[np.int64]: ...

class _TimedeltaFrequencyInferer(_FrequencyInferer): ...

def is_subperiod(source, target) -> bool: ...
def is_superperiod(source, target) -> bool: ...
