from _typeshed import Incomplete
from datetime import datetime
from dateutil.relativedelta import FR as FR, MO as MO, SA as SA, SU as SU, TH as TH, TU as TU, WE as WE

def next_monday(dt: datetime) -> datetime: ...
def next_monday_or_tuesday(dt: datetime) -> datetime: ...
def previous_friday(dt: datetime) -> datetime: ...
def sunday_to_monday(dt: datetime) -> datetime: ...
def weekend_to_monday(dt: datetime) -> datetime: ...
def nearest_workday(dt: datetime) -> datetime: ...
def next_workday(dt: datetime) -> datetime: ...
def previous_workday(dt: datetime) -> datetime: ...
def before_nearest_workday(dt: datetime) -> datetime: ...
def after_nearest_workday(dt: datetime) -> datetime: ...

class Holiday:
    name: Incomplete
    year: Incomplete
    month: Incomplete
    day: Incomplete
    offset: Incomplete
    start_date: Incomplete
    end_date: Incomplete
    observance: Incomplete
    days_of_week: Incomplete
    def __init__(self, name, year: Incomplete | None = ..., month: Incomplete | None = ..., day: Incomplete | None = ..., offset: Incomplete | None = ..., observance: Incomplete | None = ..., start_date: Incomplete | None = ..., end_date: Incomplete | None = ..., days_of_week: Incomplete | None = ...) -> None: ...
    def dates(self, start_date, end_date, return_name: bool = ...): ...

def register(cls) -> None: ...
def get_calendar(name): ...

class HolidayCalendarMetaClass(type):
    def __new__(cls, clsname, bases, attrs): ...

class AbstractHolidayCalendar(metaclass=HolidayCalendarMetaClass):
    rules: list[Holiday]
    start_date: Incomplete
    end_date: Incomplete
    name: Incomplete
    def __init__(self, name: Incomplete | None = ..., rules: Incomplete | None = ...) -> None: ...
    def rule_from_name(self, name): ...
    def holidays(self, start: Incomplete | None = ..., end: Incomplete | None = ..., return_name: bool = ...): ...
    @staticmethod
    def merge_class(base, other): ...
    def merge(self, other, inplace: bool = ...): ...

class USFederalHolidayCalendar(AbstractHolidayCalendar):
    rules: Incomplete

def HolidayCalendarFactory(name, base, other, base_class=...): ...
