from _typeshed import Incomplete

def attr_matrix(G, edge_attr: Incomplete | None = ..., node_attr: Incomplete | None = ..., normalized: bool = ..., rc_order: Incomplete | None = ..., dtype: Incomplete | None = ..., order: Incomplete | None = ...): ...
def attr_sparse_matrix(G, edge_attr: Incomplete | None = ..., node_attr: Incomplete | None = ..., normalized: bool = ..., rc_order: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
