from _typeshed import Incomplete

def incidence_matrix(G, nodelist: Incomplete | None = ..., edgelist: Incomplete | None = ..., oriented: bool = ..., weight: Incomplete | None = ...): ...
def adjacency_matrix(G, nodelist: Incomplete | None = ..., dtype: Incomplete | None = ..., weight: str = ...): ...

adj_matrix: Incomplete
