from _typeshed import Incomplete

def laplacian_matrix(G, nodelist: Incomplete | None = ..., weight: str = ...): ...
def normalized_laplacian_matrix(G, nodelist: Incomplete | None = ..., weight: str = ...): ...
def total_spanning_tree_weight(G, weight: Incomplete | None = ...): ...
def directed_laplacian_matrix(G, nodelist: Incomplete | None = ..., weight: str = ..., walk_type: Incomplete | None = ..., alpha: float = ...): ...
def directed_combinatorial_laplacian_matrix(G, nodelist: Incomplete | None = ..., weight: str = ..., walk_type: Incomplete | None = ..., alpha: float = ...): ...
