from _typeshed import Incomplete

def modularity_matrix(G, nodelist: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def directed_modularity_matrix(G, nodelist: Incomplete | None = ..., weight: Incomplete | None = ...): ...
