from _typeshed import Incomplete

def laplacian_spectrum(G, weight: str = ...): ...
def normalized_laplacian_spectrum(G, weight: str = ...): ...
def adjacency_spectrum(G, weight: str = ...): ...
def modularity_spectrum(G): ...
def bethe_hessian_spectrum(G, r: Incomplete | None = ...): ...
