import numpy as np
from _typeshed import Incomplete

class SparseWarning(Warning): ...
class SparseFormatWarning(SparseWarning): ...
class SparseEfficiencyWarning(SparseWarning): ...

class _spbase:
    __array_priority__: float
    ndim: int
    maxprint: Incomplete
    def __init__(self, maxprint=...) -> None: ...
    def reshape(self, *args, **kwargs): ...
    def resize(self, shape) -> None: ...
    def astype(self, dtype, casting: str = ..., copy: bool = ...): ...
    def __iter__(self): ...
    def count_nonzero(self) -> None: ...
    @property
    def nnz(self): ...
    @property
    def format(self): ...
    def __bool__(self) -> bool: ...
    __nonzero__: Incomplete
    def __len__(self) -> int: ...
    def asformat(self, format, copy: bool = ...): ...
    def multiply(self, other): ...
    def maximum(self, other): ...
    def minimum(self, other): ...
    def dot(self, other): ...
    def power(self, n, dtype: Incomplete | None = ...): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __abs__(self): ...
    def __round__(self, ndigits: int = ...): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, *args, **kwargs): ...
    def __rmul__(self, *args, **kwargs): ...
    def __matmul__(self, other): ...
    def __rmatmul__(self, other): ...
    def __truediv__(self, other): ...
    def __div__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rdiv__(self, other): ...
    def __neg__(self): ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __imul__(self, other): ...
    def __idiv__(self, other): ...
    def __itruediv__(self, other): ...
    def __pow__(self, *args, **kwargs): ...
    @property
    def A(self) -> np.ndarray: ...
    @property
    def T(self): ...
    @property
    def H(self): ...
    @property
    def real(self): ...
    @property
    def imag(self): ...
    @property
    def size(self): ...
    def transpose(self, axes: Incomplete | None = ..., copy: bool = ...): ...
    def conjugate(self, copy: bool = ...): ...
    def conj(self, copy: bool = ...): ...
    def nonzero(self): ...
    def todense(self, order: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def toarray(self, order: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def tocsr(self, copy: bool = ...): ...
    def todok(self, copy: bool = ...): ...
    def tocoo(self, copy: bool = ...): ...
    def tolil(self, copy: bool = ...): ...
    def todia(self, copy: bool = ...): ...
    def tobsr(self, blocksize: Incomplete | None = ..., copy: bool = ...): ...
    def tocsc(self, copy: bool = ...): ...
    def copy(self): ...
    def sum(self, axis: Incomplete | None = ..., dtype: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def mean(self, axis: Incomplete | None = ..., dtype: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def diagonal(self, k: int = ...): ...
    def trace(self, offset: int = ...): ...
    def setdiag(self, values, k: int = ...) -> None: ...
    def get_shape(self): ...
    __dict__: Incomplete
    def set_shape(self, shape) -> None: ...
    shape: Incomplete
    def asfptype(self): ...
    def getmaxprint(self): ...
    def getformat(self): ...
    def getnnz(self, axis: Incomplete | None = ...): ...
    def getH(self): ...
    def getcol(self, j): ...
    def getrow(self, i): ...

class sparray: ...

def issparse(x): ...
def isspmatrix(x): ...
