from ._base import SparseEfficiencyWarning as SparseEfficiencyWarning, issparse as issparse
from ._data import _data_matrix, _minmax_mixin
from ._index import IndexMixin as IndexMixin
from ._sparsetools import csr_column_index1 as csr_column_index1, csr_column_index2 as csr_column_index2, csr_row_index as csr_row_index, csr_row_slice as csr_row_slice, csr_sample_offsets as csr_sample_offsets, csr_sample_values as csr_sample_values, csr_todense as csr_todense, get_csr_submatrix as get_csr_submatrix
from ._sputils import check_shape as check_shape, downcast_intp_index as downcast_intp_index, get_sum_dtype as get_sum_dtype, getdtype as getdtype, is_pydata_spmatrix as is_pydata_spmatrix, isdense as isdense, isintlike as isintlike, isscalarlike as isscalarlike, isshape as isshape, to_native as to_native, upcast as upcast, upcast_char as upcast_char
from _typeshed import Incomplete

class _cs_matrix(_data_matrix, _minmax_mixin, IndexMixin):
    data: Incomplete
    indices: Incomplete
    indptr: Incomplete
    def __init__(self, arg1, shape: Incomplete | None = ..., dtype: Incomplete | None = ..., copy: bool = ...) -> None: ...
    def check_format(self, full_check: bool = ...) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def multiply(self, other): ...
    def diagonal(self, k: int = ...): ...
    def maximum(self, other): ...
    def minimum(self, other): ...
    def sum(self, axis: Incomplete | None = ..., dtype: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def tocoo(self, copy: bool = ...): ...
    def toarray(self, order: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def eliminate_zeros(self) -> None: ...
    has_canonical_format: Incomplete
    def sum_duplicates(self) -> None: ...
    has_sorted_indices: Incomplete
    def sorted_indices(self): ...
    def sort_indices(self) -> None: ...
    def prune(self) -> None: ...
    def resize(self, *shape) -> None: ...
