from _typeshed import Incomplete

def spdiags(data, diags, m: Incomplete | None = ..., n: Incomplete | None = ..., format: Incomplete | None = ...): ...
def diags(diagonals, offsets: int = ..., shape: Incomplete | None = ..., format: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
def identity(n, dtype: str = ..., format: Incomplete | None = ...): ...
def eye(m, n: Incomplete | None = ..., k: int = ..., dtype=..., format: Incomplete | None = ...): ...
def kron(A, B, format: Incomplete | None = ...): ...
def kronsum(A, B, format: Incomplete | None = ...): ...
def hstack(blocks, format: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
def vstack(blocks, format: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
def bmat(blocks, format: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
def block_diag(mats, format: Incomplete | None = ..., dtype: Incomplete | None = ...): ...
def random(m, n, density: float = ..., format: str = ..., dtype: Incomplete | None = ..., random_state: Incomplete | None = ..., data_rvs: Incomplete | None = ...): ...
def rand(m, n, density: float = ..., format: str = ..., dtype: Incomplete | None = ..., random_state: Incomplete | None = ...): ...
