from ._base import sparray
from ._compressed import _cs_matrix
from ._matrix import spmatrix
from _typeshed import Incomplete

class _csr_base(_cs_matrix):
    def transpose(self, axes: Incomplete | None = ..., copy: bool = ...): ...
    def tolil(self, copy: bool = ...): ...
    def tocsr(self, copy: bool = ...): ...
    def tocsc(self, copy: bool = ...): ...
    def tobsr(self, blocksize: Incomplete | None = ..., copy: bool = ...): ...
    def __iter__(self): ...

def isspmatrix_csr(x): ...

class csr_array(_csr_base, sparray): ...
class csr_matrix(spmatrix, _csr_base): ...
