from ._base import _spbase
from ._sputils import isscalarlike as isscalarlike, validateaxis as validateaxis
from _typeshed import Incomplete

class _data_matrix(_spbase):
    def __init__(self) -> None: ...
    dtype: Incomplete
    def __abs__(self): ...
    def __round__(self, ndigits: int = ...): ...
    def __neg__(self): ...
    def __imul__(self, other): ...
    def __itruediv__(self, other): ...
    def astype(self, dtype, casting: str = ..., copy: bool = ...): ...
    def conjugate(self, copy: bool = ...): ...
    def copy(self): ...
    def count_nonzero(self): ...
    def power(self, n, dtype: Incomplete | None = ...): ...

name: Incomplete

class _minmax_mixin:
    def max(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def min(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def nanmax(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def nanmin(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def argmax(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
    def argmin(self, axis: Incomplete | None = ..., out: Incomplete | None = ...): ...
