import numpy as np
from _typeshed import Incomplete

def upcast(*args): ...
def getdtype(dtype, a: Incomplete | None = ..., default: Incomplete | None = ...): ...
def getdata(obj, dtype: Incomplete | None = ..., copy: bool = ...) -> np.ndarray: ...
def get_sum_dtype(dtype): ...
def isscalarlike(x) -> bool: ...
def isintlike(x) -> bool: ...
def isshape(x, nonneg: bool = ..., allow_ndim: bool = ...) -> bool: ...
def issequence(t) -> bool: ...
def ismatrix(t) -> bool: ...
def isdense(x) -> bool: ...
