# Names in __all__ with no definition:
#   bsr_matmat
#   bsr_matrix
#   bsr_matvec
#   bsr_matvecs
#   bsr_sort_indices
#   bsr_tocsr
#   bsr_transpose
#   check_shape
#   csr_matmat_maxnnz
#   get_index_dtype
#   getdata
#   getdtype
#   isshape
#   isspmatrix
#   isspmatrix_bsr
#   spmatrix
#   to_native
#   upcast
#   warn
