# Names in __all__ with no definition:
#   IndexMixin
#   SparseEfficiencyWarning
#   check_shape
#   csr_column_index1
#   csr_column_index2
#   csr_row_index
#   csr_row_slice
#   csr_sample_offsets
#   csr_sample_values
#   csr_todense
#   downcast_intp_index
#   get_csr_submatrix
#   get_index_dtype
#   get_sum_dtype
#   getdtype
#   is_pydata_spmatrix
#   isdense
#   isintlike
#   isscalarlike
#   isshape
#   isspmatrix
#   operator
#   spmatrix
#   to_native
#   upcast
#   upcast_char
#   warn
