# Names in __all__ with no definition:
#   SparseEfficiencyWarning
#   check_reshape_kwargs
#   check_shape
#   coo_matrix
#   coo_matvec
#   coo_tocsr
#   coo_todense
#   downcast_intp_index
#   get_index_dtype
#   getdata
#   getdtype
#   isshape
#   isspmatrix
#   isspmatrix_coo
#   operator
#   spmatrix
#   to_native
#   upcast
#   upcast_char
#   warn
