# Names in __all__ with no definition:
#   asmatrix
#   check_reshape_kwargs
#   check_shape
#   downcast_intp_index
#   get_index_dtype
#   get_sum_dtype
#   getdata
#   getdtype
#   is_pydata_spmatrix
#   isdense
#   isintlike
#   ismatrix
#   isscalarlike
#   issequence
#   isshape
#   matrix
#   operator
#   prod
#   supported_dtypes
#   sys
#   to_native
#   upcast
#   upcast_char
#   upcast_scalar
#   validateaxis
