from typing import Literal

def assert_produces_warning(expected_warning: Union[type[Warning], bool, tuple[type[Warning], ...], None] = ..., filter_level: Literal['error', 'ignore', 'always', 'default', 'module', 'once'] = ..., check_stacklevel: bool = ..., raise_on_extra_warnings: bool = ..., match: Union[str, None] = ...): ...
def maybe_produces_warning(warning: type[Warning], condition: bool, **kwargs): ...
