from _typeshed import Incomplete
from pandas import set_option as set_option
from pandas.io.common import get_handle as get_handle
from typing import Any, IO, Iterator

def decompress_file(path, compression) -> Iterator[IO[bytes]]: ...
def set_timezone(tz: str) -> Iterator[None]: ...
def ensure_clean(filename: Incomplete | None = ..., return_filelike: bool = ..., **kwargs: Any): ...
def ensure_clean_dir() -> Iterator[str]: ...
def ensure_safe_environment_variables() -> Iterator[None]: ...
def with_csv_dialect(name, **kwargs) -> Iterator[None]: ...
def use_numexpr(use, min_elements: Incomplete | None = ...) -> Iterator[None]: ...

class RNGContext:
    seed: Incomplete
    def __init__(self, seed) -> None: ...
    start_state: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
