from networkx.algorithms.connectivity import EdgeComponentAuxGraph as EdgeComponentAuxGraph, bridge_components as bridge_components
from networkx.algorithms.connectivity.edge_kcomponents import general_k_edge_subgraphs as general_k_edge_subgraphs
from networkx.utils import pairwise as pairwise

def fset(list_of_sets): ...
def test_zero_k_exception() -> None: ...
def test_empty_input() -> None: ...
def test_not_implemented() -> None: ...
def test_general_k_edge_subgraph_quick_return() -> None: ...
def test_random_gnp() -> None: ...
def test_configuration() -> None: ...
def test_shell() -> None: ...
def test_karate() -> None: ...
def test_tarjan_bridge() -> None: ...
def test_bridge_cc() -> None: ...
def test_undirected_aux_graph() -> None: ...
def test_local_subgraph_difference() -> None: ...
def test_local_subgraph_difference_directed() -> None: ...
def test_triangles() -> None: ...
def test_four_clique() -> None: ...
def test_five_clique() -> None: ...
def test_directed_aux_graph() -> None: ...
def test_random_gnp_directed() -> None: ...
def test_configuration_directed() -> None: ...
def test_shell_directed() -> None: ...
def test_karate_directed() -> None: ...
