from _typeshed import Incomplete
from networkx.algorithms import flow as flow

MAX_CUTSETS_TO_TEST: int
flow_funcs: Incomplete

def graph_example_1(): ...
def torrents_and_ferraro_graph(): ...
def test_torrents_and_ferraro_graph() -> None: ...
def test_example_1() -> None: ...
def test_random_gnp() -> None: ...
def test_shell() -> None: ...
def test_configuration() -> None: ...
def test_karate() -> None: ...
def test_articulation_points() -> None: ...
def test_grid_2d_graph() -> None: ...
def test_disconnected_graph() -> None: ...
def test_alternative_flow_functions() -> None: ...
def test_is_separating_set_complete_graph() -> None: ...
def test_is_separating_set() -> None: ...
def test_non_repeated_cuts() -> None: ...
def test_cycle_graph() -> None: ...
def test_complete_graph() -> None: ...
