from networkx.algorithms.connectivity.kcomponents import build_k_number_dict as build_k_number_dict

def torrents_and_ferraro_graph(): ...
def test_directed() -> None: ...
def test_torrents_and_ferraro_graph() -> None: ...
def test_random_gnp() -> None: ...
def test_shell() -> None: ...
def test_configuration() -> None: ...
def test_karate() -> None: ...
def test_karate_component_number() -> None: ...
def test_davis_southern_women() -> None: ...
def test_davis_southern_women_detail_3_and_4() -> None: ...
def test_set_consolidation_rosettacode() -> None: ...
