from _typeshed import Incomplete
from networkx.classes.reportviews import NodeDataView as NodeDataView

class TestNodeView:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pickle(self) -> None: ...
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_call(self) -> None: ...

class TestNodeDataView:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_viewtype(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_iter(self) -> None: ...

def test_nodedataview_unhashable() -> None: ...

class TestNodeViewSetOps:
    @classmethod
    def setup_class(cls) -> None: ...
    def n_its(self, nodes): ...
    def test_len(self) -> None: ...
    def test_and(self) -> None: ...
    def test_or(self) -> None: ...
    def test_xor(self) -> None: ...
    def test_sub(self) -> None: ...

class TestNodeDataViewSetOps(TestNodeViewSetOps):
    @classmethod
    def setup_class(cls) -> None: ...
    def n_its(self, nodes): ...

class TestNodeDataViewDefaultSetOps(TestNodeDataViewSetOps):
    @classmethod
    def setup_class(cls) -> None: ...
    def n_its(self, nodes): ...

class TestEdgeDataView:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pickle(self) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_iterdata(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...
    def test_len(self) -> None: ...

class TestOutEdgeDataView(TestEdgeDataView):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_repr(self) -> None: ...
    def test_len(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestInEdgeDataView(TestOutEdgeDataView):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestMultiEdgeDataView(TestEdgeDataView):
    @classmethod
    def setup_class(cls) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestOutMultiEdgeDataView(TestOutEdgeDataView):
    @classmethod
    def setup_class(cls) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestInMultiEdgeDataView(TestOutMultiEdgeDataView):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestEdgeView:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pickle(self) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_call(self) -> None: ...
    def test_data(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...
    def test_len(self) -> None: ...
    def test_and(self) -> None: ...
    def test_or(self) -> None: ...
    def test_xor(self) -> None: ...
    def test_sub(self) -> None: ...

class TestOutEdgeView(TestEdgeView):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestInEdgeView(TestEdgeView):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestMultiEdgeView(TestEdgeView):
    @classmethod
    def setup_class(cls) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_str(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_call(self) -> None: ...
    def test_data(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_iterkeys(self) -> None: ...
    def test_or(self) -> None: ...
    def test_sub(self) -> None: ...
    def test_xor(self) -> None: ...
    def test_and(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestOutMultiEdgeView(TestMultiEdgeView):
    @classmethod
    def setup_class(cls) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestInMultiEdgeView(TestMultiEdgeView):
    @classmethod
    def setup_class(cls) -> None: ...
    def modify_edge(self, G, e, **kwds) -> None: ...
    def test_repr(self) -> None: ...
    def test_contains_with_nbunch(self) -> None: ...

class TestDegreeView:
    GRAPH: Incomplete
    dview: Incomplete
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pickle(self) -> None: ...
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...
    def test_len(self) -> None: ...

class TestDiDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_repr(self) -> None: ...

class TestOutDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...

class TestInDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...

class TestMultiDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...

class TestDiMultiDegreeView(TestMultiDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_repr(self) -> None: ...

class TestOutMultiDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...

class TestInMultiDegreeView(TestDegreeView):
    GRAPH: Incomplete
    dview: Incomplete
    def test_str(self) -> None: ...
    def test_repr(self) -> None: ...
    def test_nbunch(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_weight(self) -> None: ...

def test_slicing_reportviews(reportview, err_msg_terms) -> None: ...
def test_cache_dict_get_set_state(graph) -> None: ...
