class TestFilterFactory:
    def test_no_filter(self) -> None: ...
    def test_hide_nodes(self) -> None: ...
    def test_show_nodes(self) -> None: ...
    def test_hide_edges(self) -> None: ...
    def test_show_edges(self) -> None: ...
    def test_hide_diedges(self) -> None: ...
    def test_show_diedges(self) -> None: ...
    def test_hide_multiedges(self) -> None: ...
    def test_show_multiedges(self) -> None: ...
    def test_hide_multidiedges(self) -> None: ...
    def test_show_multidiedges(self) -> None: ...
