from .historical_tests import HistoricalTests as HistoricalTests

class TestDiGraphHistorical(HistoricalTests):
    @classmethod
    def setup_class(cls) -> None: ...
    def test_in_degree(self) -> None: ...
    def test_out_degree(self) -> None: ...
    def test_degree_digraph(self) -> None: ...
    def test_neighbors(self) -> None: ...
    def test_successors(self) -> None: ...
    def test_predecessors(self) -> None: ...
    def test_reverse(self) -> None: ...
    def test_reverse2(self) -> None: ...
    def test_reverse3(self) -> None: ...
