class TestOrdered:
    def test_graph(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_multigraph(self) -> None: ...
    def test_multidigraph(self) -> None: ...

class TestOrderedFeatures:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_subgraph_order(self) -> None: ...
