from _typeshed import Incomplete
from networkx.utils import edges_equal as edges_equal, graphs_equal as graphs_equal, nodes_equal as nodes_equal

class BaseGraphTester:
    def test_contains(self) -> None: ...
    def test_order(self) -> None: ...
    def test_nodes(self) -> None: ...
    def test_none_node(self) -> None: ...
    def test_has_node(self) -> None: ...
    def test_has_edge(self) -> None: ...
    def test_neighbors(self) -> None: ...
    def test_memory_leak(self): ...
    def test_edges(self) -> None: ...
    def test_degree(self) -> None: ...
    def test_size(self) -> None: ...
    def test_nbunch_iter(self) -> None: ...
    def test_nbunch_iter_node_format_raise(self) -> None: ...
    def test_selfloop_degree(self) -> None: ...
    def test_selfloops(self) -> None: ...
    def test_cache_reset(self) -> None: ...
    def test_attributes_cached(self) -> None: ...

class BaseAttrGraphTester(BaseGraphTester):
    def test_weighted_degree(self) -> None: ...
    def add_attributes(self, G) -> None: ...
    def test_name(self) -> None: ...
    def test_str_unnamed(self) -> None: ...
    def test_str_named(self) -> None: ...
    def test_graph_chain(self) -> None: ...
    def test_copy(self) -> None: ...
    def test_class_copy(self) -> None: ...
    def test_fresh_copy(self) -> None: ...
    def is_deepcopy(self, H, G) -> None: ...
    def deep_copy_attrdict(self, H, G) -> None: ...
    def deepcopy_graph_attr(self, H, G) -> None: ...
    def deepcopy_node_attr(self, H, G) -> None: ...
    def deepcopy_edge_attr(self, H, G) -> None: ...
    def is_shallow_copy(self, H, G) -> None: ...
    def shallow_copy_attrdict(self, H, G) -> None: ...
    def shallow_copy_graph_attr(self, H, G) -> None: ...
    def shallow_copy_node_attr(self, H, G) -> None: ...
    def shallow_copy_edge_attr(self, H, G) -> None: ...
    def same_attrdict(self, H, G) -> None: ...
    def different_attrdict(self, H, G) -> None: ...
    def graphs_equal(self, H, G) -> None: ...
    def test_graph_attr(self) -> None: ...
    def test_node_attr(self) -> None: ...
    def test_node_attr2(self) -> None: ...
    def test_edge_lookup(self) -> None: ...
    def test_edge_attr(self) -> None: ...
    def test_edge_attr2(self) -> None: ...
    def test_edge_attr3(self) -> None: ...
    def test_edge_attr4(self) -> None: ...
    def test_to_undirected(self) -> None: ...
    def test_to_directed_as_view(self) -> None: ...
    def test_to_undirected_as_view(self) -> None: ...
    def test_directed_class(self): ...
    def test_to_directed(self) -> None: ...
    def test_subgraph(self) -> None: ...
    def test_selfloops_attr(self) -> None: ...

class TestGraph(BaseAttrGraphTester):
    Graph: Incomplete
    k3adj: Incomplete
    k3edges: Incomplete
    k3nodes: Incomplete
    K3: Incomplete
    def setup_method(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_data_input(self) -> None: ...
    def test_adjacency(self) -> None: ...
    def test_getitem(self) -> None: ...
    def test_add_node(self) -> None: ...
    def test_add_nodes_from(self) -> None: ...
    def test_remove_node(self) -> None: ...
    def test_remove_nodes_from(self) -> None: ...
    def test_add_edge(self) -> None: ...
    def test_add_edges_from(self) -> None: ...
    def test_remove_edge(self) -> None: ...
    def test_remove_edges_from(self) -> None: ...
    def test_clear(self) -> None: ...
    def test_clear_edges(self) -> None: ...
    def test_edges_data(self) -> None: ...
    def test_get_edge_data(self) -> None: ...
    def test_update(self) -> None: ...

class TestEdgeSubgraph:
    G: Incomplete
    H: Incomplete
    def setup_method(self) -> None: ...
    def test_correct_nodes(self) -> None: ...
    def test_correct_edges(self) -> None: ...
    def test_add_node(self) -> None: ...
    def test_remove_node(self) -> None: ...
    def test_node_attr_dict(self) -> None: ...
    def test_edge_attr_dict(self) -> None: ...
    def test_graph_attr_dict(self) -> None: ...
