from .test_graph import BaseAttrGraphTester as BaseAttrGraphTester, BaseGraphTester as BaseGraphTester, TestEdgeSubgraph as _TestGraphEdgeSubgraph, TestGraph as _TestGraph
from _typeshed import Incomplete
from networkx.utils import nodes_equal as nodes_equal

class BaseDiGraphTester(BaseGraphTester):
    def test_has_successor(self) -> None: ...
    def test_successors(self) -> None: ...
    def test_has_predecessor(self) -> None: ...
    def test_predecessors(self) -> None: ...
    def test_edges(self) -> None: ...
    def test_out_edges(self) -> None: ...
    def test_out_edges_dir(self) -> None: ...
    def test_out_edges_data(self) -> None: ...
    def test_in_edges_dir(self) -> None: ...
    def test_in_edges_data(self) -> None: ...
    def test_degree(self) -> None: ...
    def test_in_degree(self) -> None: ...
    def test_out_degree(self) -> None: ...
    def test_size(self) -> None: ...
    def test_to_undirected_reciprocal(self) -> None: ...
    def test_reverse_copy(self) -> None: ...
    def test_reverse_nocopy(self) -> None: ...
    def test_reverse_hashable(self) -> None: ...
    def test_di_cache_reset(self) -> None: ...
    def test_di_attributes_cached(self) -> None: ...

class BaseAttrDiGraphTester(BaseDiGraphTester, BaseAttrGraphTester):
    def test_edges_data(self) -> None: ...
    def test_in_degree_weighted(self) -> None: ...
    def test_out_degree_weighted(self) -> None: ...

class TestDiGraph(BaseAttrDiGraphTester, _TestGraph):
    Graph: Incomplete
    k3adj: Incomplete
    k3edges: Incomplete
    k3nodes: Incomplete
    K3: Incomplete
    P3: Incomplete
    def setup_method(self) -> None: ...
    def test_data_input(self) -> None: ...
    def test_add_edge(self) -> None: ...
    def test_add_edges_from(self) -> None: ...
    def test_remove_edge(self) -> None: ...
    def test_remove_edges_from(self) -> None: ...
    def test_clear(self) -> None: ...
    def test_clear_edges(self) -> None: ...

class TestEdgeSubgraph(_TestGraphEdgeSubgraph):
    G: Incomplete
    H: Incomplete
    def setup_method(self) -> None: ...
    def test_pred_succ(self) -> None: ...
