from _typeshed import Incomplete
from networkx.utils import edges_equal as edges_equal, nodes_equal as nodes_equal

class TestReverseView:
    G: Incomplete
    rv: Incomplete
    def setup(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_exceptions(self) -> None: ...
    def test_subclass(self): ...

class TestMultiReverseView:
    G: Incomplete
    rv: Incomplete
    def setup(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_iter(self) -> None: ...
    def test_exceptions(self) -> None: ...

def test_generic_multitype() -> None: ...

class TestToDirected:
    G: Incomplete
    dv: Incomplete
    MG: Incomplete
    Mdv: Incomplete
    def setup(self) -> None: ...
    def test_directed(self) -> None: ...
    def test_already_directed(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_iter(self) -> None: ...

class TestToUndirected:
    DG: Incomplete
    uv: Incomplete
    MDG: Incomplete
    Muv: Incomplete
    def setup(self) -> None: ...
    def test_directed(self) -> None: ...
    def test_already_directed(self) -> None: ...
    def test_pickle(self) -> None: ...
    def test_contains(self) -> None: ...
    def test_iter(self) -> None: ...

class TestChainsOfViews:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_pickle(self) -> None: ...
    def test_subgraph_of_subgraph(self) -> None: ...
    def test_restricted_induced_subgraph_chains(self) -> None: ...
    def test_subgraph_copy(self) -> None: ...
    def test_subgraph_todirected(self) -> None: ...
    def test_subgraph_toundirected(self) -> None: ...
    def test_reverse_subgraph_toundirected(self) -> None: ...
    def test_reverse_reverse_copy(self) -> None: ...
    def test_subgraph_edgesubgraph_toundirected(self) -> None: ...
    def test_copy_subgraph(self) -> None: ...
    def test_copy_disubgraph(self) -> None: ...
    def test_copy_multidisubgraph(self) -> None: ...
    def test_copy_multisubgraph(self) -> None: ...
    def test_copy_of_view(self) -> None: ...
    def test_subclass(self): ...
