class TestNeighborConnectivity:
    def test_degree_p4(self) -> None: ...
    def test_degree_p4_weighted(self) -> None: ...
    def test_weight_keyword(self) -> None: ...
    def test_degree_barrat(self) -> None: ...
    def test_zero_deg(self) -> None: ...
    def test_in_out_weight(self) -> None: ...
    def test_invalid_source(self) -> None: ...
    def test_invalid_target(self) -> None: ...
    def test_invalid_undirected_graph(self) -> None: ...
    def test_single_node(self) -> None: ...
