class TestAverageNeighbor:
    def test_degree_p4(self) -> None: ...
    def test_degree_p4_weighted(self) -> None: ...
    def test_degree_k4(self) -> None: ...
    def test_degree_k4_nodes(self) -> None: ...
    def test_degree_barrat(self) -> None: ...
    def test_error_invalid_source_target(self) -> None: ...
