from .base_test import BaseTestAttributeMixing as BaseTestAttributeMixing, BaseTestDegreeMixing as BaseTestDegreeMixing

class TestAttributeMixingXY(BaseTestAttributeMixing):
    def test_node_attribute_xy_undirected(self) -> None: ...
    def test_node_attribute_xy_undirected_nodes(self) -> None: ...
    def test_node_attribute_xy_directed(self) -> None: ...
    def test_node_attribute_xy_multigraph(self) -> None: ...
    def test_node_attribute_xy_selfloop(self) -> None: ...

class TestDegreeMixingXY(BaseTestDegreeMixing):
    def test_node_degree_xy_undirected(self) -> None: ...
    def test_node_degree_xy_undirected_nodes(self) -> None: ...
    def test_node_degree_xy_directed(self) -> None: ...
    def test_node_degree_xy_multigraph(self) -> None: ...
    def test_node_degree_xy_selfloop(self) -> None: ...
    def test_node_degree_xy_weighted(self) -> None: ...
