from .base_test import BaseTestAttributeMixing as BaseTestAttributeMixing, BaseTestDegreeMixing as BaseTestDegreeMixing, BaseTestNumericMixing as BaseTestNumericMixing
from _typeshed import Incomplete

np: Incomplete

class TestDegreeMixingDict(BaseTestDegreeMixing):
    def test_degree_mixing_dict_undirected(self) -> None: ...
    def test_degree_mixing_dict_undirected_normalized(self) -> None: ...
    def test_degree_mixing_dict_directed(self) -> None: ...
    def test_degree_mixing_dict_multigraph(self) -> None: ...
    def test_degree_mixing_dict_weighted(self) -> None: ...

class TestDegreeMixingMatrix(BaseTestDegreeMixing):
    def test_degree_mixing_matrix_undirected(self) -> None: ...
    def test_degree_mixing_matrix_directed(self) -> None: ...
    def test_degree_mixing_matrix_multigraph(self) -> None: ...
    def test_degree_mixing_matrix_selfloop(self) -> None: ...
    def test_degree_mixing_matrix_weighted(self) -> None: ...
    def test_degree_mixing_matrix_mapping(self) -> None: ...

class TestAttributeMixingDict(BaseTestAttributeMixing):
    def test_attribute_mixing_dict_undirected(self) -> None: ...
    def test_attribute_mixing_dict_directed(self) -> None: ...
    def test_attribute_mixing_dict_multigraph(self) -> None: ...

class TestAttributeMixingMatrix(BaseTestAttributeMixing):
    def test_attribute_mixing_matrix_undirected(self) -> None: ...
    def test_attribute_mixing_matrix_directed(self) -> None: ...
    def test_attribute_mixing_matrix_multigraph(self) -> None: ...

class TestNumericMixingMatrix(BaseTestNumericMixing):
    def test_numeric_mixing_matrix_negative(self) -> None: ...
    def test_numeric_mixing_matrix_float(self) -> None: ...
