from .base_test import BaseTestAttributeMixing as BaseTestAttributeMixing, BaseTestDegreeMixing as BaseTestDegreeMixing, BaseTestNumericMixing as BaseTestNumericMixing
from _typeshed import Incomplete
from networkx.algorithms.assortativity.correlation import attribute_ac as attribute_ac

np: Incomplete

class TestDegreeMixingCorrelation(BaseTestDegreeMixing):
    def test_degree_assortativity_undirected(self) -> None: ...
    def test_degree_assortativity_directed(self) -> None: ...
    def test_degree_assortativity_directed2(self) -> None: ...
    def test_degree_assortativity_multigraph(self) -> None: ...
    def test_degree_pearson_assortativity_undirected(self) -> None: ...
    def test_degree_pearson_assortativity_directed(self) -> None: ...
    def test_degree_pearson_assortativity_directed2(self) -> None: ...
    def test_degree_pearson_assortativity_multigraph(self) -> None: ...
    def test_degree_assortativity_weighted(self) -> None: ...
    def test_degree_assortativity_double_star(self) -> None: ...

class TestAttributeMixingCorrelation(BaseTestAttributeMixing):
    def test_attribute_assortativity_undirected(self) -> None: ...
    def test_attribute_assortativity_directed(self) -> None: ...
    def test_attribute_assortativity_multigraph(self) -> None: ...
    def test_attribute_assortativity_coefficient(self) -> None: ...
    def test_attribute_assortativity_coefficient2(self) -> None: ...
    def test_attribute_assortativity(self) -> None: ...

class TestNumericMixingCorrelation(BaseTestNumericMixing):
    def test_numeric_assortativity_negative(self) -> None: ...
    def test_numeric_assortativity_float(self) -> None: ...
    def test_numeric_assortativity_mixed(self) -> None: ...
