from _typeshed import Incomplete
from scipy.linalg import null_space as null_space, svd as svd
from scipy.sparse import csc_matrix as csc_matrix, issparse as issparse, random as random, spdiags as spdiags
from scipy.sparse.linalg import LinearOperator as LinearOperator, aslinearoperator as aslinearoperator, svds as svds
from scipy.sparse.linalg._eigen.arpack import ArpackNoConvergence as ArpackNoConvergence

has_propack: bool

def sorted_svd(m, k, which: str = ...): ...

class CheckingLinearOperator(LinearOperator):
    A: Incomplete
    dtype: Incomplete
    shape: Incomplete
    def __init__(self, A) -> None: ...

class SVDSCommonTests:
    solver: Incomplete
    def test_svds_input_validation_A(self, args) -> None: ...
    def test_svds_input_validation_k_1(self, k) -> None: ...
    def test_svds_input_validation_k_2(self) -> None: ...
    def test_svds_input_validation_tol_1(self, tol) -> None: ...
    def test_svds_input_validation_tol_2(self, tol) -> None: ...
    def test_svds_input_validation_which(self, which) -> None: ...
    def test_svds_input_validation_v0_1(self, transpose, n) -> None: ...
    def test_svds_input_validation_v0_2(self) -> None: ...
    def test_svds_input_validation_v0_3(self, v0) -> None: ...
    def test_svds_input_validation_maxiter_1(self, maxiter) -> None: ...
    def test_svds_input_validation_maxiter_2(self) -> None: ...
    def test_svds_input_validation_return_singular_vectors(self, rsv) -> None: ...
    def test_svds_parameter_k_which(self, k, which) -> None: ...
    def test_svds_parameter_tol(self): ...
    def test_svd_v0(self) -> None: ...
    def test_svd_random_state(self) -> None: ...
    def test_svd_random_state_2(self, random_state) -> None: ...
    def test_svd_random_state_3(self, random_state) -> None: ...
    def test_svd_maxiter(self) -> None: ...
    def test_svd_return_singular_vectors(self, rsv, shape) -> None: ...
    A1: Incomplete
    A2: Incomplete
    def test_svd_simple(self, A, k, real, transpose, lo_type) -> None: ...
    def test_svd_linop(self): ...
    SHAPES: Incomplete
    def test_small_sigma_sparse(self, shape, dtype) -> None: ...
    def test_svd_LM_ones_matrix(self, shape, dtype) -> None: ...
    def test_zero_matrix(self, shape, dtype) -> None: ...
    def test_small_sigma(self, shape, dtype) -> None: ...
    def test_small_sigma2(self, dtype) -> None: ...

class Test_SVDS_once:
    def test_svds_input_validation_solver(self, solver) -> None: ...

class Test_SVDS_ARPACK(SVDSCommonTests):
    solver: str
    def setup_method(self) -> None: ...
    def test_svds_input_validation_ncv_1(self, ncv) -> None: ...
    def test_svds_input_validation_ncv_2(self) -> None: ...

class Test_SVDS_LOBPCG(SVDSCommonTests):
    solver: str
    def setup_method(self) -> None: ...
    def test_svd_random_state_3(self) -> None: ...

class Test_SVDS_PROPACK(SVDSCommonTests):
    solver: str
    def setup_method(self) -> None: ...
    def test_svd_LM_ones_matrix(self) -> None: ...
    def test_svd_LM_zeros_matrix(self) -> None: ...
