from _typeshed import Incomplete

def mean_squared_error(image0, image1): ...
def normalized_root_mse(image_true, image_test, *, normalization: str = ...): ...
def peak_signal_noise_ratio(image_true, image_test, *, data_range: Incomplete | None = ...): ...
def normalized_mutual_information(image0, image1, *, bins: int = ...): ...
