from _typeshed import Incomplete
from collections.abc import Generator

def is_biconnected(G): ...
def biconnected_component_edges(G) -> None: ...
def biconnected_components(G) -> Generator[Incomplete, None, None]: ...
def articulation_points(G) -> Generator[Incomplete, None, None]: ...
