from _typeshed import Incomplete
from collections.abc import Generator

def weakly_connected_components(G) -> Generator[Incomplete, None, None]: ...
def number_weakly_connected_components(G): ...
def is_weakly_connected(G): ...
