from _typeshed import Incomplete

def autolevel_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def gradient_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def mean_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def subtract_mean_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def enhance_contrast_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ...): ...
def pop_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ..., p1: int = ...): ...
def threshold_percentile(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., p0: int = ...): ...
