from _typeshed import Incomplete

def mean_bilateral(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., s0: int = ..., s1: int = ...): ...
def pop_bilateral(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., s0: int = ..., s1: int = ...): ...
def sum_bilateral(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., s0: int = ..., s1: int = ...): ...
