from _typeshed import Incomplete

def autolevel(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def equalize(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def gradient(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def maximum(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def mean(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def geometric_mean(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def subtract_mean(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def median(image, footprint: Incomplete | None = ..., out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def minimum(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def modal(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def enhance_contrast(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def pop(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def threshold(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def noise_filter(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def entropy(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
def otsu(image, footprint, out: Incomplete | None = ..., mask: Incomplete | None = ..., shift_x: bool = ..., shift_y: bool = ..., shift_z: bool = ...): ...
