from typing import Any

_autolevel: fused_cython_function
_autolevel_3D: fused_cython_function
_enhance_contrast: fused_cython_function
_enhance_contrast_3D: fused_cython_function
_entropy: fused_cython_function
_entropy_3D: fused_cython_function
_equalize: fused_cython_function
_equalize_3D: fused_cython_function
_geometric_mean: fused_cython_function
_geometric_mean_3D: fused_cython_function
_gradient: fused_cython_function
_gradient_3D: fused_cython_function
_majority: fused_cython_function
_majority_3D: fused_cython_function
_maximum: fused_cython_function
_maximum_3D: fused_cython_function
_mean: fused_cython_function
_mean_3D: fused_cython_function
_median: fused_cython_function
_median_3D: fused_cython_function
_minimum: fused_cython_function
_minimum_3D: fused_cython_function
_modal: fused_cython_function
_modal_3D: fused_cython_function
_noise_filter: fused_cython_function
_noise_filter_3D: fused_cython_function
_otsu: fused_cython_function
_otsu_3D: fused_cython_function
_pop: fused_cython_function
_pop_3D: fused_cython_function
_subtract_mean: fused_cython_function
_subtract_mean_3D: fused_cython_function
_sum: fused_cython_function
_sum_3D: fused_cython_function
_threshold: fused_cython_function
_threshold_3D: fused_cython_function
_windowed_hist: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
