from _typeshed import Incomplete

def caveman_graph(l, k): ...
def connected_caveman_graph(l, k): ...
def relaxed_caveman_graph(l, k, p, seed: Incomplete | None = ...): ...
def random_partition_graph(sizes, p_in, p_out, seed: Incomplete | None = ..., directed: bool = ...): ...
def planted_partition_graph(l, k, p_in, p_out, seed: Incomplete | None = ..., directed: bool = ...): ...
def gaussian_random_partition_graph(n, s, v, p_in, p_out, directed: bool = ..., seed: Incomplete | None = ...): ...
def ring_of_cliques(num_cliques, clique_size): ...
def windmill_graph(n, k): ...
def stochastic_block_model(sizes, p, nodelist: Incomplete | None = ..., seed: Incomplete | None = ..., directed: bool = ..., selfloops: bool = ..., sparse: bool = ...): ...
def LFR_benchmark_graph(n, tau1, tau2, mu, average_degree: Incomplete | None = ..., min_degree: Incomplete | None = ..., max_degree: Incomplete | None = ..., min_community: Incomplete | None = ..., max_community: Incomplete | None = ..., tol: float = ..., max_iters: int = ..., seed: Incomplete | None = ...): ...
