from _typeshed import Incomplete

class TestWikipediaExample:
    g1edges: Incomplete
    g2edges: Incomplete
    def test_graph(self) -> None: ...
    def test_subgraph(self) -> None: ...
    def test_subgraph_mono(self) -> None: ...

class TestVF2GraphDB:
    @staticmethod
    def create_graph(filename): ...
    def test_graph(self) -> None: ...
    def test_subgraph(self) -> None: ...

class TestAtlas:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_graph_atlas(self) -> None: ...

def test_multiedge() -> None: ...
def test_selfloop() -> None: ...
def test_selfloop_mono() -> None: ...
def test_isomorphism_iter1() -> None: ...
def test_monomorphism_iter1() -> None: ...
def test_isomorphism_iter2() -> None: ...
def test_multiple() -> None: ...
def test_noncomparable_nodes() -> None: ...
def test_monomorphism_edge_match() -> None: ...
