from _typeshed import Incomplete

class TestSelfIsomorphism:
    data: Incomplete
    def test_self_isomorphism(self) -> None: ...
    def test_edgecase_self_isomorphism(self) -> None: ...
    def test_directed_self_isomorphism(self) -> None: ...

class TestSubgraphIsomorphism:
    def test_isomorphism(self) -> None: ...
    def test_isomorphism2(self) -> None: ...
    def test_labeled_nodes(self): ...
    def test_labeled_edges(self): ...

class TestWikipediaExample:
    g1edges: Incomplete
    g2edges: Incomplete
    def test_graph(self) -> None: ...

class TestLargestCommonSubgraph:
    def test_mcis(self) -> None: ...
    def test_symmetry_mcis(self) -> None: ...
