class TestIsomorph:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_could_be_isomorphic(self) -> None: ...
    def test_fast_could_be_isomorphic(self) -> None: ...
    def test_faster_could_be_isomorphic(self) -> None: ...
    def test_is_isomorphic(self) -> None: ...
