from _typeshed import Incomplete

default_profile: str

def get_profile(rhost, assume: bool = ...): ...
def get_profiles(): ...
def register_profiles(profiles) -> None: ...
def register(rhost, profile: Incomplete | None = ...) -> None: ...
