from _typeshed import Incomplete
from pathos.abstract_launcher import AbstractWorkerPool

class ProcessPool(AbstractWorkerPool):
    def __init__(self, *args, **kwds) -> None: ...
    clear: Incomplete
    def map(self, f, *args, **kwds): ...
    def imap(self, f, *args, **kwds): ...
    def uimap(self, f, *args, **kwds): ...
    def amap(self, f, *args, **kwds): ...
    def pipe(self, f, *args, **kwds): ...
    def apipe(self, f, *args, **kwds): ...
    def restart(self, force: bool = ...): ...
    def close(self) -> None: ...
    def terminate(self) -> None: ...
    def join(self) -> None: ...
    ncpus: Incomplete
    nodes: Incomplete
    __state__: Incomplete
ProcessingPool = ProcessPool

# Names in __all__ with no definition:
#   _ProcessPool
