from _typeshed import Incomplete

profiler: Incomplete

def process_id(): ...
def thread_id(): ...

class profiled:
    prefix: Incomplete
    suffix: Incomplete
    sort: Incomplete
    pid: Incomplete
    def __init__(self, gen: Incomplete | None = ..., prefix: str = ..., suffix: str = ...) -> None: ...
    def __call__(self, f): ...

def not_profiled(f): ...
def enable_profiling(*args) -> None: ...
def start_profiling(*args) -> None: ...
def stop_profiling(*args) -> None: ...
def disable_profiling(*args) -> None: ...
def clear_stats(*args) -> None: ...
def get_stats(*args): ...
def print_stats(*args, **kwds) -> None: ...
def dump_stats(*args, **kwds) -> None: ...

class profile:
    config: Incomplete
    pipe: Incomplete
    def __init__(self, sort: Incomplete | None = ..., **config) -> None: ...
    def __call__(self, function, *args, **kwds): ...
