from _typeshed import Incomplete
from pathos import logger as logger

class Selector:
    def watch(self, timeout: Incomplete | None = ...) -> None: ...
    def notifyOnReadReady(self, fd, handler) -> None: ...
    def notifyOnWriteReady(self, fd, handler) -> None: ...
    def notifyOnException(self, fd, handler) -> None: ...
    def notifyOnInterrupt(self, handler) -> None: ...
    def notifyWhenIdle(self, handler) -> None: ...
    state: bool
    def __init__(self) -> None: ...
