from _typeshed import Incomplete
from pathos.abstract_launcher import AbstractWorkerPool

class SerialPool(AbstractWorkerPool):
    def map(self, f, *args, **kwds): ...
    def imap(self, f, *args, **kwds): ...
    def pipe(self, f, *args, **kwds): ...
    def restart(self, force: bool = ...) -> None: ...
    def close(self) -> None: ...
    def terminate(self) -> None: ...
    def join(self) -> None: ...
    def clear(self) -> None: ...
    nodes: Incomplete
    __state__: Incomplete
PythonSerial = SerialPool
