from _typeshed import Incomplete

class Server:
    def selector(self): ...
    def deactivate(self) -> None: ...
    def activate(self, onTimeout: Incomplete | None = ..., selector: Incomplete | None = ...) -> None: ...
    def serve(self, timeout) -> None: ...
    def __init__(self) -> None: ...
