from networkx.algorithms.approximation import diameter as diameter

class TestDiameter:
    def test_null_graph(self) -> None: ...
    def test_undirected_non_connected(self) -> None: ...
    def test_directed_non_strongly_connected(self) -> None: ...
    def test_complete_undirected_graph(self) -> None: ...
    def test_complete_directed_graph(self) -> None: ...
    def test_undirected_path_graph(self) -> None: ...
    def test_directed_path_graph(self) -> None: ...
    def test_single_node(self) -> None: ...
