from networkx.algorithms.approximation import maxcut as maxcut

def test_random_partitioning() -> None: ...
def test_random_partitioning_all_to_one() -> None: ...
def test_one_exchange_basic() -> None: ...
def test_one_exchange_optimal() -> None: ...
def test_negative_weights() -> None: ...
