from networkx.algorithms.approximation.steinertree import metric_closure as metric_closure, steiner_tree as steiner_tree
from networkx.utils import edges_equal as edges_equal

class TestSteinerTree:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_connected_metric_closure(self) -> None: ...
    def test_metric_closure(self) -> None: ...
    def test_steiner_tree(self) -> None: ...
    def test_multigraph_steiner_tree(self) -> None: ...
