from networkx.algorithms.approximation import min_edge_dominating_set as min_edge_dominating_set, min_weighted_dominating_set as min_weighted_dominating_set

class TestMinWeightDominatingSet:
    def test_min_weighted_dominating_set(self) -> None: ...
    def test_star_graph(self) -> None: ...
    def test_min_edge_dominating_set(self) -> None: ...
