def test_global_node_connectivity() -> None: ...
def test_white_harary1() -> None: ...
def test_complete_graphs() -> None: ...
def test_empty_graphs() -> None: ...
def test_petersen() -> None: ...
def test_dodecahedral() -> None: ...
def test_octahedral() -> None: ...
def test_only_source() -> None: ...
def test_only_target() -> None: ...
def test_missing_source() -> None: ...
def test_missing_target() -> None: ...
def test_source_equals_target() -> None: ...
def test_directed_node_connectivity() -> None: ...

class TestAllPairsNodeConnectivityApprox:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_cycles(self) -> None: ...
    def test_complete(self) -> None: ...
    def test_paths(self) -> None: ...
    def test_cutoff(self) -> None: ...
    def test_all_pairs_connectivity_nbunch(self) -> None: ...
