from networkx.algorithms.approximation import clique_removal as clique_removal, large_clique_size as large_clique_size, max_clique as max_clique, maximum_independent_set as maximum_independent_set

def is_independent_set(G, nodes): ...
def is_clique(G, nodes): ...

class TestCliqueRemoval:
    def test_trivial_graph(self) -> None: ...
    def test_complete_graph(self) -> None: ...
    def test_barbell_graph(self) -> None: ...

class TestMaxClique:
    def test_null_graph(self) -> None: ...
    def test_complete_graph(self) -> None: ...
    def test_maximal_by_cardinality(self) -> None: ...

def test_large_clique_size() -> None: ...
def test_independent_set() -> None: ...
