from networkx.algorithms.approximation import average_clustering as average_clustering

def test_petersen() -> None: ...
def test_petersen_seed() -> None: ...
def test_tetrahedral() -> None: ...
def test_dodecahedral() -> None: ...
def test_empty() -> None: ...
def test_complete() -> None: ...
