from networkx.algorithms.approximation import min_weighted_vertex_cover as min_weighted_vertex_cover

def is_cover(G, node_cover): ...

class TestMWVC:
    def test_unweighted_directed(self) -> None: ...
    def test_unweighted_undirected(self) -> None: ...
    def test_weighted(self) -> None: ...
    def test_unweighted_self_loop(self) -> None: ...
