(* Generated by futhark-bindgen *)

open Ctypes
open! Unsigned
open! Signed

module Bindings = struct
  external _stub: unit -> unit = "futhark_context_new"

  let fn = Foreign.foreign ~release_runtime_lock:true
  let context = typedef (ptr void) "context"
  let context_config = typedef (ptr void) "context_config"
  let futhark_context_new = fn "futhark_context_new" (context_config @-> returning context)
  let futhark_context_free = fn "futhark_context_free" (context @-> returning int)
  let futhark_context_sync = fn "futhark_context_sync" (context @-> returning int)
  let futhark_context_config_new = fn "futhark_context_config_new" (void @-> returning context_config)
  let futhark_context_config_free = fn "futhark_context_config_free" (context_config @-> returning int)
  let futhark_context_config_set_profiling = fn "futhark_context_config_set_profiling" (context_config @-> int @-> returning void)
  let futhark_context_config_set_debugging = fn "futhark_context_config_set_debugging" (context_config @-> int @-> returning void)
  let futhark_context_config_set_logging = fn "futhark_context_config_set_logging" (context_config @-> int @-> returning void)
  let futhark_context_config_set_cache_file = fn "futhark_context_config_set_cache_file" (context_config @-> string @-> returning void)
  let futhark_context_pause_profiling = fn "futhark_context_pause_profiling" (context @-> returning void)
  let futhark_context_unpause_profiling = fn "futhark_context_unpause_profiling" (context @-> returning void)
  let futhark_context_clear_caches = fn "futhark_context_clear_caches" (context @-> returning int)
  let futhark_context_get_error = fn "futhark_context_get_error" (context @-> returning (ptr char))
  let futhark_context_report = fn "futhark_context_report" (context @-> returning (ptr char))
  let free = fn "free" (ptr void @-> returning void)
  let strlen = fn "strlen" (ptr char @-> returning size_t)


end

type error =
  | InvalidShape of int * int
  | NullPtr
  | Code of int
  | UseAfterFree of [`context | `array | `opaque]

exception Error of error

let set_managed (p: 'a Ctypes_static.ptr) x =
  match p with
  | Ctypes_static.CPointer fat -> Ctypes_ptr.Fat.set_managed fat (Some (Obj.repr x))

let check_use_after_free t b = if b then raise (Error (UseAfterFree t))

let () = Printexc.register_printer (function
  | Error (InvalidShape (a, b)) -> Some (Printf.sprintf "futhark error: invalid shape, expected %d but got %d" a b)
  | Error NullPtr -> Some "futhark error: null pointer"
  | Error (Code c) -> Some (Printf.sprintf "futhark error: code %d" c) 
  | Error (UseAfterFree `context) -> Some "futhark: context used after beeing freed"
  | Error (UseAfterFree `array) -> Some "futhark: array used after beeing freed"
  | Error (UseAfterFree `opaque) -> Some "futhark: opaque value used after beeing freed"
  | _ -> None)



open Bigarray

module Context = struct
  [@@@ocaml.warning "-69"]
  type t = { handle: unit ptr; config: unit ptr; cache_file: string option; auto_sync: bool; mutable context_free: bool }
  [@@@ocaml.warning "+69"]

  let free t =
    if not t.context_free then
      let () = ignore (Bindings.futhark_context_sync t.handle) in
      let () = ignore (Bindings.futhark_context_free t.handle) in
      let () = ignore (Bindings.futhark_context_config_free t.config) in
      t.context_free <- true

  let v ?(debug = false) ?(log = false) ?(profile = false) ?cache_file ?(auto_sync = true)  () =
    let config = Bindings.futhark_context_config_new () in
    if is_null config then raise (Error NullPtr);
    Bindings.futhark_context_config_set_debugging config (if debug then 1 else 0);
    Bindings.futhark_context_config_set_profiling config (if profile then 1 else 0);
    Bindings.futhark_context_config_set_logging config (if log then 1 else 0);
    
    Option.iter (Bindings.futhark_context_config_set_cache_file config) cache_file;
    let handle = Bindings.futhark_context_new config in
    if is_null handle then 
      let () = ignore @@ Bindings.futhark_context_config_free config in
      raise (Error NullPtr)
    else
      let t = { handle; config; cache_file; auto_sync; context_free = false } in
      set_managed handle t; 
      let () = Gc.finalise free t in
      t

  let sync t =
    check_use_after_free `context t.context_free;
    let rc = Bindings.futhark_context_sync t.handle in
    if rc <> 0 then raise (Error (Code rc))

  let auto_sync t =
    if t.auto_sync then sync t
  
  let clear_caches t =
    check_use_after_free `context t.context_free;
    let rc = Bindings.futhark_context_clear_caches t.handle in
    if rc <> 0 then raise (Error (Code rc))

  let string_opt_of_ptr ptr = 
    if is_null ptr then None
    else
      let len = Bindings.strlen ptr |> Unsigned.Size_t.to_int in
      let s = String.init len (fun i -> !@(ptr +@ i)) in
      let () = Bindings.free (coerce (Ctypes.ptr Ctypes.char) (Ctypes.ptr void) ptr) in Some s

  let get_error t = 
    check_use_after_free `context t.context_free;
    let ptr = Bindings.futhark_context_get_error t.handle in string_opt_of_ptr ptr

  let report t = 
    check_use_after_free `context t.context_free;
    let ptr = Bindings.futhark_context_report t.handle in string_opt_of_ptr ptr

  let pause_profiling t = 
    check_use_after_free `context t.context_free;
    Bindings.futhark_context_pause_profiling t.handle

  let unpause_profiling t =
    check_use_after_free `context t.context_free;
    Bindings.futhark_context_unpause_profiling t.handle
end

[@@@ocaml.warning "-34"]
[@@@ocaml.warning "-69"]
type futhark_array = { mutable ptr: unit ptr ptr; shape: int array; ctx: Context.t }
type opaque = { mutable opaque_ptr: unit ptr ptr; opaque_ctx: Context.t }
[@@@ocaml.warning "+34"]
[@@@ocaml.warning "+69"]

[@@@ocaml.warning "-32"]
let get_ptr t =
  let x = !@(t.ptr) in
  check_use_after_free `array (Ctypes.is_null x);
  x

let get_opaque_ptr t =
  let x = !@(t.opaque_ptr) in
  check_use_after_free `opaque (Ctypes.is_null x);
  x
[@@@ocaml.warning "+32"]


