from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.errors import NumbaUtilError as NumbaUtilError
from typing import Callable

GLOBAL_USE_NUMBA: bool

def maybe_use_numba(engine: Union[str, None]) -> bool: ...
def set_use_numba(enable: bool = ...) -> None: ...
def get_jit_arguments(engine_kwargs: Union[dict[str, bool], None] = ..., kwargs: Union[dict, None] = ...) -> dict[str, bool]: ...
def jit_user_function(func: Callable, nopython: bool, nogil: bool, parallel: bool) -> Callable: ...
