from _typeshed import Incomplete

class CheckedCall:
    def __init__(self, f) -> None: ...
    def __call__(self, *args): ...
    def __setattr__(self, key, value) -> None: ...

def determine_clipboard(): ...
def set_clipboard(clipboard) -> None: ...

copy: Incomplete
paste: Incomplete
clipboard_get = paste
clipboard_set = copy
