def weighted_G(): ...

class TestBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_K5_endpoints(self) -> None: ...
    def test_P3_normalized(self) -> None: ...
    def test_P3(self) -> None: ...
    def test_sample_from_P3(self) -> None: ...
    def test_P3_endpoints(self) -> None: ...
    def test_krackhardt_kite_graph(self) -> None: ...
    def test_krackhardt_kite_graph_normalized(self) -> None: ...
    def test_florentine_families_graph(self) -> None: ...
    def test_les_miserables_graph(self) -> None: ...
    def test_ladder_graph(self) -> None: ...
    def test_disconnected_path(self) -> None: ...
    def test_disconnected_path_endpoints(self) -> None: ...
    def test_directed_path(self) -> None: ...
    def test_directed_path_normalized(self) -> None: ...

class TestWeightedBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_P3_normalized(self) -> None: ...
    def test_P3(self) -> None: ...
    def test_krackhardt_kite_graph(self) -> None: ...
    def test_krackhardt_kite_graph_normalized(self) -> None: ...
    def test_florentine_families_graph(self) -> None: ...
    def test_les_miserables_graph(self) -> None: ...
    def test_ladder_graph(self) -> None: ...
    def test_G(self) -> None: ...
    def test_G2(self) -> None: ...
    def test_G3(self) -> None: ...
    def test_G4(self) -> None: ...

class TestEdgeBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_normalized_K5(self) -> None: ...
    def test_C4(self) -> None: ...
    def test_P4(self) -> None: ...
    def test_normalized_P4(self) -> None: ...
    def test_balanced_tree(self) -> None: ...

class TestWeightedEdgeBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_C4(self) -> None: ...
    def test_P4(self) -> None: ...
    def test_balanced_tree(self) -> None: ...
    def test_weighted_graph(self) -> None: ...
    def test_normalized_weighted_graph(self) -> None: ...
    def test_weighted_multigraph(self) -> None: ...
    def test_normalized_weighted_multigraph(self) -> None: ...
