class TestLoadCentrality:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_not_strongly_connected(self) -> None: ...
    def test_weighted_load(self) -> None: ...
    def test_k5_load(self) -> None: ...
    def test_p3_load(self) -> None: ...
    def test_p2_load(self) -> None: ...
    def test_krackhardt_load(self) -> None: ...
    def test_florentine_families_load(self) -> None: ...
    def test_les_miserables_load(self) -> None: ...
    def test_unnormalized_k5_load(self) -> None: ...
    def test_unnormalized_p3_load(self) -> None: ...
    def test_unnormalized_krackhardt_load(self) -> None: ...
    def test_unnormalized_florentine_families_load(self) -> None: ...
    def test_load_betweenness_difference(self) -> None: ...
    def test_c4_edge_load(self) -> None: ...
    def test_p4_edge_load(self) -> None: ...
    def test_k5_edge_load(self) -> None: ...
    def test_tree_edge_load(self) -> None: ...
