from _typeshed import Incomplete

class TestDegreeCentrality:
    K: Incomplete
    P3: Incomplete
    K5: Incomplete
    F: Incomplete
    G: Incomplete
    def setup_method(self) -> None: ...
    def test_degree_centrality_1(self) -> None: ...
    def test_degree_centrality_2(self) -> None: ...
    def test_degree_centrality_3(self) -> None: ...
    def test_degree_centrality_4(self) -> None: ...
    def test_indegree_centrality(self) -> None: ...
    def test_outdegree_centrality(self) -> None: ...
    def test_small_graph_centrality(self) -> None: ...
