from networkx.algorithms.centrality.subgraph_alg import communicability_betweenness_centrality as communicability_betweenness_centrality, estrada_index as estrada_index, subgraph_centrality as subgraph_centrality, subgraph_centrality_exp as subgraph_centrality_exp

class TestSubgraph:
    def test_subgraph_centrality(self) -> None: ...
    def test_subgraph_centrality_big_graph(self) -> None: ...
    def test_communicability_betweenness_centrality_small(self) -> None: ...
    def test_communicability_betweenness_centrality(self) -> None: ...
    def test_estrada_index(self) -> None: ...
