class TestFlowBetweennessCentrality:
    def test_K4_normalized(self) -> None: ...
    def test_K4(self) -> None: ...
    def test_P4_normalized(self) -> None: ...
    def test_P4(self) -> None: ...
    def test_star(self) -> None: ...

class TestEdgeFlowBetweennessCentrality:
    def test_K4_normalized(self) -> None: ...
    def test_K4(self) -> None: ...
    def test_C4(self) -> None: ...
    def test_P4(self) -> None: ...
