class TestSubsetBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_P5_directed(self) -> None: ...
    def test_P5(self) -> None: ...
    def test_P5_multiple_target(self) -> None: ...
    def test_box(self) -> None: ...
    def test_box_and_path(self) -> None: ...
    def test_box_and_path2(self) -> None: ...
    def test_diamond_multi_path(self) -> None: ...

class TestBetweennessCentralitySources:
    def test_K5(self) -> None: ...
    def test_P3(self) -> None: ...

class TestEdgeSubsetBetweennessCentrality:
    def test_K5(self) -> None: ...
    def test_P5_directed(self) -> None: ...
    def test_P5(self) -> None: ...
    def test_P5_multiple_target(self) -> None: ...
    def test_box(self) -> None: ...
    def test_box_and_path(self) -> None: ...
    def test_box_and_path2(self) -> None: ...
