from networkx.algorithms.centrality import harmonic_centrality as harmonic_centrality

class TestClosenessCentrality:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_p3_harmonic(self) -> None: ...
    def test_p4_harmonic(self) -> None: ...
    def test_clique_complete(self) -> None: ...
    def test_cycle_C4(self) -> None: ...
    def test_cycle_C5(self) -> None: ...
    def test_bal_tree(self) -> None: ...
    def test_exampleGraph(self) -> None: ...
    def test_weighted_harmonic(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_singleton(self) -> None: ...
    def test_cycle_c4_directed(self) -> None: ...
    def test_p3_harmonic_subset(self) -> None: ...
    def test_p4_harmonic_subset(self) -> None: ...
