def example1a_G(): ...
def example1b_G(): ...

class TestPercolationCentrality:
    def test_percolation_example1a(self) -> None: ...
    def test_percolation_example1b(self) -> None: ...
    def test_converge_to_betweenness(self) -> None: ...
