from _typeshed import Incomplete

class TestGroupBetweennessCentrality:
    def test_group_betweenness_single_node(self) -> None: ...
    def test_group_betweenness_with_endpoints(self) -> None: ...
    def test_group_betweenness_normalized(self) -> None: ...
    def test_two_group_betweenness_value_zero(self) -> None: ...
    def test_group_betweenness_value_zero(self) -> None: ...
    def test_group_betweenness_disconnected_graph(self) -> None: ...
    def test_group_betweenness_node_not_in_graph(self) -> None: ...
    def test_group_betweenness_directed_weighted(self) -> None: ...

class TestProminentGroup:
    np: Incomplete
    pd: Incomplete
    def test_prominent_group_single_node(self) -> None: ...
    def test_prominent_group_with_c(self) -> None: ...
    def test_prominent_group_normalized_endpoints(self) -> None: ...
    def test_prominent_group_disconnected_graph(self) -> None: ...
    def test_prominent_group_node_not_in_graph(self) -> None: ...
    def test_group_betweenness_directed_weighted(self) -> None: ...
    def test_prominent_group_greedy_algorithm(self) -> None: ...

class TestGroupClosenessCentrality:
    def test_group_closeness_single_node(self) -> None: ...
    def test_group_closeness_disconnected(self) -> None: ...
    def test_group_closeness_multiple_node(self) -> None: ...
    def test_group_closeness_node_not_in_graph(self) -> None: ...

class TestGroupDegreeCentrality:
    def test_group_degree_centrality_single_node(self) -> None: ...
    def test_group_degree_centrality_multiple_node(self) -> None: ...
    def test_group_in_degree_centrality(self) -> None: ...
    def test_group_out_degree_centrality(self) -> None: ...
    def test_group_degree_centrality_node_not_in_graph(self) -> None: ...
