class TestGlobalReachingCentrality:
    def test_non_positive_weights(self) -> None: ...
    def test_negatively_weighted(self) -> None: ...
    def test_directed_star(self) -> None: ...
    def test_undirected_unweighted_star(self) -> None: ...
    def test_undirected_weighted_star(self) -> None: ...
    def test_cycle_directed_unweighted(self) -> None: ...
    def test_cycle_undirected_unweighted(self) -> None: ...
    def test_cycle_directed_weighted(self) -> None: ...
    def test_cycle_undirected_weighted(self) -> None: ...
    def test_directed_weighted(self) -> None: ...

class TestLocalReachingCentrality:
    def test_non_positive_weights(self) -> None: ...
    def test_negatively_weighted(self) -> None: ...
    def test_undirected_unweighted_star(self) -> None: ...
    def test_undirected_weighted_star(self) -> None: ...
