class TestVoteRankCentrality:
    def test_voterank_centrality_1(self) -> None: ...
    def test_voterank_centrality_2(self) -> None: ...
    def test_voterank_centrality_3(self) -> None: ...
    def test_voterank_centrality_4(self) -> None: ...
    def test_voterank_centrality_5(self) -> None: ...
