class TestSecondOrderCentrality:
    def test_empty(self) -> None: ...
    def test_non_connected(self) -> None: ...
    def test_non_negative_edge_weights(self) -> None: ...
    def test_one_node_graph(self) -> None: ...
    def test_P3(self) -> None: ...
    def test_K3(self) -> None: ...
    def test_ring_graph(self) -> None: ...
