from _typeshed import Incomplete

np: Incomplete

class TestFlowBetweennessCentrality:
    def test_K4_normalized(self) -> None: ...
    def test_K4(self) -> None: ...
    def test_P4_normalized(self) -> None: ...
    def test_P4(self) -> None: ...
    def test_star(self) -> None: ...
    def test_solvers2(self) -> None: ...

class TestApproximateFlowBetweennessCentrality:
    def test_K4_normalized(self) -> None: ...
    def test_K4(self) -> None: ...
    def test_star(self) -> None: ...
    def test_grid(self) -> None: ...
    def test_seed(self) -> None: ...
    def test_solvers(self) -> None: ...

class TestWeightedFlowBetweennessCentrality: ...

class TestEdgeFlowBetweennessCentrality:
    def test_K4(self) -> None: ...
    def test_K4_normalized(self) -> None: ...
    def test_C4(self) -> None: ...
    def test_P4(self) -> None: ...
