from _typeshed import Incomplete

np: Incomplete

def test_trophic_levels() -> None: ...
def test_trophic_levels_levine() -> None: ...
def test_trophic_levels_simple() -> None: ...
def test_trophic_levels_more_complex() -> None: ...
def test_trophic_levels_even_more_complex() -> None: ...
def test_trophic_levels_singular_matrix() -> None: ...
def test_trophic_levels_singular_with_basal() -> None: ...
def test_trophic_differences() -> None: ...
def test_trophic_incoherence_parameter_no_cannibalism() -> None: ...
def test_trophic_incoherence_parameter_cannibalism() -> None: ...
