from _typeshed import Incomplete

np: Incomplete

class TestEigenvectorCentrality:
    def test_K5(self) -> None: ...
    def test_P3(self) -> None: ...
    def test_P3_unweighted(self) -> None: ...
    def test_maxiter(self) -> None: ...

class TestEigenvectorCentralityDirected:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_eigenvector_centrality_weighted(self) -> None: ...
    def test_eigenvector_centrality_weighted_numpy(self) -> None: ...
    def test_eigenvector_centrality_unweighted(self) -> None: ...
    def test_eigenvector_centrality_unweighted_numpy(self) -> None: ...

class TestEigenvectorCentralityExceptions:
    def test_multigraph(self) -> None: ...
    def test_multigraph_numpy(self) -> None: ...
    def test_empty(self) -> None: ...
    def test_empty_numpy(self) -> None: ...
