class TestClosenessCentrality:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_wf_improved(self) -> None: ...
    def test_digraph(self) -> None: ...
    def test_k5_closeness(self) -> None: ...
    def test_p3_closeness(self) -> None: ...
    def test_krackhardt_closeness(self) -> None: ...
    def test_florentine_families_closeness(self) -> None: ...
    def test_les_miserables_closeness(self) -> None: ...
    def test_weighted_closeness(self) -> None: ...
    @staticmethod
    def pick_add_edge(g): ...
    @staticmethod
    def pick_remove_edge(g): ...
    def test_directed_raises(self) -> None: ...
    def test_wrong_size_prev_cc_raises(self) -> None: ...
    def test_wrong_nodes_prev_cc_raises(self) -> None: ...
    def test_zero_centrality(self) -> None: ...
    def test_incremental(self) -> None: ...
