from _typeshed import Incomplete

def betweenness_centrality_subset(G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ...): ...
def edge_betweenness_centrality_subset(G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ...): ...
def betweenness_centrality_source(G, normalized: bool = ..., weight: Incomplete | None = ..., sources: Incomplete | None = ...): ...
