from _typeshed import Incomplete

def betweenness_centrality(G, k: Incomplete | None = ..., normalized: bool = ..., weight: Incomplete | None = ..., endpoints: bool = ..., seed: Incomplete | None = ...): ...
def edge_betweenness_centrality(G, k: Incomplete | None = ..., normalized: bool = ..., weight: Incomplete | None = ..., seed: Incomplete | None = ...): ...
def edge_betweenness(G, k: Incomplete | None = ..., normalized: bool = ..., weight: Incomplete | None = ..., seed: Incomplete | None = ...): ...
