from _typeshed import Incomplete

def closeness_centrality(G, u: Incomplete | None = ..., distance: Incomplete | None = ..., wf_improved: bool = ...): ...
def incremental_closeness_centrality(G, edge, prev_cc: Incomplete | None = ..., insertion: bool = ..., wf_improved: bool = ...): ...
