from _typeshed import Incomplete

def current_flow_betweenness_centrality_subset(G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ..., dtype=..., solver: str = ...): ...
def edge_current_flow_betweenness_centrality_subset(G, sources, targets, normalized: bool = ..., weight: Incomplete | None = ..., dtype=..., solver: str = ...): ...
