from _typeshed import Incomplete

def eigenvector_centrality(G, max_iter: int = ..., tol: float = ..., nstart: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def eigenvector_centrality_numpy(G, weight: Incomplete | None = ..., max_iter: int = ..., tol: int = ...): ...
