from _typeshed import Incomplete

def group_betweenness_centrality(G, C, normalized: bool = ..., weight: Incomplete | None = ..., endpoints: bool = ...): ...
def prominent_group(G, k, weight: Incomplete | None = ..., C: Incomplete | None = ..., endpoints: bool = ..., normalized: bool = ..., greedy: bool = ...): ...
def group_closeness_centrality(G, S, weight: Incomplete | None = ...): ...
def group_degree_centrality(G, S): ...
def group_in_degree_centrality(G, S): ...
def group_out_degree_centrality(G, S): ...
