from _typeshed import Incomplete

def global_reaching_centrality(G, weight: Incomplete | None = ..., normalized: bool = ...): ...
def local_reaching_centrality(G, v, paths: Incomplete | None = ..., weight: Incomplete | None = ..., normalized: bool = ...): ...
