from networkx import NetworkXError as NetworkXError, cycle_graph as cycle_graph
from networkx.algorithms.bipartite import complete_bipartite_graph as complete_bipartite_graph, node_redundancy as node_redundancy

def test_no_redundant_nodes() -> None: ...
def test_redundant_nodes() -> None: ...
def test_not_enough_neighbors() -> None: ...
