from ..generators import alternating_havel_hakimi_graph as alternating_havel_hakimi_graph, complete_bipartite_graph as complete_bipartite_graph, configuration_model as configuration_model, gnmk_random_graph as gnmk_random_graph, havel_hakimi_graph as havel_hakimi_graph, preferential_attachment_graph as preferential_attachment_graph, random_graph as random_graph, reverse_havel_hakimi_graph as reverse_havel_hakimi_graph

class TestGeneratorsBipartite:
    def test_complete_bipartite_graph(self) -> None: ...
    def test_configuration_model(self) -> None: ...
    def test_havel_hakimi_graph(self) -> None: ...
    def test_reverse_havel_hakimi_graph(self) -> None: ...
    def test_alternating_havel_hakimi_graph(self) -> None: ...
    def test_preferential_attachment(self) -> None: ...
    def test_random_graph(self) -> None: ...
    def test_random_digraph(self) -> None: ...
    def test_gnmk_random_graph(self) -> None: ...
    def test_gnmk_random_graph_complete(self) -> None: ...
