from networkx.algorithms.bipartite.cluster import cc_dot as cc_dot, cc_max as cc_max, cc_min as cc_min

def test_pairwise_bipartite_cc_functions() -> None: ...
def test_star_graph() -> None: ...
def test_not_bipartite() -> None: ...
def test_bad_mode() -> None: ...
def test_path_graph() -> None: ...
def test_average_path_graph() -> None: ...
def test_ra_clustering_davis() -> None: ...
def test_ra_clustering_square() -> None: ...
def test_ra_clustering_zero() -> None: ...
