from networkx.algorithms import bipartite as bipartite

class TestBipartiteCentrality:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_degree_centrality(self) -> None: ...
    def test_betweenness_centrality(self) -> None: ...
    def test_closeness_centrality(self) -> None: ...
    def test_davis_degree_centrality(self) -> None: ...
    def test_davis_betweenness_centrality(self) -> None: ...
    def test_davis_closeness_centrality(self) -> None: ...
