from _typeshed import Incomplete
from networkx.algorithms import bipartite as bipartite
from networkx.utils import edges_equal as edges_equal

np: Incomplete
sp: Incomplete
sparse: Incomplete

class TestBiadjacencyMatrix:
    def test_biadjacency_matrix_weight(self) -> None: ...
    def test_biadjacency_matrix(self) -> None: ...
    def test_biadjacency_matrix_order(self) -> None: ...
    def test_null_graph(self) -> None: ...
    def test_empty_graph(self) -> None: ...
    def test_duplicate_row(self) -> None: ...
    def test_duplicate_col(self) -> None: ...
    def test_format_keyword(self) -> None: ...
    def test_from_biadjacency_roundtrip(self) -> None: ...
    def test_from_biadjacency_weight(self) -> None: ...
    def test_from_biadjacency_multigraph(self) -> None: ...
