from networkx.algorithms import bipartite as bipartite
from networkx.utils import edges_equal as edges_equal, graphs_equal as graphs_equal, nodes_equal as nodes_equal

class TestEdgelist:
    @classmethod
    def setup_class(cls) -> None: ...
    def test_read_edgelist_1(self) -> None: ...
    def test_read_edgelist_3(self) -> None: ...
    def test_write_edgelist_1(self) -> None: ...
    def test_write_edgelist_2(self) -> None: ...
    def test_write_edgelist_3(self) -> None: ...
    def test_write_edgelist_4(self) -> None: ...
    def test_unicode(self) -> None: ...
    def test_latin1_issue(self) -> None: ...
    def test_latin1(self) -> None: ...
    def test_edgelist_graph(self) -> None: ...
    def test_edgelist_integers(self) -> None: ...
    def test_edgelist_multigraph(self) -> None: ...
    def test_empty_digraph(self) -> None: ...
    def test_raise_attribute(self) -> None: ...
