from _typeshed import Incomplete

def edge_boundary(G, nbunch1, nbunch2: Incomplete | None = ..., data: bool = ..., keys: bool = ..., default: Incomplete | None = ...): ...
def node_boundary(G, nbunch1, nbunch2: Incomplete | None = ...): ...
