from _typeshed import Incomplete
from collections.abc import Generator

def bridges(G, root: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
def has_bridges(G, root: Incomplete | None = ...): ...
def local_bridges(G, with_span: bool = ..., weight: Incomplete | None = ...) -> Generator[Incomplete, None, Incomplete]: ...
