from _typeshed import Incomplete

def triangles(G, nodes: Incomplete | None = ...): ...
def average_clustering(G, nodes: Incomplete | None = ..., weight: Incomplete | None = ..., count_zeros: bool = ...): ...
def clustering(G, nodes: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def transitivity(G): ...
def square_clustering(G, nodes: Incomplete | None = ...): ...
def generalized_degree(G, nodes: Incomplete | None = ...): ...
