from _typeshed import Incomplete

def weisfeiler_lehman_graph_hash(G, edge_attr: Incomplete | None = ..., node_attr: Incomplete | None = ..., iterations: int = ..., digest_size: int = ...): ...
def weisfeiler_lehman_subgraph_hashes(G, edge_attr: Incomplete | None = ..., node_attr: Incomplete | None = ..., iterations: int = ..., digest_size: int = ...): ...
