from _typeshed import Incomplete

def effective_size(G, nodes: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def constraint(G, nodes: Incomplete | None = ..., weight: Incomplete | None = ...): ...
def local_constraint(G, u, v, weight: Incomplete | None = ...): ...
