from _typeshed import Incomplete

def dedensify(G, threshold, prefix: Incomplete | None = ..., copy: bool = ...): ...
def snap_aggregation(G, node_attributes, edge_attributes=..., prefix: str = ..., supernode_attribute: str = ..., superedge_attribute: str = ...): ...
