from _typeshed import Incomplete

def double_edge_swap(G, nswap: int = ..., max_tries: int = ..., seed: Incomplete | None = ...): ...
def connected_double_edge_swap(G, nswap: int = ..., _window_threshold: int = ..., seed: Incomplete | None = ...): ...
