from _typeshed import Incomplete

mpl: Incomplete
np: Incomplete
plt: Incomplete
barbell: Incomplete

def test_draw() -> None: ...
def test_draw_shell_nlist() -> None: ...
def test_edge_colormap() -> None: ...
def test_arrows() -> None: ...
def test_single_edge_color_undirected(edge_color, expected, edgelist) -> None: ...
def test_single_edge_color_directed(edge_color, expected, edgelist) -> None: ...
def test_edge_color_tuple_interpretation() -> None: ...
def test_fewer_edge_colors_than_num_edges_directed() -> None: ...
def test_more_edge_colors_than_num_edges_directed() -> None: ...
def test_edge_color_string_with_gloabl_alpha_undirected() -> None: ...
def test_edge_color_string_with_global_alpha_directed() -> None: ...
def test_edge_width_default_value(graph_type) -> None: ...
def test_edge_width_single_value_undirected(edgewidth, expected) -> None: ...
def test_edge_width_single_value_directed(edgewidth, expected) -> None: ...
def test_edge_width_sequence(edgelist) -> None: ...
def test_edge_color_with_edge_vmin_vmax() -> None: ...
def test_directed_edges_linestyle_default() -> None: ...
def test_directed_edges_linestyle_single_value(style) -> None: ...
def test_directed_edges_linestyle_sequence(style_seq) -> None: ...
def test_labels_and_colors() -> None: ...
def test_house_with_colors(): ...
def test_axes() -> None: ...
def test_empty_graph() -> None: ...
def test_draw_empty_nodes_return_values() -> None: ...
def test_multigraph_edgelist_tuples() -> None: ...
def test_alpha_iter() -> None: ...
def test_error_invalid_kwds() -> None: ...
def test_draw_networkx_arrowsize_incorrect_size() -> None: ...
def test_draw_edges_arrowsize(arrowsize) -> None: ...
def test_np_edgelist() -> None: ...
def test_draw_nodes_missing_node_from_position() -> None: ...
def test_draw_edges_min_source_target_margins(node_shape) -> None: ...
def test_nonzero_selfloop_with_single_node() -> None: ...
def test_nonzero_selfloop_with_single_edge_in_edgelist() -> None: ...
def test_apply_alpha() -> None: ...
def test_draw_edges_toggling_with_arrows_kwarg() -> None: ...
def test_draw_networkx_arrows_default_undirected(drawing_func) -> None: ...
def test_draw_networkx_arrows_default_directed(drawing_func) -> None: ...
def test_edgelist_kwarg_not_ignored() -> None: ...
def test_draw_networkx_edge_label_multiedge_exception() -> None: ...
def test_draw_networkx_edge_label_empty_dict() -> None: ...
def test_draw_networkx_edges_undirected_selfloop_colors() -> None: ...
