from _typeshed import Incomplete
from networkx.utils import graphs_equal as graphs_equal

pydot: Incomplete

class TestPydot:
    def pydot_checks(self, G, prog) -> None: ...
    def test_undirected(self) -> None: ...
    def test_directed(self) -> None: ...
    def test_read_write(self) -> None: ...

def test_pydot_issue_258() -> None: ...
def test_hashable_pydot(graph_type) -> None: ...
def test_pydot_numrical_name() -> None: ...
