from _typeshed import Incomplete

class ForkServer:
    def __init__(self) -> None: ...
    def set_forkserver_preload(self, modules_names) -> None: ...
    def get_inherited_fds(self): ...
    def connect_to_new_process(self, fds): ...
    def ensure_running(self) -> None: ...

ensure_running: Incomplete
get_inherited_fds: Incomplete
connect_to_new_process: Incomplete
set_forkserver_preload: Incomplete
