from _typeshed import Incomplete

class Arena:
    size: Incomplete
    fd: Incomplete
    buffer: Incomplete
    def __init__(self, size, fd: int = ...) -> None: ...

class Heap:
    def __init__(self, size=...) -> None: ...
    def free(self, block) -> None: ...
    def malloc(self, size): ...

class BufferWrapper:
    def __init__(self, size) -> None: ...
    def create_memoryview(self): ...
