from _typeshed import Incomplete

class Popen:
    method: str
    pid: Incomplete
    returncode: Incomplete
    sentinel: Incomplete
    finalizer: Incomplete
    def __init__(self, process_obj) -> None: ...
    def duplicate_for_child(self, handle): ...
    def wait(self, timeout: Incomplete | None = ...): ...
    def poll(self): ...
    def terminate(self) -> None: ...
    kill: Incomplete
    def close(self) -> None: ...
