from _typeshed import Incomplete

class ResourceTracker:
    def __init__(self) -> None: ...
    def getfd(self): ...
    def ensure_running(self) -> None: ...
    def register(self, name, rtype) -> None: ...
    def unregister(self, name, rtype) -> None: ...

ensure_running: Incomplete
register: Incomplete
unregister: Incomplete
