def set_executable(exe) -> None: ...
def get_executable(): ...
def freeze_support() -> None: ...
def get_command_line(**kwds): ...
def get_preparation_data(name): ...
def import_main_path(main_path) -> None: ...

# Names in __all__ with no definition:
#   _main
