from _typeshed import Incomplete

def from_agraph(A, create_using: Incomplete | None = ...): ...
def to_agraph(N): ...
def write_dot(G, path) -> None: ...
def read_dot(path): ...
def graphviz_layout(G, prog: str = ..., root: Incomplete | None = ..., args: str = ...): ...
def pygraphviz_layout(G, prog: str = ..., root: Incomplete | None = ..., args: str = ...): ...
def view_pygraphviz(G, edgelabel: Incomplete | None = ..., prog: str = ..., args: str = ..., suffix: str = ..., path: Incomplete | None = ..., show: bool = ...): ...
