from _typeshed import Incomplete

class CanvasToolBase:
    manager: Incomplete
    ax: Incomplete
    artists: Incomplete
    active: bool
    callback_on_move: Incomplete
    callback_on_enter: Incomplete
    callback_on_release: Incomplete
    def __init__(self, manager, on_move: Incomplete | None = ..., on_enter: Incomplete | None = ..., on_release: Incomplete | None = ..., useblit: bool = ..., ax: Incomplete | None = ...) -> None: ...
    def ignore(self, event): ...
    def hit_test(self, event): ...
    def redraw(self) -> None: ...
    def set_visible(self, val) -> None: ...
    def on_key_press(self, event) -> None: ...
    def on_mouse_press(self, event) -> None: ...
    def on_mouse_release(self, event) -> None: ...
    def on_move(self, event) -> None: ...
    def on_scroll(self, event) -> None: ...
    def remove(self) -> None: ...
    @property
    def geometry(self) -> None: ...

class ToolHandles:
    ax: Incomplete
    artist: Incomplete
    def __init__(self, ax, x, y, marker: str = ..., marker_props: Incomplete | None = ...) -> None: ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    def set_data(self, pts, y: Incomplete | None = ...) -> None: ...
    def set_visible(self, val) -> None: ...
    def set_animated(self, val) -> None: ...
    def closest(self, x, y): ...
