from ...viewer.canvastools.base import CanvasToolBase
from _typeshed import Incomplete

class LineTool(CanvasToolBase):
    linewidth: Incomplete
    maxdist: Incomplete
    artists: Incomplete
    callback_on_enter: Incomplete
    def __init__(self, manager, on_move: Incomplete | None = ..., on_release: Incomplete | None = ..., on_enter: Incomplete | None = ..., maxdist: int = ..., line_props: Incomplete | None = ..., handle_props: Incomplete | None = ..., **kwargs) -> None: ...
    @property
    def end_points(self): ...
    @end_points.setter
    def end_points(self, pts) -> None: ...
    def hit_test(self, event): ...
    def on_mouse_press(self, event) -> None: ...
    def on_mouse_release(self, event) -> None: ...
    def on_move(self, event) -> None: ...
    def update(self, x: Incomplete | None = ..., y: Incomplete | None = ...) -> None: ...
    @property
    def geometry(self): ...

class ThickLineTool(LineTool):
    callback_on_change: Incomplete
    def __init__(self, manager, on_move: Incomplete | None = ..., on_enter: Incomplete | None = ..., on_release: Incomplete | None = ..., on_change: Incomplete | None = ..., maxdist: int = ..., line_props: Incomplete | None = ..., handle_props: Incomplete | None = ...) -> None: ...
    def on_scroll(self, event) -> None: ...
    def on_key_press(self, event) -> None: ...
