from ...viewer.canvastools.base import CanvasToolBase
from _typeshed import Incomplete
from matplotlib.widgets import RectangleSelector

class RectangleTool(CanvasToolBase, RectangleSelector):
    maxdist: Incomplete
    active_handle: Incomplete
    callback_on_enter: Incomplete
    artists: Incomplete
    def __init__(self, manager, on_move: Incomplete | None = ..., on_release: Incomplete | None = ..., on_enter: Incomplete | None = ..., maxdist: int = ..., rect_props: Incomplete | None = ...) -> None: ...
    @property
    def corners(self): ...
    @property
    def edge_centers(self): ...
    @property
    def extents(self): ...
    @extents.setter
    def extents(self, extents) -> None: ...
    eventpress: Incomplete
    def on_mouse_release(self, event) -> None: ...
    def on_mouse_press(self, event) -> None: ...
    def on_move(self, event) -> None: ...
    @property
    def geometry(self): ...
