from _typeshed import Incomplete

def gcrotmk(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: int = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., m: int = ..., k: Incomplete | None = ..., CU: Incomplete | None = ..., discard_C: bool = ..., truncate: str = ..., atol: Incomplete | None = ...): ...
