from _typeshed import Incomplete

def bicg(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: Incomplete | None = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., atol: Incomplete | None = ...): ...
def bicgstab(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: Incomplete | None = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., atol: Incomplete | None = ...): ...
def cg(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: Incomplete | None = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., atol: Incomplete | None = ...): ...
def cgs(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: Incomplete | None = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., atol: Incomplete | None = ...): ...
def gmres(A, b, x0: Incomplete | None = ..., tol: float = ..., restart: Incomplete | None = ..., maxiter: Incomplete | None = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., restrt: Incomplete | None = ..., atol: Incomplete | None = ..., callback_type: Incomplete | None = ...): ...
def qmr(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: Incomplete | None = ..., M1: Incomplete | None = ..., M2: Incomplete | None = ..., callback: Incomplete | None = ..., atol: Incomplete | None = ...): ...
