from _typeshed import Incomplete

def lgmres(A, b, x0: Incomplete | None = ..., tol: float = ..., maxiter: int = ..., M: Incomplete | None = ..., callback: Incomplete | None = ..., inner_m: int = ..., outer_k: int = ..., outer_v: Incomplete | None = ..., store_outer_Av: bool = ..., prepend_outer_v: bool = ..., atol: Incomplete | None = ...): ...
