from networkx import Graph as Graph, NetworkXError as NetworkXError
from networkx.algorithms.community.asyn_fluid import asyn_fluidc as asyn_fluidc

def test_exceptions() -> None: ...
def test_single_node() -> None: ...
def test_two_nodes() -> None: ...
def test_two_clique_communities() -> None: ...
def test_five_clique_ring() -> None: ...
