from networkx.algorithms.community import girvan_newman as girvan_newman

def set_of_sets(iterable): ...
def validate_communities(result, expected) -> None: ...
def validate_possible_communities(result, *expected) -> None: ...

class TestGirvanNewman:
    def test_no_edges(self) -> None: ...
    def test_undirected(self) -> None: ...
    def test_directed(self) -> None: ...
    def test_selfloops(self) -> None: ...
    def test_most_valuable_edge(self): ...
