from networkx.algorithms.community import greedy_modularity_communities as greedy_modularity_communities, naive_greedy_modularity_communities as naive_greedy_modularity_communities

def test_modularity_communities(func) -> None: ...
def test_modularity_communities_categorical_labels(func) -> None: ...
def test_greedy_modularity_communities_components() -> None: ...
def test_greedy_modularity_communities_relabeled() -> None: ...
def test_greedy_modularity_communities_directed() -> None: ...
def test_modularity_communities_weighted(func) -> None: ...
def test_modularity_communities_floating_point() -> None: ...
def test_modularity_communities_directed_weighted() -> None: ...
def test_greedy_modularity_communities_multigraph() -> None: ...
def test_greedy_modularity_communities_multigraph_weighted() -> None: ...
def test_greed_modularity_communities_multidigraph() -> None: ...
def test_greed_modularity_communities_multidigraph_weighted() -> None: ...
def test_resolution_parameter_impact() -> None: ...
def test_cutoff_parameter() -> None: ...
def test_best_n() -> None: ...
