from networkx.algorithms.community import is_partition as is_partition, louvain_communities as louvain_communities, louvain_partitions as louvain_partitions, modularity as modularity, partition_quality as partition_quality

def test_modularity_increase() -> None: ...
def test_valid_partition() -> None: ...
def test_karate_club_partition() -> None: ...
def test_partition_iterator() -> None: ...
def test_directed_partition() -> None: ...
def test_none_weight_param() -> None: ...
def test_quality() -> None: ...
def test_multigraph() -> None: ...
def test_resolution() -> None: ...
def test_threshold() -> None: ...
