from networkx import barbell_graph as barbell_graph
from networkx.algorithms.community import coverage as coverage, modularity as modularity, partition_quality as partition_quality, performance as performance
from networkx.algorithms.community.quality import inter_community_edges as inter_community_edges

class TestPerformance:
    def test_bad_partition(self) -> None: ...
    def test_good_partition(self) -> None: ...

class TestCoverage:
    def test_bad_partition(self) -> None: ...
    def test_good_partition(self) -> None: ...

def test_modularity() -> None: ...
def test_modularity_resolution() -> None: ...
def test_inter_community_edges_with_digraphs() -> None: ...
