from networkx.algorithms.community import lukes_partitioning as lukes_partitioning

EWL: str
NWL: str

def paper_1_case(float_edge_wt: bool = ..., explicit_node_wt: bool = ..., directed: bool = ...): ...
def paper_2_case(explicit_edge_wt: bool = ..., directed: bool = ...): ...
def test_paper_1_case() -> None: ...
def test_paper_2_case() -> None: ...
def test_mandatory_tree() -> None: ...
def test_mandatory_integrality() -> None: ...
