from networkx.algorithms.community import asyn_lpa_communities as asyn_lpa_communities, label_propagation_communities as label_propagation_communities

def test_directed_not_supported() -> None: ...
def test_iterator_vs_iterable() -> None: ...
def test_one_node() -> None: ...
def test_unconnected_communities() -> None: ...
def test_connected_communities() -> None: ...
def test_termination() -> None: ...

class TestAsynLpaCommunities:
    def test_null_graph(self) -> None: ...
    def test_single_node(self) -> None: ...
    def test_simple_communities(self) -> None: ...
    def test_seed_argument(self) -> None: ...
    def test_several_communities(self) -> None: ...
