from networkx.algorithms.community import kernighan_lin_bisection as kernighan_lin_bisection

def assert_partition_equal(x, y) -> None: ...
def test_partition() -> None: ...
def test_partition_argument() -> None: ...
def test_partition_argument_non_integer_nodes() -> None: ...
def test_seed_argument() -> None: ...
def test_non_disjoint_partition() -> None: ...
def test_too_many_blocks() -> None: ...
def test_multigraph() -> None: ...
def test_max_iter_argument() -> None: ...
