from networkx.algorithms.community import is_partition as is_partition

def test_is_partition() -> None: ...
def test_not_covering() -> None: ...
def test_not_disjoint() -> None: ...
def test_not_node() -> None: ...
