import numpy as np
from _typeshed import Incomplete
from matplotlib.axes import Axes as Axes
from matplotlib.figure import Figure as Figure
from pandas import DataFrame as DataFrame, Series as Series
from typing import Iterator

def table(ax, data, rowLabels: Incomplete | None = ..., colLabels: Incomplete | None = ..., **kwargs): ...
def register() -> None: ...
def deregister() -> None: ...
def scatter_matrix(frame: DataFrame, alpha: float = ..., figsize: Union[tuple[float, float], None] = ..., ax: Union[Axes, None] = ..., grid: bool = ..., diagonal: str = ..., marker: str = ..., density_kwds: Incomplete | None = ..., hist_kwds: Incomplete | None = ..., range_padding: float = ..., **kwargs) -> np.ndarray: ...
def radviz(frame: DataFrame, class_column: str, ax: Union[Axes, None] = ..., color: Union[list[str], tuple[str, ...], None] = ..., colormap: Incomplete | None = ..., **kwds) -> Axes: ...
def andrews_curves(frame: DataFrame, class_column: str, ax: Union[Axes, None] = ..., samples: int = ..., color: Union[list[str], tuple[str, ...], None] = ..., colormap: Incomplete | None = ..., **kwargs) -> Axes: ...
def bootstrap_plot(series: Series, fig: Union[Figure, None] = ..., size: int = ..., samples: int = ..., **kwds) -> Figure: ...
def parallel_coordinates(frame: DataFrame, class_column: str, cols: Union[list[str], None] = ..., ax: Union[Axes, None] = ..., color: Union[list[str], tuple[str, ...], None] = ..., use_columns: bool = ..., xticks: Union[list, tuple, None] = ..., colormap: Incomplete | None = ..., axvlines: bool = ..., axvlines_kwds: Incomplete | None = ..., sort_labels: bool = ..., **kwargs) -> Axes: ...
def lag_plot(series: Series, lag: int = ..., ax: Union[Axes, None] = ..., **kwds) -> Axes: ...
def autocorrelation_plot(series: Series, ax: Union[Axes, None] = ..., **kwargs) -> Axes: ...

class _Options(dict):
    def __init__(self, deprecated: bool = ...) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def reset(self) -> None: ...
    def use(self, key, value) -> Iterator[_Options]: ...

plot_params: Incomplete
