# Names in __all__ with no definition:
#   LPIFilter2D
#   apply_hysteresis_threshold
#   butterworth
#   correlate_sparse
#   difference_of_gaussians
#   farid
#   farid_h
#   farid_v
#   frangi
#   gabor
#   gabor_kernel
#   gaussian
#   hessian
#   inverse
#   laplace
#   median
#   meijering
#   prewitt
#   prewitt_h
#   prewitt_v
#   rank
#   rank_order
#   roberts
#   roberts_neg_diag
#   roberts_pos_diag
#   sato
#   scharr
#   scharr_h
#   scharr_v
#   sobel
#   sobel_h
#   sobel_v
#   threshold_isodata
#   threshold_li
#   threshold_local
#   threshold_mean
#   threshold_minimum
#   threshold_multiotsu
#   threshold_niblack
#   threshold_otsu
#   threshold_sauvola
#   threshold_triangle
#   threshold_yen
#   try_all_threshold
#   unsharp_mask
#   wiener
#   window
