from _typeshed import Incomplete

def gabor_kernel(frequency, theta: int = ..., bandwidth: int = ..., sigma_x: Incomplete | None = ..., sigma_y: Incomplete | None = ..., n_stds: int = ..., offset: int = ..., dtype=...): ...
def gabor(image, frequency, theta: int = ..., bandwidth: int = ..., sigma_x: Incomplete | None = ..., sigma_y: Incomplete | None = ..., n_stds: int = ..., offset: int = ..., mode: str = ..., cval: int = ...): ...
