from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _get_multiotsu_thresh_indices(*args, **kwargs) -> Any: ...
def _get_multiotsu_thresh_indices_lut(*args, **kwargs) -> Any: ...
