from .._shared.utils import check_nD as check_nD
from ..restoration.uft import laplacian as laplacian
from ..util.dtype import img_as_float as img_as_float
from _typeshed import Incomplete

SOBEL_EDGE: Incomplete
SOBEL_SMOOTH: Incomplete
HSOBEL_WEIGHTS: Incomplete
VSOBEL_WEIGHTS: Incomplete
SCHARR_EDGE: Incomplete
SCHARR_SMOOTH: Incomplete
HSCHARR_WEIGHTS: Incomplete
VSCHARR_WEIGHTS: Incomplete
PREWITT_EDGE: Incomplete
PREWITT_SMOOTH: Incomplete
HPREWITT_WEIGHTS: Incomplete
VPREWITT_WEIGHTS: Incomplete
ROBERTS_PD_WEIGHTS: Incomplete
ROBERTS_ND_WEIGHTS: Incomplete
p: Incomplete
d1: Incomplete
HFARID_WEIGHTS: Incomplete
VFARID_WEIGHTS: Incomplete

def sobel(image, mask: Incomplete | None = ..., *, axis: Incomplete | None = ..., mode: str = ..., cval: float = ...): ...
def sobel_h(image, mask: Incomplete | None = ...): ...
def sobel_v(image, mask: Incomplete | None = ...): ...
def scharr(image, mask: Incomplete | None = ..., *, axis: Incomplete | None = ..., mode: str = ..., cval: float = ...): ...
def scharr_h(image, mask: Incomplete | None = ...): ...
def scharr_v(image, mask: Incomplete | None = ...): ...
def prewitt(image, mask: Incomplete | None = ..., *, axis: Incomplete | None = ..., mode: str = ..., cval: float = ...): ...
def prewitt_h(image, mask: Incomplete | None = ...): ...
def prewitt_v(image, mask: Incomplete | None = ...): ...
def roberts(image, mask: Incomplete | None = ...): ...
def roberts_pos_diag(image, mask: Incomplete | None = ...): ...
def roberts_neg_diag(image, mask: Incomplete | None = ...): ...
def laplace(image, ksize: int = ..., mask: Incomplete | None = ...): ...
def farid(image, *, mask: Incomplete | None = ...): ...
def farid_h(image, *, mask: Incomplete | None = ...): ...
def farid_v(image, *, mask: Incomplete | None = ...): ...
