from _typeshed import Incomplete
from http.server import BaseHTTPRequestHandler
from pathos.server import Server
from xmlrpc.server import SimpleXMLRPCDispatcher

class XMLRPCServer(Server, SimpleXMLRPCDispatcher):
    def activate(self) -> None: ...
    def serve(self) -> None: ...
    def __init__(self, host, port) -> None: ...

class XMLRPCRequestHandler(BaseHTTPRequestHandler):
    def do_POST(self): ...
    def log_message(self, format, *args) -> None: ...
    rfile: Incomplete
    wfile: Incomplete
    connection: Incomplete
    client_address: Incomplete
    def __init__(self, server, socket) -> None: ...
