from .. import util as util, visual as visual
from ..constants import log as log
from _typeshed import Incomplete

def load_collada(file_obj, resolver: Incomplete | None = ..., ignore_broken: bool = ..., **kwargs): ...
def export_collada(mesh, **kwargs): ...
def load_zae(file_obj, resolver: Incomplete | None = ..., **kwargs): ...
