from .. import resolvers as resolvers, util as util
from ..constants import log as log
from .gltf import export_glb as export_glb, export_gltf as export_gltf
from .obj import export_obj as export_obj
from .ply import export_ply as export_ply
from .stl import export_stl as export_stl, export_stl_ascii as export_stl_ascii
from .threemf import export_3MF as export_3MF
from .urdf import export_urdf as export_urdf
from _typeshed import Incomplete

def export_mesh(mesh, file_obj, file_type: Incomplete | None = ..., resolver: Incomplete | None = ..., **kwargs): ...
def export_dict64(mesh): ...
def export_dict(mesh, encoding: Incomplete | None = ...): ...
def scene_to_dict(scene, use_base64: bool = ..., include_metadata: bool = ...): ...
def export_scene(scene, file_obj, file_type: Incomplete | None = ..., resolver: Incomplete | None = ..., **kwargs): ...
def export_json(mesh): ...
def export_msgpack(mesh): ...
