from .. import util as util
from _typeshed import Incomplete

def load_msgpack(blob, **kwargs): ...
def load_dict(data, **kwargs): ...
def load_meshio(file_obj, file_type: Incomplete | None = ..., **kwargs): ...
