from .. import util as util

class HeaderError(Exception): ...

def load_stl(file_obj, **kwargs): ...
def load_stl_binary(file_obj): ...
def load_stl_ascii(file_obj): ...
def export_stl(mesh): ...
def export_stl_ascii(mesh): ...
