from .base import Plugin as Plugin
from .canny import CannyPlugin as CannyPlugin
from .color_histogram import ColorHistogram as ColorHistogram
from .crop import Crop as Crop
from .labelplugin import LabelPainter as LabelPainter
from .lineprofile import LineProfile as LineProfile
from .measure import Measure as Measure
from .overlayplugin import OverlayPlugin as OverlayPlugin
from .plotplugin import PlotPlugin as PlotPlugin
