from ..qt import QtCore as QtCore, QtWidgets as QtWidgets, Signal as Signal
from ..utils import RequiredAttr as RequiredAttr, init_qtapp as init_qtapp
from _typeshed import Incomplete

class Plugin(QtWidgets.QDialog):
    name: str
    image_viewer: Incomplete
    image_changed: Incomplete
    dock: Incomplete
    image_filter: Incomplete
    layout: Incomplete
    row: int
    arguments: Incomplete
    keyword_arguments: Incomplete
    useblit: Incomplete
    cids: Incomplete
    artists: Incomplete
    def __init__(self, image_filter: Incomplete | None = ..., height: int = ..., width: int = ..., useblit: bool = ..., dock: str = ...) -> None: ...
    def attach(self, image_viewer) -> None: ...
    def add_widget(self, widget) -> None: ...
    def __add__(self, widget): ...
    def filter_image(self, *widget_arg) -> None: ...
    @property
    def filtered_image(self): ...
    def display_filtered_image(self, image) -> None: ...
    def update_plugin(self, name, value) -> None: ...
    def show(self, main_window: bool = ...) -> None: ...
    def closeEvent(self, event) -> None: ...
    def clean_up(self) -> None: ...
    def remove_image_artists(self) -> None: ...
    def output(self): ...
