from ... import color as color, exposure as exposure
from ..canvastools import RectangleTool as RectangleTool
from .plotplugin import PlotPlugin as PlotPlugin
from _typeshed import Incomplete

class ColorHistogram(PlotPlugin):
    name: str
    max_pct: Incomplete
    def __init__(self, max_pct: float = ..., **kwargs) -> None: ...
    rect_tool: Incomplete
    def attach(self, image_viewer) -> None: ...
    def help(self): ...
    mask: Incomplete
    def ab_selected(self, extents) -> None: ...
    def output(self): ...

def pct_total_area(image, percentile: float = ...): ...
