from .base import Plugin
from _typeshed import Incomplete

class Crop(Plugin):
    name: str
    maxdist: Incomplete
    def __init__(self, maxdist: int = ..., **kwargs) -> None: ...
    rect_tool: Incomplete
    reset_button: Incomplete
    def attach(self, image_viewer) -> None: ...
    def help(self): ...
    def crop(self, extents) -> None: ...
    def reset(self) -> None: ...
