from .base import Plugin
from _typeshed import Incomplete

class LabelPainter(Plugin):
    name: str
    def __init__(self, max_radius: int = ..., **kwargs) -> None: ...
    def help(self): ...
    paint_tool: Incomplete
    def attach(self, image_viewer) -> None: ...
    def on_enter(self, overlay) -> None: ...
    @property
    def radius(self): ...
    @radius.setter
    def radius(self, val) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, val) -> None: ...
