from .plotplugin import PlotPlugin
from _typeshed import Incomplete

class LineProfile(PlotPlugin):
    name: str
    maxdist: Incomplete
    def __init__(self, maxdist: int = ..., epsilon: str = ..., limits: str = ..., **kwargs) -> None: ...
    limits: Incomplete
    line_tool: Incomplete
    scan_data: Incomplete
    def attach(self, image_viewer) -> None: ...
    def help(self): ...
    def get_profiles(self): ...
    def line_changed(self, end_points) -> None: ...
    profile: Incomplete
    def reset_axes(self, scan_data) -> None: ...
    def output(self): ...
