from .base import Plugin
from _typeshed import Incomplete

class Measure(Plugin):
    name: str
    maxdist: Incomplete
    def __init__(self, maxdist: int = ..., **kwargs) -> None: ...
    line_tool: Incomplete
    def attach(self, image_viewer) -> None: ...
    def help(self): ...
    def line_changed(self, end_points) -> None: ...
