from .base import Plugin
from _typeshed import Incomplete

class OverlayPlugin(Plugin):
    colors: Incomplete
    cmap: Incomplete
    color_names: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def attach(self, image_viewer) -> None: ...
    @property
    def overlay(self): ...
    @overlay.setter
    def overlay(self, image) -> None: ...
    @property
    def color(self): ...
    @color.setter
    def color(self, index) -> None: ...
    @property
    def filtered_image(self): ...
    def display_filtered_image(self, image) -> None: ...
    def closeEvent(self, event) -> None: ...
    def output(self): ...
