from .base import Plugin
from _typeshed import Incomplete

class PlotPlugin(Plugin):
    def __init__(self, image_filter: Incomplete | None = ..., height: int = ..., width: int = ..., **kwargs) -> None: ...
    def attach(self, image_viewer) -> None: ...
    def redraw(self) -> None: ...
    canvas: Incomplete
    def add_plot(self) -> None: ...
    def add_tool(self, tool) -> None: ...
    def remove_tool(self, tool) -> None: ...
