from ..transform import warp as warp
from ._optical_flow_utils import coarse_to_fine as coarse_to_fine, get_warp_points as get_warp_points

def optical_flow_tvl1(reference_image, moving_image, *, attachment: int = ..., tightness: float = ..., num_warp: int = ..., num_iter: int = ..., tol: float = ..., prefilter: bool = ..., dtype=...): ...
def optical_flow_ilk(reference_image, moving_image, *, radius: int = ..., num_warp: int = ..., gaussian: bool = ..., prefilter: bool = ..., dtype=...): ...
