from networkx.testing import assert_edges_equal as assert_edges_equal, assert_graphs_equal as assert_graphs_equal, assert_nodes_equal as assert_nodes_equal

class _GenericTest: ...

class TestNodesEqual(_GenericTest):
    def test_nodes_equal(self) -> None: ...
    def test_nodes_not_equal(self) -> None: ...
    def test_nodes_with_data_equal(self) -> None: ...
    def test_edges_with_data_not_equal(self) -> None: ...

class TestEdgesEqual(_GenericTest):
    def test_edges_equal(self) -> None: ...
    def test_edges_not_equal(self) -> None: ...
    def test_edges_with_data_equal(self) -> None: ...
    def test_edges_with_data_not_equal(self) -> None: ...
    def test_no_edges(self) -> None: ...
    def test_duplicate_edges(self) -> None: ...
    def test_duplicate_edges_with_data(self) -> None: ...
    def test_order_of_edges_with_data(self) -> None: ...
    def test_order_of_multiedges(self) -> None: ...
    def test_order_of_edges_with_keys(self) -> None: ...

class TestGraphsEqual(_GenericTest):
    def test_graphs_equal(self) -> None: ...
    def test_digraphs_equal(self) -> None: ...
    def test_multigraphs_equal(self) -> None: ...
    def test_multidigraphs_equal(self) -> None: ...
    def test_graphs_not_equal(self) -> None: ...
    def test_graphs_not_equal2(self) -> None: ...
    def test_graphs_not_equal3(self) -> None: ...
