from .colorconv import lab2lch as lab2lch

def deltaE_cie76(lab1, lab2, channel_axis: int = ...): ...
def deltaE_ciede94(lab1, lab2, kH: int = ..., kC: int = ..., kL: int = ..., k1: float = ..., k2: float = ..., *, channel_axis: int = ...): ...
def deltaE_ciede2000(lab1, lab2, kL: int = ..., kC: int = ..., kH: int = ..., *, channel_axis: int = ...): ...
def deltaE_cmc(lab1, lab2, kL: int = ..., kC: int = ..., *, channel_axis: int = ...): ...
def get_dH2(lab1, lab2, *, channel_axis: int = ...): ...
