from typing import Any

def add(*args, **kwargs) -> Any: ...
def brightness(*args, **kwargs) -> Any: ...
def gamma(*args, **kwargs) -> Any: ...
def hsv_add(*args, **kwargs) -> Any: ...
def hsv_multiply(*args, **kwargs) -> Any: ...
def multiply(*args, **kwargs) -> Any: ...
def py_hsv_2_rgb(*args, **kwargs) -> Any: ...
def py_rgb_2_hsv(*args, **kwargs) -> Any: ...
def sigmoid_gamma(*args, **kwargs) -> Any: ...
