from _typeshed import Incomplete

def imread(fname, dtype: Incomplete | None = ..., img_num: Incomplete | None = ..., **kwargs): ...
def imsave(fname, arr, format_str: Incomplete | None = ..., **kwargs) -> None: ...
