from _typeshed import Incomplete

class DisjointSet:
    n_subsets: int
    def __init__(self, elements: Incomplete | None = ...) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, x) -> bool: ...
    def __getitem__(self, x): ...
    def add(self, x) -> None: ...
    def merge(self, x, y): ...
    def connected(self, x, y): ...
    def subset(self, x): ...
    def subset_size(self, x): ...
    def subsets(self): ...
