from typing import Any, ClassVar

class Cell:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def get_faces(self, *args, **kwargs) -> Any: ...
    def get_normals(self, *args, **kwargs) -> Any: ...
    def get_values(self, *args, **kwargs) -> Any: ...
    def get_vertices(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Lut:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class LutProvider:
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_LutProvider(*args, **kwargs) -> Any: ...
def marching_cubes(im, doubleisovalue, LutProviderluts, intst = ..., intclassic = ...) -> Any: ...
def remove_degenerate_faces(*args, **kwargs) -> Any: ...
