from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def _append_tris(*args, **kwargs) -> Any: ...
def iterate_and_store_3d(*args, **kwargs) -> Any: ...
def unpack_unique_verts(*args, **kwargs) -> Any: ...
