from typing import Any

_int64_max: int
group_cummax: fused_cython_function
group_cummin: fused_cython_function
group_cumsum: fused_cython_function
group_last: fused_cython_function
group_max: fused_cython_function
group_mean: fused_cython_function
group_min: fused_cython_function
group_nth: fused_cython_function
group_ohlc: fused_cython_function
group_prod: fused_cython_function
group_quantile: fused_cython_function
group_rank: fused_cython_function
group_sum: fused_cython_function
group_var: fused_cython_function
rank_1d: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def ensure_platform_int(*args, **kwargs) -> Any: ...
def group_any_all(*args, **kwargs) -> Any: ...
def group_cumprod_float64(*args, **kwargs) -> Any: ...
def group_fillna_indexer(*args, **kwargs) -> Any: ...
def group_median_float64(*args, **kwargs) -> Any: ...
def group_shift_indexer(*args, **kwargs) -> Any: ...
def groupsort_indexer(*args, **kwargs) -> Any: ...
def take_2d_axis1_float64_float64(*args, **kwargs) -> Any: ...
