from typing import Any

class NDFrameIndexerBase:
    name: Any
    ndim: Any
    obj: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_NDFrameIndexerBase(*args, **kwargs) -> Any: ...
