from typing import Any, ClassVar

_SIZE_CUTOFF: int

class BaseMultiIndexCodesEngine:
    def __init__(self, *args, **kwargs) -> None: ...
    def _codes_to_ints(self, *args, **kwargs) -> Any: ...
    def _extract_level_codes(self, *args, **kwargs) -> Any: ...
    def get_indexer(self, *args, **kwargs) -> Any: ...
    def get_indexer_non_unique(self, *args, **kwargs) -> Any: ...
    def get_indexer_with_fill(self, *args, **kwargs) -> Any: ...
    def get_loc(self, *args, **kwargs) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class BoolEngine(UInt8Engine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Complex128Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Complex64Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class DatetimeEngine(Int64Engine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_loc(self, *args, **kwargs) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ExtensionEngine(SharedEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Float32Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Float64Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IndexEngine:
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    is_mapping_populated: Any
    is_monotonic_decreasing: Any
    is_monotonic_increasing: Any
    is_unique: Any
    mapping: Any
    over_size_threshold: Any
    values: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def clear_mapping(self, *args, **kwargs) -> Any: ...
    def get_indexer(self, *args, **kwargs) -> Any: ...
    def get_indexer_non_unique(self, *args, **kwargs) -> Any: ...
    def get_loc(self, *args, **kwargs) -> Any: ...
    def sizeof(self, *args, **kwargs) -> Any: ...
    def __contains__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
    def __sizeof__(self) -> Any: ...

class Int16Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Int32Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Int64Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Int8Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ObjectEngine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class PeriodEngine(Int64Engine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def get_loc(self, *args, **kwargs) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class TimedeltaEngine(DatetimeEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class UInt16Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class UInt32Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class UInt64Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class UInt8Engine(IndexEngine):
    __pyx_vtable__: ClassVar[PyCapsule] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_BaseMultiIndexCodesEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_BoolEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Complex128Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Complex64Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_DatetimeEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def __pyx_unpickle_ExtensionEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Float32Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Float64Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_IndexEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Int16Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Int32Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Int64Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_Int8Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_ObjectEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_PeriodEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_SharedEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_TimedeltaEngine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_UInt16Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_UInt32Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_UInt64Engine(*args, **kwargs) -> Any: ...
def __pyx_unpickle_UInt8Engine(*args, **kwargs) -> Any: ...
