from typing import Any

asof_join_backward_on_X_by_Y: fused_cython_function
asof_join_forward_on_X_by_Y: fused_cython_function
asof_join_nearest_on_X_by_Y: fused_cython_function
inner_join_indexer: fused_cython_function
left_join_indexer: fused_cython_function
left_join_indexer_unique: fused_cython_function
outer_join_indexer: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def ffill_indexer(*args, **kwargs) -> Any: ...
def full_outer_join(*args, **kwargs) -> Any: ...
def groupsort_indexer(*args, **kwargs) -> Any: ...
def inner_join(*args, **kwargs) -> Any: ...
def left_outer_join(*args, **kwargs) -> Any: ...
