from typing import Any

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def maybe_convert_bool(*args, **kwargs) -> Any: ...
def scalar_binop(*args, **kwargs) -> Any: ...
def scalar_compare(*args, **kwargs) -> Any: ...
def vec_binop(*args, **kwargs) -> Any: ...
def vec_compare(*args, **kwargs) -> Any: ...
