from typing import Any

class AxisProperty:
    axis: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __delete__(self, *args, **kwargs) -> Any: ...
    def __get__(self, instance, owner) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __set__(self, instance, value) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class CachedProperty:
    fget: Any
    name: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __delete__(self, *args, **kwargs) -> Any: ...
    def __get__(self, instance, owner) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __set__(self, instance, value) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class cache_readonly:
    fget: Any
    name: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __delete__(self, *args, **kwargs) -> Any: ...
    def __get__(self, instance, owner) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __set__(self, instance, value) -> Any: ...
    def __setstate__(self, state) -> Any: ...

def __pyx_unpickle_AxisProperty(*args, **kwargs) -> Any: ...
def __pyx_unpickle_CachedProperty(*args, **kwargs) -> Any: ...
