from typing import Any

max_len_string_array: fused_cython_function

def __pyx_unpickle_Enum(*args, **kwargs) -> Any: ...
def convert_json_to_lines(*args, **kwargs) -> Any: ...
def string_array_replace_from_nan_rep(*args, **kwargs) -> Any: ...
def word_len(*args, **kwargs) -> Any: ...
def write_csv_rows(*args, **kwargs) -> Any: ...
