from . import dxf as dxf, svg_io as svg_io
from ... import util as util
from _typeshed import Incomplete

def export_path(path, file_type: Incomplete | None = ..., file_obj: Incomplete | None = ..., **kwargs): ...
def export_dict(path): ...
