from scipy._lib._testutils import check_free_memory as check_free_memory
from scipy.sparse import bsr_matrix as bsr_matrix, coo_matrix as coo_matrix, csc_matrix as csc_matrix, csr_matrix as csr_matrix, dia_matrix as dia_matrix
from scipy.sparse._sputils import supported_dtypes as supported_dtypes

def int_to_int8(n): ...
def test_exception() -> None: ...
def test_threads() -> None: ...
def test_regression_std_vector_dtypes() -> None: ...
def test_nnz_overflow() -> None: ...

class TestInt32Overflow:
    n: int
    def setup_method(self) -> None: ...
    def teardown_method(self) -> None: ...
    def test_coo_todense(self) -> None: ...
    def test_matvecs(self) -> None: ...
    def test_dia_matvec(self) -> None: ...
    def test_bsr_1_block(self, op): ...
    def test_bsr_n_block(self, op): ...

def test_csr_matmat_int64_overflow() -> None: ...
def test_upcast() -> None: ...
def test_endianness() -> None: ...
