from _typeshed import Incomplete

sparray_types: Incomplete
sparray_classes: Incomplete
A: Incomplete
B: Incomplete
X: Incomplete
sparrays: Incomplete
square_sparrays: Incomplete
eig_sparrays: Incomplete
parametrize_sparrays: Incomplete
parametrize_square_sparrays: Incomplete
parametrize_eig_sparrays: Incomplete

def test_sum(A) -> None: ...
def test_mean(A) -> None: ...
def test_min_max(A) -> None: ...
def test_todense(A) -> None: ...
def test_indexing(A) -> None: ...
def test_dense_addition(A) -> None: ...
def test_sparse_addition(A) -> None: ...
def test_elementwise_mul(A) -> None: ...
def test_elementwise_rmul(A) -> None: ...
def test_matmul(A) -> None: ...
def test_pow(B) -> None: ...
def test_sparse_divide(A) -> None: ...
def test_sparse_dense_divide(A) -> None: ...
def test_dense_divide(A) -> None: ...
def test_no_A_attr(A) -> None: ...
def test_no_H_attr(A) -> None: ...
def test_getrow_getcol(A) -> None: ...
def test_as_linearoperator(A) -> None: ...
def test_inv(B) -> None: ...
def test_expm(B) -> None: ...
def test_expm_multiply(B) -> None: ...
def test_norm(A) -> None: ...
def test_onenormest(B) -> None: ...
def test_spsolve(B) -> None: ...
def test_spsolve_triangular() -> None: ...
def test_factorized(B) -> None: ...
def test_solvers(B, solver) -> None: ...
def test_lstsqr(A, solver) -> None: ...
def test_eigs(X) -> None: ...
def test_eigsh(X) -> None: ...
def test_svds(X) -> None: ...
def test_splu() -> None: ...
def test_spilu() -> None: ...
def test_power_operator(A) -> None: ...
def test_index_dtype_compressed(cls, indices_attrs, expected_dtype) -> None: ...
def test_default_is_matrix_diags() -> None: ...
def test_default_is_matrix_eye() -> None: ...
def test_default_is_matrix_spdiags() -> None: ...
def test_default_is_matrix_identity() -> None: ...
def test_default_is_matrix_kron_dense() -> None: ...
def test_default_is_matrix_kron_sparse() -> None: ...
def test_default_is_matrix_kronsum() -> None: ...
def test_default_is_matrix_random() -> None: ...
def test_default_is_matrix_rand() -> None: ...
def test_default_is_matrix_stacks(fn) -> None: ...
def test_blocks_default_construction_fn_matrices() -> None: ...
def test_format_property() -> None: ...
def test_issparse() -> None: ...
def test_isspmatrix() -> None: ...
def test_isspmatrix_format(fmt, fn) -> None: ...
