from _typeshed import Incomplete
from scipy.sparse import bsr_matrix as bsr_matrix, coo_matrix as coo_matrix, csc_matrix as csc_matrix, csr_matrix as csr_matrix, dia_matrix as dia_matrix, dok_matrix as dok_matrix, load_npz as load_npz, save_npz as save_npz

DATA_DIR: Incomplete

def test_save_and_load_random() -> None: ...
def test_save_and_load_empty() -> None: ...
def test_save_and_load_one_entry() -> None: ...
def test_malicious_load(): ...
def test_py23_compatibility() -> None: ...
def test_implemented_error() -> None: ...
