from _typeshed import Incomplete
from scipy.sparse import csr_matrix as csr_matrix

class TestExtract:
    cases: Incomplete
    def setup_method(self) -> None: ...
    def find(self) -> None: ...
    def test_tril(self) -> None: ...
    def test_triu(self) -> None: ...
