from _typeshed import Incomplete
from scipy._lib._testutils import check_free_memory as check_free_memory
from scipy._lib._util import check_random_state as check_random_state
from scipy.sparse import coo_matrix as coo_matrix, csr_matrix as csr_matrix
from scipy.sparse._sputils import matrix as matrix

sparse_formats: Incomplete

class TestConstructUtils:
    def test_spdiags(self) -> None: ...
    def test_diags(self) -> None: ...
    def test_diags_default(self) -> None: ...
    def test_diags_default_bad(self) -> None: ...
    def test_diags_bad(self) -> None: ...
    def test_diags_vs_diag(self) -> None: ...
    def test_diags_dtype(self) -> None: ...
    def test_diags_one_diagonal(self) -> None: ...
    def test_diags_empty(self) -> None: ...
    def test_identity(self) -> None: ...
    def test_eye(self) -> None: ...
    def test_eye_one(self) -> None: ...
    def test_kron(self) -> None: ...
    def test_kron_large(self) -> None: ...
    def test_kronsum(self) -> None: ...
    def test_vstack(self) -> None: ...
    def test_hstack(self) -> None: ...
    def test_bmat(self) -> None: ...
    def test_concatenate_int32_overflow(self) -> None: ...
    def test_block_diag_basic(self) -> None: ...
    def test_block_diag_scalar_1d_args(self) -> None: ...
    def test_block_diag_1(self) -> None: ...
    def test_block_diag_sparse_matrices(self) -> None: ...
    def test_random_sampling(self): ...
    def test_rand(self) -> None: ...
    def test_randn(self) -> None: ...
    def test_random_accept_str_dtype(self) -> None: ...
    def test_random_sparse_matrix_returns_correct_number_of_non_zero_elements(self) -> None: ...
