from scipy.sparse._sputils import matrix as matrix

class TestSparseUtils:
    def test_upcast(self) -> None: ...
    def test_getdtype(self) -> None: ...
    def test_isscalarlike(self) -> None: ...
    def test_isintlike(self) -> None: ...
    def test_isshape(self) -> None: ...
    def test_issequence(self) -> None: ...
    def test_ismatrix(self) -> None: ...
    def test_isdense(self) -> None: ...
    def test_validateaxis(self) -> None: ...
    def test_get_index_dtype(self) -> None: ...
    def test_check_shape_overflow(self) -> None: ...
    def test_matrix(self) -> None: ...
    def test_asmatrix(self) -> None: ...
