import abc
from ..util import ABC as ABC

class Visuals(ABC, metaclass=abc.ABCMeta):
    @property
    @abc.abstractmethod
    def kind(self): ...
    @abc.abstractmethod
    def update_vertices(self,mask): ...
    @abc.abstractmethod
    def update_faces(self,mask): ...
    @abc.abstractmethod
    def concatenate(self, other): ...
    @abc.abstractmethod
    def __hash__(self): ...
    @abc.abstractmethod
    def copy(self): ...
    def __add__(self, other): ...
