from .. import caching as caching, grouping as grouping, util as util
from .base import Visuals as Visuals
from _typeshed import Incomplete

class ColorVisuals(Visuals):
    mesh: Incomplete
    defaults: Incomplete
    def __init__(self, mesh: Incomplete | None = ..., face_colors: Incomplete | None = ..., vertex_colors: Incomplete | None = ...) -> None: ...
    def transparency(self): ...
    @property
    def defined(self): ...
    @property
    def kind(self): ...
    def __hash__(self): ...
    def copy(self): ...
    @property
    def face_colors(self): ...
    @face_colors.setter
    def face_colors(self, values) -> None: ...
    @property
    def vertex_colors(self): ...
    @vertex_colors.setter
    def vertex_colors(self, values) -> None: ...
    def update_vertices(self, mask) -> None: ...
    def update_faces(self, mask) -> None: ...
    def face_subset(self, face_index): ...
    @property
    def main_color(self): ...
    def to_texture(self): ...
    def concatenate(self, other, *args): ...

class VertexColor(Visuals):
    obj: Incomplete
    def __init__(self, colors: Incomplete | None = ..., obj: Incomplete | None = ...) -> None: ...
    @property
    def kind(self): ...
    def update_vertices(self, mask) -> None: ...
    def update_faces(self, mask) -> None: ...
    @property
    def vertex_colors(self): ...
    @vertex_colors.setter
    def vertex_colors(self, data) -> None: ...
    def copy(self): ...
    def concatenate(self, other): ...
    def __hash__(self): ...

def to_rgba(colors, dtype=...): ...
def to_float(colors): ...
def hex_to_rgba(color): ...
def random_color(dtype=...): ...
def vertex_to_face_color(vertex_colors, faces): ...
def face_to_vertex_color(mesh, face_colors, dtype=...): ...
def colors_to_materials(colors, count: Incomplete | None = ...): ...
def linear_color_map(values, color_range: Incomplete | None = ...): ...
def interpolate(values, color_map: Incomplete | None = ..., dtype=...): ...
def uv_to_color(uv, image): ...
def uv_to_interpolated_color(uv, image): ...

DEFAULT_COLOR: Incomplete
