from _typeshed import Incomplete
from scipy.linalg import norm as norm
from scipy.sparse import SparseEfficiencyWarning as SparseEfficiencyWarning, csr_matrix as csr_matrix, kronsum as kronsum, spdiags as spdiags
from scipy.sparse.linalg import LinearOperator as LinearOperator, aslinearoperator as aslinearoperator
from scipy.sparse.linalg._isolve import bicg as bicg, bicgstab as bicgstab, cg as cg, cgs as cgs, gcrotmk as gcrotmk, gmres as gmres, lgmres as lgmres, minres as minres, qmr as qmr, tfqmr as tfqmr

def solver(request): ...

class Case:
    name: Incomplete
    A: Incomplete
    b: Incomplete
    skip: Incomplete
    nonconvergence: Incomplete
    def __init__(self, name, A, b: Incomplete | None = ..., skip: Incomplete | None = ..., nonconvergence: Incomplete | None = ...) -> None: ...

class IterativeParams:
    cases: Incomplete
    def __init__(self) -> None: ...

cases: Incomplete

def case(request): ...
def check_maxiter(solver, case) -> None: ...
def test_maxiter(solver, case) -> None: ...
def assert_normclose(a, b, tol: float = ...) -> None: ...
def check_convergence(solver, case) -> None: ...
def test_convergence(solver, case) -> None: ...
def check_precond_dummy(solver, case): ...
def test_precond_dummy(solver, case) -> None: ...
def check_precond_inverse(solver, case): ...
def test_precond_inverse(solver, case) -> None: ...
def test_reentrancy(solver) -> None: ...
def test_atol(solver) -> None: ...
def test_zero_rhs(solver) -> None: ...
def test_maxiter_worsening(solver) -> None: ...
def test_x0_working(solver) -> None: ...
def test_x0_equals_Mb(solver, case) -> None: ...
def test_show(case, capsys) -> None: ...

class TestQMR:
    def test_leftright_precond(self): ...

class TestGMRES:
    def test_basic(self) -> None: ...
    def test_callback(self): ...
    def test_abi(self) -> None: ...
    def test_atol_legacy(self) -> None: ...
    def test_defective_precond_breakdown(self) -> None: ...
    def test_defective_matrix_breakdown(self) -> None: ...
    def test_callback_type(self) -> None: ...
    def test_callback_x_monotonic(self) -> None: ...
    def test_restrt_dep(self) -> None: ...
