from _typeshed import Incomplete
from scipy.linalg import norm as norm
from scipy.sparse import csr_matrix as csr_matrix, eye as eye, rand as rand
from scipy.sparse.linalg import splu as splu
from scipy.sparse.linalg._interface import LinearOperator as LinearOperator
from scipy.sparse.linalg._isolve import gcrotmk as gcrotmk, gmres as gmres

Am: Incomplete
b: Incomplete
count: Incomplete

def matvec(v): ...

A: Incomplete

def do_solve(**kw): ...

class TestGCROTMK:
    def test_preconditioner(self) -> None: ...
    def test_arnoldi(self) -> None: ...
    def test_cornercase(self) -> None: ...
    def test_nans(self) -> None: ...
    def test_truncate(self) -> None: ...
    def test_CU(self) -> None: ...
    def test_denormals(self) -> None: ...
