name: "Publish to PyPI"
on:
    release
jobs:
    make_sdist:
        name: Make SDist
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Optional, use if you use setuptools_scm
            submodules: true  # Optional, use if you have submodules

        - name: Build SDist
          run: pipx run build --sdist

        - uses: actions/upload-artifact@v4
          with:
            name: cibw-sdist
            path: dist/*.tar.gz

    upload_all:
        needs: [build_wheels, make_sdist]
        environment: pypi
        permissions:
          id-token: write
        runs-on: ubuntu-latest
        if: github.event_name == 'release' && github.event.action == 'published'
        steps:
        - uses: actions/download-artifact@v4
          with:
            pattern: cibw-*
            path: dist
            merge-multiple: true

        - uses: pypa/gh-action-pypi-publish@release/v1
